### ISSUE TITLE
1.16.2 Crash on server join with chocapic13's shader

### ISSUE THREAD

**Issue by drakosoldier298** [Chocohead/OptiFabric#10]
https://gist.github.com/drakosoldier298/d002b7214d7ca590f784473de2de555c

**Comment by Chocohead** [comment]
The crash looks very similar to https://github.com/sp614x/optifine/issues/4558#issuecomment-683346599, might want to follow that issue given I strongly doubt there's anything OptiFabric can do to fix a driver crash.
