### ISSUE TITLE
Chrash @ Startup

### ISSUE THREAD

**Issue by Timtendo12** [Chocohead/OptiFabric#100]
I have the latest version for 1.16.3 i tried a older version of optifine but that also didnt work. It keeps giving me this issue:

```
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Afsluitcode: -1
```

**Comment by Chocohead** [comment]
We'll need the full crash report from the `crash-reports` folder, the single header line is doesn't provide any insights on its own.
