### ISSUE TITLE
taking a screen shot crash the game

### ISSUE THREAD

**Issue by Danjhop4** [Chocohead/OptiFabric#1005]
if you try and take a screen shot it crashes the game
[crash-2023-03-21_17.48.16-client.txt](https://github.com/Chocohead/OptiFabric/files/11031968/crash-2023-03-21_17.48.16-client.txt)
heres the crash file

**Comment by Danjhop4** [comment]
its modded to accept 1.19.4

**Comment by ghost** [comment]
There is a new action build now danjhop, try that

**Comment by ghost** [comment]
Also modding builds is probably not supported, the latest action natively supports 1.19.4

**Comment by Danjhop4** [comment]
Ok

**Comment by Danjhop4** [comment]
Will build that

**Comment by Danjhop4** [comment]
> Also modding builds is probably not supported, the latest action natively supports 1.19.4

Changed the fabric.mod.json that’s all

**Comment by ghost** [comment]
That can cause unforeseen issues

**Comment by Danjhop4** [comment]
nope still doing it

**Comment by ghost** [comment]
Well then give the dev time, it's free after all

Just like optifine danjhop

The deva offer amazing things for free so be grateful it exists at all

**Comment by Danjhop4** [comment]
> Well then give the dev time, it's free after all
> 
> Just like optifine danjhop
> 
> The deva offer amazing things for free so be grateful it exists at all

was not being rude i just told them what i did
