### ISSUE TITLE
Optifabric Crashing While Trying To Get It Running On 1.19.3

### ISSUE THREAD

**Issue by Thegamerprogrammer** [Chocohead/OptiFabric#1006]
I Downloaded The Plugin From Curseforge and installed fabric 0.14.7 1.19.3 and Placed Optifine Like Said In The Instructions But I Get This Error: `Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'OptiFabric' (optifabric) 1.13.16 with any version that is compatible with:
		 - minecraft 1.19.3
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.5.2 with any version that is compatible with:
		 - optifabric, any version
	 - Replace mod 'Just Enough Items' (jei) 11.0.0.206 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.5.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'OptiFabric' (optifabric) 1.13.16 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18, version 1.18.1, version 1.18.2, version 1.19, version 1.19.1 or version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'Just Enough Items' (jei) 11.0.0.206 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Is There A Version For 1.19.3 and if there is kindly please tell me how to install it

**Comment by topia** [comment]
There is no release builds to support 1.19.3 or later because optifine hasn't released the non-pre version yet. For beta, download the artifacts zip of the latest build from "Actions", and put `optifabric-x.x.jar` from it.

By the way, there is a known incompatibility between JEI and optifine now, and the immersive portals mod declares incompatible with optifine as stated.

**Comment by Thegamerprogrammer** [comment]
Thanks This Fixed My Problem!
