### ISSUE TITLE
Not compatible with newest 1.16.2 OPTIFINE

### ISSUE THREAD

**Issue by TooManyArial** [Chocohead/OptiFabric#102]
The Newest OPTIFABRIC for 1.16.2 is not compatible with the newest OPTIFINE for 1.16.2. not sure what to do, I just posted this to let you know.

**Comment by vinnyg0621** [comment]
optifine isn't all in caps

**Comment by Titaniumtown** [comment]
optifabric is for 1.16.4 lol
