### ISSUE TITLE
Request compatibility with java21

### ISSUE THREAD

**Issue by aaaapai** [Chocohead/OptiFabric#1028]
Updating to java21 can bring great optimization effect. Using java17.0.7 to play minecraft 1.19.4 on my device seems to wander between 39 and 52 frames, and using java21 to play seems to wander between 60 and 82 frames. Optifine compatible, forge incompatible, fabric compatible, optifabric incompatible, sodium incompatible.
I don't know if the java21 runtime I installed is inherently problematic

**Comment by aaaapai** [comment]
Journal:
[latestlog.txt](https://github.com/Chocohead/OptiFabric/files/11132612/latestlog.txt)

**Comment by Chocohead** [comment]
This is all down to the version of ASM being used. Classes compiled with Java 21 need [ASM 9.5](https://asm.ow2.io/versions.html#9.5) in order for ASM to be able to read them, which neither Fabric nor Forge are currently using. Once they update, Mixin will work, which will fix OptiFabric and should fix Sodium.
