### ISSUE TITLE
[1.8.7 / 1.16.4_HD_U_G5] Crash when trying to break AE2 cables

### ISSUE THREAD

**Issue by yorii** [Chocohead/OptiFabric#103]
Hello, I saw the patch notes for 1.8.7 and got excited that it had Applied Energistics 2 listed as compatible, but I still get a crash whenever I try to break any AE2 cable, same or similar crash also happens with Modern Industrialization pipes.

Here is my log from when breaking an AE2 cable: https://0bin.net/paste/Ck-OoRi+#6uk+0u8iLKZheeYWQp4nWYpLb8Wb6sKYYnJ-sBmrUQc

Maybe I have some setting wrong or another incompatible mod loaded? It all works fine without Optifine/Optifabric.

**Comment by Chocohead** [comment]
Think this should be fixed now, always hard to tell when there's so many different rendering related methods which OptiFine plays about with. Do say if there's still some things having problems.
