### ISSUE TITLE
Colormap issue with fabric api

### ISSUE THREAD

**Issue by Smognoggler** [Chocohead/OptiFabric#104]
An Optifine water colormap is not used for flowing water if fabric api 0.26.0 is included. This is along with Optifabric 1.8.7, Optifine G5, and a texture pack that only adds the colormap.
![2020-11-19_01 24 23](https://user-images.githubusercontent.com/74704914/99640336-fb0bf500-2a05-11eb-8718-13aeec635ac8.png)

**Comment by Chocohead** [comment]
Surprised no one had noticed sooner really, missed a check for flowing water when making sure it was tintable in the first place
