### ISSUE TITLE
[1.8.9] ME Chest also crashing

### ISSUE THREAD

**Issue by yorii** [Chocohead/OptiFabric#106]
Thanks again for fixing the cable/pipe issue in 1.8.9!

Here is a follow-up regarding related render methods:

https://paste.ee/p/MEMIU

I tried fixing it myself but I couldn't figure it out 😄

**Comment by IMS212** [comment]
1.8.9? last time i checked optifabric didnt exist for 1.8 (i know legacy fabric exists)

**Comment by yorii** [comment]
> 1.8.9? last time i checked optifabric didnt exist for 1.8 (i know legacy fabric exists)

Optifabric 1.8.9 😝 

All latest version with 1.16.4 HD U G5
