### ISSUE TITLE
v.1.13.24

### ISSUE THREAD

**Issue by pufarina** [Chocohead/OptiFabric#1060]
Doesn't even get to the mojang logo, crashes instantly, sends the user back to the mc launcher. I know the 1.19.4 version is still in beta, but this really needs to get fixed.
error code -1

**Comment by TprScruffy** [comment]
I also have this issue with using either l3 or l4 versions of optifine for 1.19.4

**Comment by Drift91** [comment]
Have you tried downgrading your Fabric API? See https://github.com/Chocohead/OptiFabric/issues/1053 for details.

**Comment by pufarina** [comment]
> Have you tried downgrading your Fabric API? See #1053 for details.

Yeah, I just tried, and it fixed the issue. Still, they should fix the incompatability with the latest fabric api version, due to the incompatability of other mobs with 0.80.0
