### ISSUE TITLE
Incompatible with Fabric API 0.81.0 or newer.

### ISSUE THREAD

**Issue by Haphosm** [Chocohead/OptiFabric#1065]
Game crashes upon launch, if both optifabric and optifine is in the mods folder if Fabric API is newer than 0.80.0 (0.81.0, 0.82.0).

**Comment by AuroraDoesCode** [comment]
confirmed

**Comment by behindyounow** [comment]
My mods folder has 4 files:
optifabric-1.13.24
OptiFine_1.19.4_HD_U_I4
replaymod-1.19.4-2.6.12
fabric-api-0.80.0+1.19.4

Still crashes. How come?

EDIT: It's the latest replaymod file that crashes it. Guess I need to wait to use that one, without it everything loads fine.

**Comment by FranchDressin** [comment]
> My mods folder has 4 files: optifabric-1.13.24 OptiFine_1.19.4_HD_U_I4 replaymod-1.19.4-2.6.12 fabric-api-0.80.0+1.19.4
> 
> Still crashes. How come?
> 
> EDIT: It's the latest replaymod file that crashes it. Guess I need to wait to use that one, without it everything loads fine.

Can Confirm that this combination of fabric api, optifabric, and optfine are stable, and playable in 1.19.4
![image](https://github.com/Chocohead/OptiFabric/assets/56232553/a22f9900-632c-4f50-b167-144896945554)

See you guys again when 1.20 doesn't work!

**Comment by dawnfire9** [comment]
fabric-api 0.84.0 1.19.4
crash
[log](https://mclo.gs/MgqbHhz)
