### ISSUE TITLE
optifabric_1.19.4 jar

### ISSUE THREAD

**Issue by VIDEOGRAFF** [Chocohead/OptiFabric#1066]
Optifabric 1.19 .4 Beta version  its not working properly on multiple mods  !
 
/ like ,, This'll
     Anyone mod only support this version why. please help me and another minecraft players (optifine ,mod menu & replymod)
         Please dear Sir fix this bug I hope. @Chocohead /OptiFabric .

**Comment by joshbarrass** [comment]
A workaround is to use Fabric API 0.80.0 (see #1065)
