### ISSUE TITLE
Shaders are not compatible with Satin Warning: I don't have Satin installed.

### ISSUE THREAD

**Issue by AzureMonument** [Chocohead/OptiFabric#107]
As stated in the title of the issue, I keep getting the warning from optifne or optifabric (I'm assuming the later, as I can't get optifine to run on fabric without it and from my research [satin ](https://www.curseforge.com/minecraft/mc-mods/satin-api)is a fabric mod).

Uhm. Not much more I can say. I'm trying to upload a couple pictures of the 's' section of my modlist and the picture of the warning, but Github just keeps popping up with "Something went really wrong, and we can't process that file".

Anyway, thanks for your time.

**Comment by DerRoboMeister** [comment]
Do you happen to have the Blur mod installed? Because that one triggered the warning for me.

**Comment by IMS212** [comment]
yes, blur mod uses Satin (Satin is a library used by mods, not a mod itself)

**Comment by AzureMonument** [comment]
Welp. That'd do it, I do indeed have blur.

**Comment by Chocohead** [comment]
It's still on the todo list to see if I get can get them working together fully, it seems a little inconsistent when Satin does and doesn't break.
