### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by landmine111** [Chocohead/OptiFabric#1079]
when is 1.20 comming out

**Comment by peepeepoopoocaca** [comment]
Creator hasn't been active for a few weeks, so I assume they're busy. Hopefully it'll come out soon, but I partially blame the fact that Optifine hasn't fully released for 1.20. There's pre-releases, but certain features of Optifine have not been finalized for 1.20.

**Comment by Jacob22549** [comment]
good day if optifabric could for version 1.20??

**Comment by Jacob22549** [comment]
> Creator hasn't been active for a few weeks, so I assume they're busy. Hopefully it'll come out soon, but I partially blame the fact that Optifine hasn't fully released for 1.20. There's pre-releases, but certain features of Optifine have not been finalized for 1.20.

optifine 1.20 has already been fully released, check me out.

**Comment by topia** [comment]
For curiosity, what is your definition for fully released? I can find only preview versions.
https://optifine.net/downloads

**Comment by peepeepoopoocaca** [comment]
> optifine 1.20 has already been fully released, check me out.

No it hasn't. Every version from 1.20 to 1.20.1 says "Preview Version" on the Optifine website. Not all features have been implemented yet. Please learn to read.
