### ISSUE TITLE
issue with version 1.16.4

### ISSUE THREAD

**Issue by d-prob** [Chocohead/OptiFabric#108]
i have 1.16.4 versions on both optifine and optifabric but it opens the error screen:

![image](https://user-images.githubusercontent.com/57526976/99899139-dc497f00-2ce1-11eb-8644-666bb149f66e.png)

**Comment by CTAK-CO6AK** [comment]
Check your minecraft version

**Comment by d-prob** [comment]
yep, 1.16.4.

**Comment by Chocohead** [comment]
Make sure the version of Optifine you're using matches the version of Minecraft you're using. Whilst OptiFabric can span between 1.16.1 and 1.16.4, Optifine can't.
