### ISSUE TITLE
Any news about update for 1.20.1?

### ISSUE THREAD

**Issue by KelevraW7** [Chocohead/OptiFabric#1088]
I'm a big fan of your work and I would like to know if there is an approximate release date of OptiFabric in version 1.20.1. 

I'm going to start my own server with friends and I need to know if we will use it or if we need other alternatives. 

Thank you so much!

**Comment by GamebP** [comment]
I need it, my resource pack requires optifine.

**Comment by ChinoKou** [comment]
> I need it, my resource pack requires optifine.

You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"

**Comment by KelevraW7** [comment]
> > I need it, my resource pack requires optifine.
> 
> You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"

THANK YOU. Although I have tried to place the three most updated mods and I get this error. What can happen?

![image](https://github.com/Chocohead/OptiFabric/assets/138030004/e69a5a41-1c87-437c-9861-a7db2befdbef)

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Entity Model Features' (entity_model_features) 0.2.11 with any version that is compatible with:
		 - cem 0.8.0
Unmet dependency listing:
	 - Mod 'Entity Model Features' (entity_model_features) 0.2.11 is incompatible with any version of mod 'Custom Entity Models' (cem), but a matching version is present: 0.8.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by GamebP** [comment]
> > I need it, my resource pack requires optifine.
> 
> You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"

You might have the right answer. But the mods you just said are not-highly downloaded. 
When I looked at the pages, it still says in beta or in release.
Thanks.

**Comment by haohao927** [comment]
> > > I need it, my resource pack requires optifine.
> > 
> > 
> > You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"
> 
> THANK YOU. Although I have tried to place the three most updated mods and I get this error. What can happen?
> 
> ![image](https://user-images.githubusercontent.com/138030004/252474423-e69a5a41-1c87-437c-9861-a7db2befdbef.png)
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Replace mod 'Entity Model Features' (entity_model_features) 0.2.11 with any version that is compatible with: - cem 0.8.0 Unmet dependency listing: - Mod 'Entity Model Features' (entity_model_features) 0.2.11 is incompatible with any version of mod 'Custom Entity Models' (cem), but a matching version is present: 0.8.0! at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)



> > > I need it, my resource pack requires optifine.
> > 
> > 
> > You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"
> 
> THANK YOU. Although I have tried to place the three most updated mods and I get this error. What can happen?
> 
> ![image](https://user-images.githubusercontent.com/138030004/252474423-e69a5a41-1c87-437c-9861-a7db2befdbef.png)
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Replace mod 'Entity Model Features' (entity_model_features) 0.2.11 with any version that is compatible with: - cem 0.8.0 Unmet dependency listing: - Mod 'Entity Model Features' (entity_model_features) 0.2.11 is incompatible with any version of mod 'Custom Entity Models' (cem), but a matching version is present: 0.8.0! at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Sorry,I haven't express clearly."Custom Entity Models" is not Incompatible with "Entity Model Features".You can choose one of it to use in your game. What about "Entity Texture Features" ? It can compatible with "Custom Entity Models" or "Entity Model Features".In a brief,use ETF+CEM or ETF+EMF.Use which one depend on your resource pack work situation.Optifine Cem is hard to reproduce,so use these mods not sure every resourcepacks can work perfect.

**Comment by ChinoKou** [comment]
> > > I need it, my resource pack requires optifine.
> > 
> > 
> > You can use these mods "Entity Model Features" "Entity Texture Features" "Custom Entity Models"
> 
> THANK YOU. Although I have tried to place the three most updated mods and I get this error. What can happen?
> 
> ![image](https://user-images.githubusercontent.com/138030004/252474423-e69a5a41-1c87-437c-9861-a7db2befdbef.png)
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Replace mod 'Entity Model Features' (entity_model_features) 0.2.11 with any version that is compatible with: - cem 0.8.0 Unmet dependency listing: - Mod 'Entity Model Features' (entity_model_features) 0.2.11 is incompatible with any version of mod 'Custom Entity Models' (cem), but a matching version is present: 0.8.0! at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Sorry,I haven't express clearly."Custom Entity Models" is not Incompatible with "Entity Model Features".You can choose one of it to use in your game. 
What about "Entity Texture Features" ? It can compatible with "Custom Entity Models" or "Entity Model Features".
In a brief,you can use ETF+CEM or ETF+EMF.
Use which one depend on your resource pack work situation.Optifine Cem is hard to reproduce,so use these mods not sure every resourcepacks can work perfect.
