### ISSUE TITLE
[1.8.10 + 1.16.4 HD U G5] Edge case crash with connected textures.

### ISSUE THREAD

**Issue by yorii** [Chocohead/OptiFabric#109]
An AE2 cable placed next to a block of sandstone in some unknown specific manner causes a crash with Connected Textures setting set to Fast or Fancy, it does not happen with Connected Textures set to Off.

https://paste.ee/p/ajlzY

**Comment by yorii** [comment]
![2020-11-22_18 45 14](https://user-images.githubusercontent.com/7960287/99911186-e88a0800-2cf2-11eb-9b4f-ba0408d494a6.png)
This is where it is happening.

**Comment by yorii** [comment]
Replacing all the sandstone around the cable with regular stone also eliminates the issue.

**Comment by IMS212** [comment]
Does this happen on the forge version of ae2 and optifine?
