### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by JoeyFab** [Chocohead/OptiFabric#1091]
As im writing this optifine 1.20.1 just fully released  and i think it was optifabric for 1.19.4 where the day it fully released it it was available.

![image](https://github.com/Chocohead/OptiFabric/assets/133546842/36e2d089-2025-47be-a569-6b6b7474b7b3)

Thanks

**Comment by JoeyFab** [comment]
![image](https://github.com/Chocohead/OptiFabric/assets/133546842/07103180-c13a-4397-ad5a-a3df50d31eb8)

**Comment by kylerchin** [comment]
Duplicate of #1088, please close

**Comment by Reggiewaffel** [comment]
I'm looking forward to the Update. We'll have to be patient, we'll see when it comes.
