### ISSUE TITLE
[Waiting] Waiting for 1.20 & 1.20.1 support. 

### ISSUE THREAD

**Issue by GamebP** [Chocohead/OptiFabric#1094]
We wait for the support on the newer versions of minecraft. like 1.20 , 1.20.1 .
**I'm waiting beacuse I have custom animations in my resource pack. And it needs a optifabric.** 

_Fabric mods are most compatable with a high texturepack & shaders too._

**Comment by S4VAIBHAV** [comment]
I'm waiting too..🤓

**Comment by Chris123NT** [comment]
hopefully the support comes soon now that optifine is finalized for 1.20.1

**Comment by Gamerduck543** [comment]
Bro me too Choco please

**Comment by MCStara** [comment]
I just wanted to say thank you for working on this update, I see that it is being worked on on [#1095](https://github.com/Chocohead/OptiFabric/pull/1095) and I'm grateful to find info on it being updated as I use optifabric and have for years now and greatly appreciate and enjoy the mod. Looking forward to being able to -play 1.20 when all is settled :)
