### ISSUE TITLE
optifabric isnt working and crashing on startup

### ISSUE THREAD

**Issue by Tomskiiii** [Chocohead/OptiFabric#1103]
my first issue was i didnt have the optifine .jar file but i have that now but as soon as i added it the launcher would launch minecraft and instead would instantly crash the game and the exit code is 1

<img width="758" alt="Screenshot 2023-07-14 at 8 32 19 PM" src="https://github.com/Chocohead/OptiFabric/assets/139575030/55aebe73-03b8-4734-b5c9-3fd3acace41f">
<img width="758" alt="Screenshot 2023-07-14 at 8 32 47 PM" src="https://github.com/Chocohead/OptiFabric/assets/139575030/f81b7038-fda3-4b4c-8caa-6aff30b63292">

**Comment by topia** [comment]
Please upload the latest.log from Minecraft logs directory.

**Comment by Tomskiiii** [comment]
> Please upload the latest.log from Minecraft logs directory.

![Uploading Screenshot 2023-07-14 at 8.54.37 PM.png…]()

**Comment by Tomskiiii** [comment]
this is my latest .log> Please upload the latest.log from Minecraft logs directory.

<img width="1440" alt="Screenshot 2023-07-14 at 8 54 37 PM" src="https://github.com/Chocohead/OptiFabric/assets/139575030/6fb8a8f0-207b-432b-a811-47e9a75d05fe">

**Comment by topia** [comment]
According to your screenshot, there are some incompatibilities with "noclip" and optifine. but I don't know what noclip is. Maybe one of your mods contains it. if you can't find yourself, please upload log file fully.

**Comment by Tomskiiii** [comment]
> According to your screenshot, there are some incompatibilities with "noclip" and optifine. but I don't know what noclip is. Maybe one of your mods contains it. if you can't find yourself, please upload log file fully.

Thank you that worked basically it let's you clip through blocks and fly around I was using it to build but I'll find an alternative

**Comment by ghost** [comment]
similar issue here. would appreciate any help possible

[latest.log here](https://pastebin.com/zigSNdfT)

**Comment by topia** [comment]
> similar issue here. would appreciate any help possible
> 
> [latest.log here](https://pastebin.com/zigSNdfT)

```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> optifabric.compat.apoli-newerer.mixins.json:WorldRendererNewMixin from mod optifabric -> Apply Methods -> (Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZFZZZLnet/minecraft/class_4597$class_4598;)V:getEntity -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
```
The log says it failed with the optifabric compatibility layer for apoli, and origins mod contains apoli. It might be outdated, So I suggest you try without origins.

**Comment by ghost** [comment]
> > similar issue here. would appreciate any help possible
> > [latest.log here](https://pastebin.com/zigSNdfT)
> 
> ```
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> optifabric.compat.apoli-newerer.mixins.json:WorldRendererNewMixin from mod optifabric -> Apply Methods -> (Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZFZZZLnet/minecraft/class_4597$class_4598;)V:getEntity -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
> ```
> 
> The log says it failed with the optifabric compatibility layer for apoli, and origins mod contains apoli. It might be outdated, So I suggest you try without origins.

i tried, but Fabric gave me an error about needing a later cloth-config version despite already having one later than the version 9.0.92 it mentioned. we might look into alternatives to optifabric or just forgo it altogether

**Comment by AuroraDoesCode** [comment]
> > > similar issue here. would appreciate any help possible
> > > [latest.log here](https://pastebin.com/zigSNdfT)
> > 
> > 
> > ```
> > Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> optifabric.compat.apoli-newerer.mixins.json:WorldRendererNewMixin from mod optifabric -> Apply Methods -> (Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZFZZZLnet/minecraft/class_4597$class_4598;)V:getEntity -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The log says it failed with the optifabric compatibility layer for apoli, and origins mod contains apoli. It might be outdated, So I suggest you try without origins.
> 
> i tried, but Fabric gave me an error about needing a later cloth-config version despite already having one later than the version 9.0.92 it mentioned. we might look into alternatives to optifabric or just forgo it altogether

Freecam is the Alternative you want. Works fine with Optifabric / Optifine. Origins isnt supported.
