### ISSUE TITLE
Incompatible with carpet in 1.20.1

### ISSUE THREAD

**Issue by ChinoKou** [Chocohead/OptiFabric#1104]
latest.log :
https://pastebin.com/z0KF0rR1

**Comment by AuroraDoesCode** [comment]
Confirmed, carpet support needs updated

**Comment by YertsARG** [comment]
I don't understand how to fix it... I saw what you posted, but I don't understand what I have to do

**Comment by AuroraDoesCode** [comment]
https://github.com/Chocohead/OptiFabric/suites/14321155891/artifacts/805811889 That’s a build artifact with the fix for 1.19.3 - 1.20.1, you can also download it from the actions tab

**Comment by YertsARG** [comment]
Wooooooow! Thanks!
