### ISSUE TITLE
Incompatibility with Architectury

### ISSUE THREAD

**Issue by Toseflo** [Chocohead/OptiFabric#112]
OptiFabric is incompatible with Architectury.
Link: https://www.curseforge.com/minecraft/mc-mods/architectury-fabric

The game crashes before it even really starts loading.
For anyone who wants to use Slight GUI Modifications, downgrade Slight GUI Modifications to 1.5.1. This version doesn't require Architectury and you can start your game without Architectury.

**Comment by IMS212** [comment]
here's the crash https://pastebin.com/raw/YKnrU4sJ
