### ISSUE TITLE
issue with 1.16.4 minecraft

### ISSUE THREAD

**Issue by AFQSYKR** [Chocohead/OptiFabric#113]
I already have both versions, i can run 1.16.3 but I cant run 1.16.4 even I have both of them

![Screenshot (58)](https://user-images.githubusercontent.com/75354801/100834737-62668200-34a7-11eb-8613-e4ab84744f2a.png)

**Comment by IMS212** [comment]
You need to only have 1.16.4 optifine in your mods folder and no other versions.

**Comment by Chocohead** [comment]
As mentioned you need to make sure you include a version of Optifine which matches the version of Minecraft you're using
