### ISSUE TITLE
Optifabric + OptiFine_1.16.4_HD_U_G5 causes a crash

### ISSUE THREAD

**Issue by zachsai** [Chocohead/OptiFabric#115]
I am trying to play All of Fabric 3 1.16.4 Build version 2.5.0
I have to remove lithium because it is incompatible with optifabric.
After launching Optifabric version 1.8.10 with OptiFine_1.16.4_HD_U_G5
The game crashes.

https://discord.com/channels/570630340075454474/577535257356664845/784239659717754891

**Comment by IMS212** [comment]
probably related to #112 , might be fixed by downgrading slight gui modifications to 1.5.1 and removing architectury.
