### ISSUE TITLE
There was an error loading OptiFabric!

### ISSUE THREAD

**Issue by jaapjan13** [Chocohead/OptiFabric#117]
It seems OptiFabric dousn't see the 1.16.4-OptiFine_HD_U_G5.jar in the mods folder. 
![afbeelding](https://user-images.githubusercontent.com/75691812/101520295-913b9700-3984-11eb-85f4-ffb62d46dbba.png)

**Comment by jaapjan13** [comment]
![afbeelding](https://user-images.githubusercontent.com/75691812/101520492-deb80400-3984-11eb-9823-aaf1d6d50d9a.png)

**Comment by IMS212** [comment]
try opening the jar file, extracting it, and trying again, also please give a log

**Comment by jaapjan13** [comment]
Opening wich Jar file? The OptiFabric or the Optifine one. Also where do I find a log file to provide to you?

**Comment by IMS212** [comment]
optifine, you can find log in .minecraft\logs\latest.log

**Comment by 0xfeeddeadbeef** [comment]
That screenshot looks suspicious — OptiFine jar downloaded from [the official website](http://optifine.net/adloadx?f=OptiFine_1.16.4_HD_U_G5.jar) is named `OptiFine_1.16.4_HD_U_G5.jar`, not `1.16.4-OptiFine_HD_U_G5.jar`.

**Comment by IMS212** [comment]
oh yeah did not notice that; where did you get optifine?

**Comment by 0xfeeddeadbeef** [comment]
Also, official OptiFine jar is 5 MB in size; it is 17 MB on the screenshot. I bet it is a malware. Upload it [to VirusTotal to verify](https://www.virustotal.com/gui/).

**Comment by jaapjan13** [comment]
That is quite interesting, I did get it off of the original website... Here is a screenshot from the results of the website you posted: 
![afbeelding](https://user-images.githubusercontent.com/75691812/101541281-8a6f4d00-39a1-11eb-8bac-c635371f2bab.png)

**Comment by jaapjan13** [comment]
https://optifine.net/adloadx?f=OptiFine_1.16.4_HD_U_G5.jar&x=fb0d is where I got it from. 
![afbeelding](https://user-images.githubusercontent.com/75691812/101541636-05386800-39a2-11eb-85b5-068f663156b5.png) Is a preview of the pop-up my browser (Firefox) gives me when I want to download it. Not the syntax you seem to be used to with the file name.

**Comment by IMS212** [comment]
interesting, how did it get to the file name you're using? anyway download it from that site again and put that one in

**Comment by jaapjan13** [comment]
With you guys's help I found the root of the issue... When you re-use the Jar file that you've used to launch Optifine as a **version** instead of a mod it expands itself to 17 MB and it becomes unuseable to OptiFabric. Now that I've used a fresh version it works perfectly. Thanks for the assist
