### ISSUE TITLE
Fabric loom not importing package (discord and GitHub banned hence doing it here to hope it’s passed on)

### ISSUE THREAD

**Issue by Danjhop4** [Chocohead/OptiFabric#1178]
![](https://cdn.discordapp.com/attachments/1007343453669171353/1139913729010573392/error.png)
Sorry if it is off topic

**Comment by AuroraDoesCode** [comment]
Says you didn't set Java home, so install Java properly then try again. I can compile from source fine.

**Comment by Danjhop4** [comment]
That’s normal I don’t have admin so I modded gradle to use mcs java the error is a left over

**Comment by Danjhop4** [comment]
> Says you didn't set Java home, so install Java properly then try again. I can compile from source fine.

That’s normal I modded it to use mc java no admin

**Comment by Danjhop4** [comment]
https://github.com/Chocohead/OptiFabric/issues/1178#issuecomment-1676090138
copyed the file from a old project it worked odd
