### ISSUE TITLE
it wont open the installer

### ISSUE THREAD

**Issue by soniikui** [Chocohead/OptiFabric#12]
i cant open it idk why : (

**Comment by IMS212** [comment]
this isn’t an installer, it’s an mod for fabric. If you just want optifine get it from [here](https://optifine.net) and select mirror next to the version you want, then run that. If you still can’t open it, get java from https://java.com then try again.

**Comment by Chocohead** [comment]
As mentioned, OptiFabric is just a normal mod file which you put straight into the mods folder, no running it required. If you're having troubles installing Fabric there's a helpful set of pages on it [on the wiki](https://fabricmc.net/wiki/install).
