### ISSUE TITLE
Does not work with create

### ISSUE THREAD

**Issue by vtf6259** [Chocohead/OptiFabric#1210]
i am using a other mod called clockwork as a addon for Valkyrien Skies and clockwork needs create to work but there are big fps drops i was using fabric  and optifine is forge only so a came across optifabric so i tried it and i get 
![image](https://github.com/Chocohead/OptiFabric/assets/125233907/b7fa287b-2b8a-4434-aa3d-e3396848c065)

**Comment by Poopooracoocoo** [comment]
Also see
https://github.com/Fabricators-of-Create/Create/issues/616
https://github.com/Fabricators-of-Create/Create/issues/675
https://github.com/Fabricators-of-Create/Create/issues/882
https://fabricmc.net/wiki/optifine-alternatives

**Comment by sylv256** [comment]
https://lambdaurora.dev/optifine_alternatives/
