### ISSUE TITLE
Text is... it just isnt. 

### ISSUE THREAD

**Issue by MatyxCZ** [Chocohead/OptiFabric#1225]
![Snímek obrazovky 2023-09-16 220003](https://github.com/Chocohead/OptiFabric/assets/145228987/81acdbf1-717d-4cb7-88a1-687486d32acd)
anyone knows what to do

**Comment by XXMA16** [comment]
#1123

**Comment by rikosama** [comment]
same happening to me

**Comment by rikosama** [comment]
use Fabric API 0.85.0 (1.20.1)
works for me

**Comment by MatyxCZ** [comment]
Ok i am not sure that my fabric build Is outdated

**Comment by Telarmine2** [comment]
Read the first comment and make sure that your fabric is up to date @MatyxCZ
