### ISSUE TITLE
helpme

### ISSUE THREAD

**Issue by cayonnaise** [Chocohead/OptiFabric#1233]
![image_2023-10-03_231841770](https://github.com/Chocohead/OptiFabric/assets/146859506/0b8bed22-fc8b-40ba-8be1-35d4acf35077)

**Comment by Poopooracoocoo** [comment]
So what does your mods folder look like? And can you upload your latest.log?

---

I recommend switching to alternatives to OptiFine.
https://lambdaurora.dev/optifine_alternatives/
https://fabricmc.net/wiki/community:optifine_alternatives
https://github.com/TheUsefulLists/UsefulMods
https://fabulously-optimized.gitbook.io/modpack/readme/give-up-optifine
https://github.com/skywardmc/additive/wiki/Give-up-OptiFine

**Comment by cayonnaise** [comment]
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/5244d139-9c12-418c-914e-a96153440d17)

wdym latest.log?

**Comment by Poopooracoocoo** [comment]
You can find your latest.log in your logs folder.

You're missing OptiFine, just as the message said. Why did you need to create an issue to say this? OptiFabric does not replace OptiFine. It only tries to make it run on Fabric.

**Comment by cayonnaise** [comment]
i'm sry i dont understand 
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/cb6ef457-05a7-41be-bbe5-41b594ad9a31)
 and 
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/94f1b8be-773d-4a03-87d0-0d803e04df0c)

**Comment by Poopooracoocoo** [comment]
Let me repeat myself:
>You're missing OptiFine, just as the message said. Why did you need to create an issue to say this? OptiFabric does not replace OptiFine. It only tries to make it run on Fabric.

Read the description.
https://www.curseforge.com/minecraft/mc-mods/optifabric

Then download OptiFine and add it to your mods folder.
https://optifine.net/home

**Comment by cayonnaise** [comment]
THANK YOU SO MUCH

**Comment by cayonnaise** [comment]
a? 
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/0a08c1cb-10b0-41ee-b5d4-39b038b6dd1b)
this one is OptiFine Hd U I2

**Comment by cayonnaise** [comment]
theres three version 
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/40ea2b07-335d-48ca-aa75-fe7604bde471)
and when i try the second one, this is what i get
![image](https://github.com/Chocohead/OptiFabric/assets/146859506/f80e24c1-a4a6-4824-a92b-9b7ffbb7582b)
this one is OptiFine Hd U I1

**Comment by cayonnaise** [comment]
[crash-2023-10-06_19.21.57-client.txt](https://github.com/Chocohead/OptiFabric/files/12830434/crash-2023-10-06_19.21.57-client.txt)
and this is the crash report

**Comment by Poopooracoocoo** [comment]
OptiFine isn't going to be compatible with a lot of things. You should use alternatives to it for Fabric. I've linked to alternatives above. Personally I use the Fabulously Optimized modpack in Prism Launcher and then add mods to it.

**Comment by cayonnaise** [comment]
THANK YOU SO MUCH

**Comment by cayonnaise** [comment]
> OptiFine isn't going to be compatible with a lot of things. You should use alternatives to it for Fabric. I've linked to alternatives above. Personally I use the Fabulously Optimized modpack in Prism Launcher and then add mods to it.

now i am downloading the Fabulously Optimized modpack, wish me luck

**Comment by Poopooracoocoo** [comment]
Anyway, as this isn't a bug in OptiFabric, you can close this issue, @cayonnaise
