### ISSUE TITLE
Does not work with replay mod

### ISSUE THREAD

**Issue by vtf6259** [Chocohead/OptiFabric#1235]
when i launch minecraft with optifabric and replay mod i get exit code: 1

**Comment by Poopooracoocoo** [comment]
They're not compatible... Exit code 1 isn't very useful. A latest.log, which you can find in your logs folder, is more useful. I suggest uploading it here. But know that there are already many issues about Replay Mod's incompatibility with OptiFabric and OptiFine

---

I recommend switching to alternatives to OptiFine.
https://lambdaurora.dev/optifine_alternatives/
https://fabricmc.net/wiki/community:optifine_alternatives
https://github.com/TheUsefulLists/UsefulMods
https://fabulously-optimized.gitbook.io/modpack/readme/give-up-optifine
https://github.com/skywardmc/additive/wiki/Give-up-OptiFine
