### ISSUE TITLE
There was an error loading OptiFabric

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [Chocohead/OptiFabric#1243]
When I load my minecraft 1.20.1 then shows a error 
![Screenshot 2023-10-21 121406](https://github.com/Chocohead/OptiFabric/assets/109818645/87b7a055-3c82-4abd-b098-c7277d599670)

**Comment by rilakuma123** [comment]
Screenshot of your mods folder? Logs?

**Comment by SohamRoy20Gaming** [comment]
![Screenshot 2023-10-22 172356](https://github.com/Chocohead/OptiFabric/assets/109818645/1a186cb6-4d59-4bd5-9412-3efb239f04c6)

**Comment by Poopooracoocoo** [comment]
You're missing OptiFine just as the message tells you. OptiFabric just makes OptiFine compatible with Fabric. It doesn't include or replace it. You need to ad OptiFine to your mods folder.

**Comment by Poopooracoocoo** [comment]
Well now you've replaced OptiFine and OptiFabric with Sodium... It's not very relevant to this issue anymore.
