### ISSUE TITLE
REI rendering cells crash

### ISSUE THREAD

**Issue by superon** [Chocohead/OptiFabric#126]
i've been unable to reproduce this crash :/ it happened when i type "soo" in the search field
optifabric-1.8.13
OptiFine_1.16.4_HD_U_G5

https://pastebin.com/cg29tNeB

**Comment by Chocohead** [comment]
If you switch shaders on or off whilst in game you will get this crash from anything which needs Fabric's rendering API. There's not really a way to avoid it without impacting the game's performance effectively making constants not constant any more. It only happens from changing it then though so once the game has been restarted/crashed from switching it'll be fine again.
