### ISSUE TITLE
Optifabric Crash (+ Replay Mod, 1.20.1)

### ISSUE THREAD

**Issue by TrevBoy1** [Chocohead/OptiFabric#1265]
I tried to play Optifabric (loader 0.14.25) with Replay Mod (and Optifine, of course) on version 1.20.1, but the game crashes while loading with exit code 1. I think Optifine itself is the issue, since it appears to open fine without it.
Edit: Optifabric appears to actually be the problem.

**Comment by Jpdminecart** [comment]
You're not the only person that has encountered this problem at a point in time there was supposedly a temporarily fix to fix the problem however that temporary fix did not succeed when I tried to do it #1260 #1259

**Comment by hogrhogr213** [comment]
Uihhjjju

**Comment by TrevBoy1** [comment]
Update: I couldn't find any fix for this issue as of now.
I decided to switch to the Fabulously Optimised modpack (from a Reddit post). It looks like everything from Optifine is in Fabulously Optimised, and no issues have happened thus far. Hopefully this gets fixed soon.
