### ISSUE TITLE
Game crash upon launch

### ISSUE THREAD

**Issue by XEUIPR** [Chocohead/OptiFabric#1271]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of me.modmuss50.optifabric.mod.Text failed

version 1.19.2
3 mods; Optifabric(w/optifine) & worldedit

https://github.com/Chocohead/OptiFabric/assets/102369198/6e7cd708-fe40-4306-903a-4c6026f95729

**Comment by Poopooracoocoo** [comment]
OptiFabric's incompatibility with Fabric Loader 0.15.0 was already reported in #1261.

In the future please attach the crash report.
