### ISSUE TITLE
Shaders cause the game to crash (1.16.3)

### ISSUE THREAD

**Issue by MrMeowOfficial** [Chocohead/OptiFabric#129]
I was able to start up the game with shaders enabled once, but I turned them off and on again and they've crashed ever since, but only in some worlds for some reason. It could be that I'm overloading the game but I can include a crash report if that would help to identify the problem. I'm also running Litematica at the same time but I haven't used any of its exclusive features while using OptiFabric yet.

**Comment by Chocohead** [comment]
A crash report would be very helpful in working out what is wrong if you have any.

**Comment by MrMeowOfficial** [comment]
[hs_err_pid22376.log](https://github.com/Chocohead/OptiFabric/files/5785656/hs_err_pid22376.log)

**Comment by Chocohead** [comment]
`atio6axx.dll` is part of the AMD GPU driver, which is notorious for having strange OpenGL issues. Unfortunately there's not really a universal way of fixing/working around them either, and these issues can happen with OptiFine alone too (such as sp614x/optifine#4448), so the best I can suggest is seeing if there is any driver update or trying with a different shader pack.
