### ISSUE TITLE
Incompatible with mods utilizing the Fabric Rendering API

### ISSUE THREAD

**Issue by Jarfeh** [Chocohead/OptiFabric#132]
This issue had originally been active before modmuss55 stopped working on the original builds for this mod. I'm merely submitting it here so that it isn't "lost."

**Comment by Chocohead** [comment]
This has been resolved many months ago now. If there are any issues with a particular mod please do make issue reports for them so they can be fixed too.

**Comment by Jarfeh** [comment]
Alright, before I had created the issue, I could not find any mention of it being fixed. Thank you for your response 👍

**Comment by Chocohead** [comment]
I'd fixed it locally before the `llama` branch was even pushed here, so there was never a need to move the issue over; the commit was 47ef417 for reference.
