### ISSUE TITLE
So recently I have downloaded fabric but I have left it because of optifabric..

### ISSUE THREAD

**Issue by southallarcher** [Chocohead/OptiFabric#135]
Optifabric crashes my game when I add it to my mods folder. ofc I add it bcs I want to uyse optifine but does anyone know why it crashes my game when I add it to my mods folder? ty for reading.

**Comment by BotiBoster** [comment]
Because it doesn't work with the current fabric api, you have to downgrade it to 0.28.4 to use it

**Comment by southallarcher** [comment]
> Because it doesn't work with the current fabric api, you have to downgrade it to 0.28.4 to use it

thanks mate ill change it soon
