### ISSUE TITLE
Missing texture with CIT

### ISSUE THREAD

**Issue by xleb-normal** [Chocohead/OptiFabric#1366]
All textures that are modified using CIT display the model and texture that were not found, although this was not the case when using the OptiFabric v1.13.25 version

OptiFabric versions: v1.14.3
OptiFine versions: OptiFine HD U I6
Minecraft versions: 1.20.1

**Comment by Chocohead** [comment]
Could you attach/link the texture pack you're using?

**Comment by xleb-normal** [comment]
> Could you attach/link the texture pack you're using?

I used my test resource pack, but I also checked with other resource packs that use the CIT system and with all of them this bug happens, although with version v1.13.25 everything was fine

link https://www.planetminecraft.com/texture-pack/what-painting-i-m-looking-at/
https://www.planetminecraft.com/texture-pack/ksepsp-v8-0/
https://modrinth.com/resourcepack/msh-totems
