### ISSUE TITLE
Optifine 1.16.4 G6 pre9, pre10 incompatible with FabricAPI 0.28.4

### ISSUE THREAD

**Issue by satwik9aari** [Chocohead/OptiFabric#139]
The game crashes on loading a world with just FabricAPI 0.28.4 in the mods folder along with OptiFabric & Optifine G6 pre9 or pre10. Optifine versions upto G6 pre8 work fine with the same FabricAPI version. Also, the crash doesn't occur when there's no FabricAPI. I believe this is not the same issue as the other reports which are due to using FabricAPI 0.29.x and any version of Optifine.

[crash-2021-01-06_15.03.49-client.txt](https://github.com/Chocohead/OptiFabric/files/5775020/crash-2021-01-06_15.03.49-client.txt)

**Comment by SnooComics9452** [comment]
double #137 #133 #130

**Comment by satwik9aari** [comment]
> I believe this is not the same issue as the other reports which are due to using FabricAPI 0.29.x and any version of Optifine.

As mentioned already, those issues are different. The game doesn't even open when using FabricAPI 0.29.x regardless of the Optifine version used. This is the issue in those 3  reports.
My issue is with using **pre9** or **pre10** with FabricAPI **0.28.x** (which works fine with previous preview versions). The game opens fine in this case but crashes when loading a world.
