### ISSUE TITLE
1.20.4 Not Compatible with releases of Entity Model Features

### ISSUE THREAD

**Issue by VelvetRose252** [Chocohead/OptiFabric#1394]
Hi I'm trying to fix my CITs not appearing in my 1.20.4 game. I tried installing all different 1.20.4 releases of Entity Model Features with the 1.20.4 Optifabric one at a time but Fabric keeps giving me the same error message over and over. What version of Entity Model would be compatible to Optifabric  1.14.3 or what Optifabric version would work with EMF?

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Entity Model Features' (entity_model_features) 1.2 with any version that is compatible with:
		 - optifabric 1.14.3
More details:
	 - Mod 'Entity Model Features' (entity_model_features) 1.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.14.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Poopooracoocoo** [comment]
Why would you want EMF in the first place when it just implements OptiFine's custom entity models??

**Comment by VelvetRose252** [comment]
Hi, some of my CIT packs (IE Mizuno 16 CIT pack) weren't appearing in my 1.20.4 game while playing on Optifine. I tried installing CIT resewn in hopes that it would fix the pathing of the packs but it hardly fixed. A friend of mine suggested installing EMF and EFT and that's where I ran into the problem. I just talked with the dev for EMF and learned EMF was not made for Optifabric and Optifine and that I should look into Fabulously Optimized and Prism Launcher. Would you recommend this route too? And what do you think is the easiest way to go about it?

**Comment by VelvetRose252** [comment]
1.20.1+ has been a headache for me for awhile because of the changed pathing but my friends keep insisting on playing the latest version of Minecraft and they're new to playing with CITs. So I like a solution that's simple enough for them top follow too

**Comment by Poopooracoocoo** [comment]
> I just talked with the dev for EMF and learned EMF was not made for Optifabric and Optifine

Well of course. EMF's purpose is to implement OptiFine's custom entity models format. It would be redundant even if it did work with OptiFine. 

>some of my CIT packs (IE Mizuno 16 CIT pack weren't appearing in my 1.20.4 game while playing on Optifine.

CITs not working is a bug in OptiFabric according to #1366, which I can reproduce.


>  I tried installing CIT resewn in hopes that it would fix the pathing of the packs but it hardly fixed.

To be clear, CIT Resewn is not available for 1.20.4 yet. It's not included in any modpacks as older versions won't work. There is, however, a fork that works great: https://github.com/SHsuperCM/CITResewn/pull/353#issuecomment-1869378843

I've tested [Mizuno's 16 Craft CIT Pack](https://mizunomcmemo.blogspot.com/p/mizunos-16-craft-cit.html) and it works great. I was not using OptiFabric and OptiFine as that would be redundant and unsupported by CIT Resewn, as stated in its most description. 

>Fabulously Optimized and Prism Launcher. Would you recommend this route too? And what do you think is the easiest way to go about it?

Yes. A pack like Fabulously Optimized and a launcher like Prism are the best way to go about it. You may prefer to install mods yourself, or to use a different pack like Additive (which has an installer for Minecraft Launcher), or to use a different launcher like the Modrinth App. 

Do keep in mind that there are some quirks with Sodium such as it's lack of support for core shaders and lack of translucency sorting. And that there is no custom colours mod that has full parity with OptiFine on newer versions of Minecraft. Vanadium is quite close though.

>1.20.1+ has been a headache for me for awhile because of the changed pathing 

Are you referring to how 1.20.2 split up sprite sheets (for GUI)? Mojang's Slicer tool is great for converting old resource packs to the new format. 

Or perhaps you're referring to how CIT Resewn has an option to allow broken paths in resourcepacks? Mizuno's 16 Craft CIT is fine though.

**Comment by VelvetRose252** [comment]
Hi thank you for replying so quickly. I was initially playing Mizuno16 CIT pack with just Optifine, no fabric or optifabric, and they didn’t appear. That’s when I started adding CIT Resewn, didn’t work, added Fabric, nope didn’t work, and I added Optifabric, also didn’t work. So I’m feeling stumped. I have installed Sodium + Iris with shaders for a previous version and my CITs appeared fine but I didn’t like how it wasn’t improving my performance and it wasn’t a simple process to install. I’m wondering what is your setup to have your Mizuno 16 CIT to work perfectly and compatible with shaders?

**Comment by Poopooracoocoo** [comment]
Here are the setups with Mizuno's 16 Craft CIT Pack that I found worked:
- OptiFine 1.20.1 
- OptiFine 1.20.4
- CIT Resewn 1.20.1
- CIT Resewn Fork 1.20.4

>I have installed Sodium + Iris with shaders for a previous version and my CITs appeared fine but I didn’t like how it wasn’t improving my performance and it wasn’t a simple process to install.

I'd focus on getting that working better. The Sodium and Iris Discord servers can investigate why you're not seeing a performance improvement.

Also sorry Chocohead. I really deviated from OptiFabric issues.

**Comment by VelvetRose252** [comment]
Hi that is very helpful. I tried CIT Resewn and fabric and the CIT worked like a charm. It's weird to hear that you can see the Mizuno CIT on Optifine in 1.20.4 but I can’t,  I’m probably just unlucky.  I think this will be the solution for my friends. As for me I will experiment with Fabulously Optimized and seek assistance improving Sodium and Iris. It’s refreshing to know there are newer alternatives to Optifine and hopefully simple to install as Optifine. Thank you for your help, we can close this ticket!
