### ISSUE TITLE
1.20.1 Game Doesnt Launch w/ Optifabric & optifine

### ISSUE THREAD

**Issue by TestSubject1221** [Chocohead/OptiFabric#1395]
game doesnt load if i put this 2 mods. but if i remove it the game load
[crashreport.txt](https://github.com/Chocohead/OptiFabric/files/14074755/crashreport.txt)

**Comment by Poopooracoocoo** [comment]
This was fixed in OptiFabric 1.14.3.

**Comment by TestSubject1221** [comment]
> This was fixed in OptiFabric 1.14.3.

ill try. thanks
