### ISSUE TITLE
Fabric Optifine/optifabric Not working 1.16.4

### ISSUE THREAD

**Issue by OfficialRedDot** [Chocohead/OptiFabric#140]
Hello,
As said in the title my game does not run optifine on fabric. It only runs without optifine. If I start without the optifine but with the optifabric it says that it hasn't found optifine. But when I import optifine it does not work. The log is down below. 
Thanks for helping!
[New Paste 1.txt](https://github.com/Chocohead/OptiFabric/files/5783202/New.Paste.1.txt)

**Comment by Chocohead** [comment]
Fixed by 9f4a6fd
