### ISSUE TITLE
Incompatible with Fabric API (1.16.4)

### ISSUE THREAD

**Issue by MrMeowOfficial** [Chocohead/OptiFabric#141]
The game instantly crashes everytime I try to use OptiFabric and Fabric API at the same time, and it doesn't give an option for a crash report so unfortunately I can't help out with that. It seems to work fine in 1.16.3 however so I'm not sure which mod is causing the issue.

**Comment by aflacc** [comment]
I'm having this same issue

**Comment by Chocohead** [comment]
This should have (most likely) been fixed by 9f4a6fd, try updating to [1.8.16](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3161917).
