### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TosinV1** [Chocohead/OptiFabric#1433]

**Comment by TosinV1** [comment]
Hello?????

**Comment by Dracconis** [comment]
Try using Fabric Loader 0.14.25.

**Comment by TosinV1** [comment]
i already done that

**Comment by Dracconis** [comment]
Which version of the Fabric API are you using?

**Comment by TosinV1** [comment]
0.77

**Comment by TosinV1** [comment]
problem is, im using the exact same version i had before, i reinstalled mc and now its having all sort of problems

**Comment by Dracconis** [comment]
So using Fabric Launcher 0.14.25, Fabric API 0.77, Optifabric 1.13.16, Optifine HD U H9?

**Comment by TosinV1** [comment]
yes, ive tried that combo

**Comment by Dracconis** [comment]
Hmmm, then you will have to wait for someone else more knowledgeable than I. Im sorry I wasnt able to help.

**Comment by Poopooracoocoo** [comment]
You didn't install Fabric Loader 0.14.25 correctly. Otherwise you would not see this error. 

You'll need to use Fabric API 0.76.

**Comment by TosinV1** [comment]
There we go, now it works

**Comment by TosinV1** [comment]
thanks

**Comment by TosinV1** [comment]
it crashes the game. Exit code 1

**Comment by Poopooracoocoo** [comment]
Crash reports are in your crash-reports folder. If one was not generated, then share the latest.log file in your logs folder.
