### ISSUE TITLE
Crash with ver 1.8.16 and optifine HD U G5

### ISSUE THREAD

**Issue by cerovest** [Chocohead/OptiFabric#145]
if i don't put Optifabric and optifine in my mod folder i don't have any issues. the game crash during launch.
full logs: https://pastebin.com/ma0kxFB4
my mod list: https://puu.sh/H5zC6/e8334d2c02.png

**Comment by THBTX** [comment]
optifabric-1.8.16.jar and OptiFine_1.16.4_HD_U_G5 causing crash with intermediary-fabric-loader-0.10.8-1.16.4

**Comment by cerovest** [comment]
is it a note for you or it's for me to change something ? i'm not used to fabric so i have no idea

**Comment by THBTX** [comment]
Just a note for the dev letting them know it's happened to me as well.

**Comment by cerovest** [comment]
Update: i've tried with every of my mods, and the crash happen with light overlay 5.6.1 and/or architectury 1.2.73 (so i'll open a cleaner report)
