### ISSUE TITLE
Don't work 1.20.1

### ISSUE THREAD

**Issue by KIRUYXAN** [Chocohead/OptiFabric#1454]
When I run minecraft  fabric 1.20.1 with opptifabric, it just give an error of 1, but everything works without optifabric

**Comment by Dracconis** [comment]
Make sure you are using fabric-api-0.85.0+1.20.1, optifabric-1.13.25 (or OptiFabric-v1.14.3), preview_OptiFine_1.20.1_HD_U_I6.

**Comment by Poopooracoocoo** [comment]
Crash reports can be found in your crash-reports folder. If one wasn't generated, there's a latest.log in your logs folder.
