### ISSUE TITLE
Crashing with AOF3 2.5.7

### ISSUE THREAD

**Issue by irunatbullets** [Chocohead/OptiFabric#146]
A user has reporting a crash when trying to load worlds after installing optifine/optifabric with AOF3.

https://pastebin.com/f91ES244

It's possible to get the pack running by removing JMX and downgrading ignis-fatuus to 1.1.0 which jijs earlier versions of both JMX and Frex.

I've checked in with the JMX devs and have been asked to log an issue here.

If you think the issue belongs somewhere else please let me know.

**Comment by ronalddtang** [comment]
Have tried removing JMX and downgrading ignis fatuus with no luck still.

**Comment by irunatbullets** [comment]
@ronalddtang I think you'll also need to disable lithium, however there is a compatible version available on the aof discord. Also there are a few extra steps required for running optifine on 2.5.9.
