### ISSUE TITLE
conflict with optifine

### ISSUE THREAD

**Issue by chocoman15** [Chocohead/OptiFabric#147]
i installed the newest version of light overlay and downloaded architechury and its conflicting with optifine?  log here:   https://dpaste.org/hqj4

**Comment by shedaniel** [comment]
> Have a feeling it won't be the last time

It surely isn't, and won't be :)

**Comment by Chocohead** [comment]
If you don't want to keep the fix on your side @shedaniel I can move it here, otherwise I've marked out the versions OptiFabric breaks so people are aware they've got to either update (or backdate).
