### ISSUE TITLE
Problem in Sandwichable Compat Module with Sandwichable versions 1.2 +

### ISSUE THREAD

**Issue by FoundationGames** [Chocohead/OptiFabric#149]
I renamed a method in 1.2 and it seems to have broken everything. Oops. See the issue on Sandwichable repository. FoundationGames/Sandwichable#71

**Comment by Chocohead** [comment]
Not to worry, it is what it is for the way OptiFabric tries to correct other mod's Mixins. You're certainly not the first mod which has different handling depending on the present version to match Mixin names.
