### ISSUE TITLE
help with optifabric 1.17.1

### ISSUE THREAD

**Issue by MisterproPL** [Chocohead/OptiFabric#1496]
![image](https://github.com/Chocohead/OptiFabric/assets/161737576/7d2111fe-d275-4cea-bb21-5be9bdecde01)

**Comment by MisterproPL** [comment]
help
idk how to fix it

**Comment by Dracconis** [comment]
Try using Fabric Loader 0.14.25.

**Comment by MisterproPL** [comment]
thanks

**Comment by MisterproPL** [comment]
thanks it works
