### ISSUE TITLE
Custom water colors do not work with Fabric API

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#15]
Using Fabric API 0.19.0 build 398, OptiFabric-v1.4.1 and OptiFine 1.16.2 HD U G3 the custom water colormap that optifine offers does not work. When Fabric API is not installed the custom colors do work as intended. 

You can notice the issue with the resource packs [bedrock-biome-water](https://www.planetminecraft.com/texture-pack/bedrock-biome-water/) and [caelesti](https://www.curseforge.com/minecraft/texture-packs/caelesti)  for example. The file that is supposed to supply these colors is minecraft:optifine/colormap/water.png

I can post the logs (which look normal to me) and settings if you are unable to reproduce the issue.

**Comment by Chocohead** [comment]
This will be Indigo overriding the normal fluid rendering not taking OptiFine's changed fluid tinting into account. Hopefully should be quite simple to fix.
