### ISSUE TITLE
Certain textures sometimes have mismatched _n & _s textures

### ISSUE THREAD

**Issue by zombye** [Chocohead/OptiFabric#150]
In my testing I've only had it happen with the melon side texture and the [Vanilla Normals Renewed](https://github.com/Poudingue/Vanilla-Normals-Renewed) resource pack, where it is sometimes using the _n & _s textures for magma. Magma still uses the correct textures.
As far as I can tell, it seems to work correctly about 20% of the time, though it could be affecting some other texture.

Tested with:
* OptiFabric 1.8.16
* OptiFine 1.16.4 HD U G5
* [Vanilla Normals Renewed](https://github.com/Poudingue/Vanilla-Normals-Renewed) V0.9.9.9 & V1.0.0, both are affected
* Various shaderpacks, in case it only happens when shaderpacks configure OptiFine in specific ways. Affects all that I've tested.

I'm not sure if other resource packs are affected. I have not noticed it in any other resource packs I've tested so far, but it could just be affecting some other texture.

For testing I've made a simple shaderpack to display the _n & _s textures: [showTextures.zip](https://github.com/Chocohead/OptiFabric/files/5811147/showTextures.zip)
Screenshot of issue:
![2021-01-13_22 20 43](https://user-images.githubusercontent.com/9051920/104511839-9c21c100-55ed-11eb-9346-b1a4ba7594a7.png)
Screenshot of expected result:
![2021-01-13_22 20 52](https://user-images.githubusercontent.com/9051920/104511872-a774ec80-55ed-11eb-96f4-e367cae443c4.png)

**Comment by Chocohead** [comment]
Do you get this with OptiFine being used standalone too or is this just an OptiFabric thing?

**Comment by zombye** [comment]
I was unable to reproduce this issue in standalone OptiFine when I created this issue, but oddly enough when re-testing it today it seems to have started happeing with standalone OptiFine too.
It also seems to be happening around half the time today, both in standalone OptiFine & with OptiFabric.

Given the random nature of the issue I'm guessing I was just getting lucky when initially testing standalone OptiFine, and unlucky while testing with OptiFabric.
