### ISSUE TITLE
1.20.4 compatibility issue, idk if there is a discord so im asking here

### ISSUE THREAD

**Issue by Josh4minee** [Chocohead/OptiFabric#1541]
so im crashing when I have these mods on
just realised I havent tried with the mods off
il do a couple more tests and update you guys, and get the crash logs, forgot about those
here is what im trying to so tho, lmk if yall see any blatent incompatibilities
![image](https://github.com/Chocohead/OptiFabric/assets/165106905/6373b8af-d80a-451a-bf21-60eb048c0957)

**Comment by Dracconis** [comment]
With the exception of AmbientSounds, Appleskin, CreativeCore, Essential-fabric, fallingleaves, Gamma-Utils, and itemscroller I can say that the rest of the mods work just fine using Fabric Loader version 0.15.6. So as just a suggestion try using that loader version and while removing the above mentioned mods and see if the game will load into a world. If so then start adding 1 mod back at a time and retest each time until it crashes again. You should then find the mod that might be conflicting with another 1. Also, the error log will give us some insight as to what is going on when it crashes.

**Comment by Josh4minee** [comment]
yeye I just didnt get the chance to send all those sorry, did tests like you said this morning and realised that its essentials mod that is actually INCOMPATIBLE with optifabric, they didnt import support for it (they stated this on their website)
