### ISSUE TITLE
Incompatible with Sodium and Lithium

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [Chocohead/OptiFabric#158]

**Comment by IMS212** [comment]
There is a patched version of lithium going around that works with OptiFabric, however sodium will never be compatible as it changes the rendering engine so much.

**Comment by Ilan-Sperber** [comment]
Where is the patched version of Lithium?

**Comment by Titaniumtown** [comment]
Yea, where is this version of lithium? Would love to see it.

**Comment by ZuccySuccy** [comment]
pretty sure you can remove the `breaks optifabric` text in fabricmod.json in most lithium versions and it works. What I do

**Comment by Chocohead** [comment]
If you just remove the `breaks` line without any more changes you get #18 / #36, you also need a single fix within one of Lithium's Mixins: Chocohead/Lithium@877777f (or to turn off the feature in Lithium's config). As far as I'm aware the only patched forms are the ones from my fork (or possibly forks of that), every push is built in the actions tab just like OptiFabric.

Sodium on the other hand is simply never going to work as per #40.
