### ISSUE TITLE
Crashes When Running ReplayMod

### ISSUE THREAD

**Issue by TheVisionaryOne** [Chocohead/OptiFabric#161]
Crashes when running alongside Replay Mod on 1.16.4. I am using Jumploader, which is a mod that allows Fabric mods to run in a Forge launcher. Not sure if that's contributing to the problem, but Replay Mod seems to be the main mod that's complaining in the crash log.

Here's some mod versions:
OptiFabric (1.9.2)
Optifine (HD_U_G6)
Replay Mod (2.5.1)
Jumploader (2.1.2)
Fabric API (0.29.2)

I'm running Forge-35.1.4. Not sure if that's relevant.

Here's the log file:
[latest.log](https://github.com/Chocohead/OptiFabric/files/5969576/latest.log)

**Comment by Chocohead** [comment]
This is actually a conflict with RandomPatches with Replay Mod being the mod which happened to load the conflicting Mixin first. Shouldn't be too much of a problem to get it working though.

**Comment by Chocohead** [comment]
You just need to update RandomPatches, it seems they have already fixed this: TheRandomLabs/RandomPatches@5a33b20
