### ISSUE TITLE
Optifabric could not find the optifine jar in the mods folder but i have it in the mods folder

### ISSUE THREAD

**Issue by KamuiSW** [Chocohead/OptiFabric#162]

**Comment by SnooComics9452** [comment]
this happend when u use custom mods folder

**Comment by Chocohead** [comment]
Think it might be a good idea to log which mods folder it has looked in, it is a little vague if people aren't aware

**Comment by jr0dsgarage** [comment]
If you're using MultiMC, make sure the Optifine Jar is enabled in the Loader mods list.  I have seen this error message when I forget to turn Optifine "on" in MultiMC.
