### ISSUE TITLE
Incompatible with Tweakeroo's Free Camera, I can look player's head only

### ISSUE THREAD

**Issue by Sanluli36li** [Chocohead/OptiFabric#164]
![2021-02-15_13 43 18](https://user-images.githubusercontent.com/5201743/107927242-b1558b00-6fb1-11eb-954b-dfea70c03583.png)
![2021-02-15_13 43 25](https://user-images.githubusercontent.com/5201743/107927250-b31f4e80-6fb1-11eb-8684-e6dd09f27bdf.png)
This bug only appears when working with Optifine

**Comment by Chocohead** [comment]
Does this happen if you use Canvas or Sodium with Tweakeroo (instead of OptiFabric)? I feel like I've seen reports similar to this before...

**Comment by GuNanOvO** [comment]
![2021-02-18_02 13 02](https://user-images.githubusercontent.com/63027311/108248640-187c6680-718f-11eb-9add-cd1155bb8cbb.png)
![2021-02-18_02 12 37](https://user-images.githubusercontent.com/63027311/108248646-1a462a00-718f-11eb-8347-304ac4450e84.png)
It is normal when using Sodium.

**Comment by Sanluli36li** [comment]
> Does this happen if you use Canvas or Sodium with Tweakeroo (instead of OptiFabric)? I feel like I've seen reports similar to this before...

It seems to be caused by Optifine G6 
Sodium is working fine 
Canvas’s performance is worse, it can’t see any part of the player

**Comment by SunnySlopes** [comment]
i've met with the problem too!

**Comment by Chocohead** [comment]
Fixed with [Tweakeroo v0.10.0-dev.20210303.123654](https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files/3224921)
