### ISSUE TITLE
OptiFabric could not find the Optifine jar in the mods folder

### ISSUE THREAD

**Issue by BrooklynLake** [Chocohead/OptiFabric#165]
![캡처](https://user-images.githubusercontent.com/70588155/108387826-5346d300-7251-11eb-95b9-de1380bf35d7.PNG)

(I have optifabric mod!)
mod loader version : fabric 0.11.1

Mods:
fabric-api-0.30.3 + 1.16
optifabric 1.8.0

**Comment by BrooklynLake** [comment]
![캡처2](https://user-images.githubusercontent.com/70588155/108388615-2646f000-7252-11eb-9269-41758e5c3fe1.PNG)

**Comment by 0xfeeddeadbeef** [comment]
Error message is correct — there is no OptiFine jar in your Mods folder. [Download from the official web site](https://optifine.net/adloadx?f=OptiFine_1.16.5_HD_U_G6.jar).

Also, optifabric-1.8.0 is outdated. [Get the latest version 1.9.2](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3183995)
