### ISSUE TITLE
Incompatibility with oωo (owo-lib)

### ISSUE THREAD

**Issue by xleb-normal** [Chocohead/OptiFabric#1650]
For some reason oωo (owo-lib) is causing problems with Optifabric. The author of oωo apparently doesn't want to fix it on his side, so I created a report issue here

**Comment by Dracconis** [comment]
> For some reason oωo (owo-lib) is causing problems with Optifabric. The author of oωo apparently doesn't want to fix it on his side, so I created a report issue here

Well regardless of circumstances we would need the error log so that we can see what error you are getting and IF it can be fixed through normal means.

**Comment by xleb-normal** [comment]
> > For some reason oωo (owo-lib) is causing problems with Optifabric. The author of oωo apparently doesn't want to fix it on his side, so I created a report issue here
> 
> Well regardless of circumstances we would need the error log so that we can see what error you are getting and IF it can be fixed through normal means.

Minecraft launches, but as I understand it OptiFine first gives an error about not being able to load textures, and then just hangs on the loading screen :/
Mod list -
OptiFine_1.20.4_HD_U_I7
optifabric-1.14.3
owo-lib-0.12.6+1.20.3
fabric-api-0.97.1+1.20.4
fzmm-mc1.20.4-0.2.11

[latest.log](https://github.com/user-attachments/files/15525182/latest.log)

**Comment by Dracconis** [comment]
Considering that you are running this on a linux system have you tried running minecraft without the fzmm and owo mods? If so does it run as intended? Then have you tried running it again by only adding 1 of those 2 mods to see if it will still run?

**Comment by xleb-normal** [comment]
> Considering that you are running this on a linux system have you tried running minecraft without the fzmm and owo mods? If so does it run as intended? Then have you tried running it again by only adding 1 of those 2 mods to see if it will still run?

Yes, I am using Linux, I tried running minecraft without the owo-lib and fzmm mods, and minecraft worked fine without them. I tried separately running owo-lib without fzmm and the problem was the same, but as soon as I removed OptiFabric and OptiFine, minecraft started working fine.

**Comment by Dracconis** [comment]
All I can say then is you will need to wait and see if Choco comes on to see this issue and if they can fix it. Otherwise the owo Dev just seems to be lazy and doesn't want to at least put in the effort to see if they can fix it on their end. (This based on a ticket that was closed for similar issue last year)
