### ISSUE TITLE
I do all reading the other errors, i have optifine 1.16.5 HD U G8, fabricloader 0.14.25 optifabric 1.13.16 and nothing, the same error

### ISSUE THREAD

**Issue by sulii928** [Chocohead/OptiFabric#1651]
![image](https://github.com/Chocohead/OptiFabric/assets/171512382/a8ec98d1-3374-4b55-8488-3d6a1d6aca03)

**Comment by Dracconis** [comment]
Then you are not using the release fabric-loader- 0.14.25-1.16.5 Profile version when you are launching Minecraft, otherwise you would not be getting that error.

**Comment by sulii928** [comment]
i delete all fabric versions i have and then i installed the 0.14.25 and it doesn't work as well

**Comment by Dracconis** [comment]
With the versions of the mods you mentioned it will work just fine with no issue.

**Comment by sulii928** [comment]
i use a non official minecraft launcher so i dont know how to select the other version of fabric loader :c

**Comment by Dracconis** [comment]
> i use a non official minecraft launcher so i dont know how to select the other version of fabric loader :c

Google is your friend. A 5 second search gave me this to answer your question for Prism Launcher
https://prismlauncher.org/wiki/getting-started/download-mods/

**Comment by sulii928** [comment]
i found a solution 4 t launcher u wanna know it? Maybe it will help you help someone else.

**Comment by Dracconis** [comment]
I will take your word for it and I am glad that you found a solution to your issue. If this solves your issue then, please close this ticket.
