### ISSUE TITLE
Sodium doesn't work when I go into the world

### ISSUE THREAD

**Issue by ArmaN11123885** [Chocohead/OptiFabric#1658]
Sodium doesn't work when I go into the world. I tried everything. I looked at all the guides on how to fix this error. I downloaded sodium, threw it into a folder, then downloaded the sodium patch for Open4les. I did everything as it should, went in and I went into the game, chose a world and went in, but when the territory started loading, it froze, what’s the problem? 

Uploading HnVideoEditor_2024_06_07_125346435.mp4…
![Screenshot_20240607_123312](https://github.com/Chocohead/OptiFabric/assets/169547149/e4af3bf0-4f6b-4fe0-9719-890107234a10)
![Screenshot_20240607_123241](https://github.com/Chocohead/OptiFabric/assets/169547149/41159f34-18fa-41d3-b6c4-699e39a69469)

**Comment by Dracconis** [comment]
You do realize this is the Optifine Github and not the Sodium Github reporting tool right?

**Comment by ArmaN11123885** [comment]
I'm sure I'm sorry, I just got it wrong
