### ISSUE TITLE
1.16.5 Incompatible with Immersive portals

### ISSUE THREAD

**Issue by VinsiesPlayer** [Chocohead/OptiFabric#166]
I think that is the issue. I have 1.16.5 minecraft with fabric. Minecraft crashes and says that an unexpected error occurred. The exit code was 0. My mods folder has OptiFabric 1.9.2, OptiFine 1.16.5_HD_U_G7 & immersive portals in it. If you're wondering why i'm telling so many details it's because then you can tell if you find another way to fix this or the problem is'nt immersive portals. But for now on I will be continuing to use immersive portals without optifine.

**Comment by detective-wraith** [comment]
I have tried it with Immersive portals and it works for me. Are you sure you are using optifine G7?

**Comment by qouteall** [comment]
Fixed

**Comment by Chocohead** [comment]
You'll need to update Immersive Portals as it fixed it with qouteall/ImmersivePortalsMod@507bcfb
