### ISSUE TITLE
OptiFine HD U I9 pre1 was come out~

### ISSUE THREAD

**Issue by dsb987** [Chocohead/OptiFabric#1669]
OptiFine HD U I9 pre1 was come out, i'm already waiting optifine for so long time...

**Comment by dsb987** [comment]
omg!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
when i changed the fabric.mod.json in optifabric-1.14.3 to makes it supported 1.20.6, and deleted the fabric-renderer-indigo-0.100.0.jar in fabric-api, my optifine is actually working!
how sweet!~

**Comment by dsb987** [comment]
oh yeah, it also working with NotSoNew right now, with java1.8.0_51.

**Comment by Dracconis** [comment]
Then if you have solved your issue please close this ticket.

**Comment by Dracconis** [comment]
If the issue was resolved why did you reopen the ticket?
