### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Alex-gif-byte** [Chocohead/OptiFabric#1677]
не могу войти в игру когда установил optifabric только сним проблема

![2024-06-15_23-54-14](https://github.com/Chocohead/OptiFabric/assets/172924719/83ff4b89-038d-4536-bed2-4aaf137fe1be)
все моды и версия 1 16 5
![2024-06-15_23-56-35](https://github.com/Chocohead/OptiFabric/assets/172924719/7992bc60-7172-4d6e-bfa9-eb8fdaac6a83)

**Comment by Alex-gif-byte** [comment]
вот все моды
![Uploading 2024-06-15_23-56-35.png…]()

**Comment by Alex-gif-byte** [comment]
все моды и версия 1 16 5
![Uploading 2024-06-15_23-56-35.png…]()

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25 and update your Optifabric 1.10.2 to 1.13.16 also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.
