### ISSUE TITLE
optifabric không hoạt động trên minecraft 1.18.2

### ISSUE THREAD

**Issue by Nob2244** [Chocohead/OptiFabric#1694]
![Ảnh chụp màn hình 2024-06-23 215757](https://github.com/Chocohead/OptiFabric/assets/100352812/8b9b4bdc-91e8-48f9-8a7c-f109baf225ad)
Đây là mods tôi sử dụng và trình cài đặt Fabric ở phiên bản mới nhất
![Uploading Ảnh chụp màn hình 2024-06-23 215926.png…]()

**Comment by Nob2244** [comment]
tôi sử dụng Tlauncher, mong bạn giúp đỡ

**Comment by Dracconis** [comment]
Trước hết, đây là Github tiếng Anh. Tìm kiếm câu trả lời mất chưa đầy 5 giây trên Google. Sử dụng trang này ( https://tlauncher.org/en/how-install-fabric.html ) để cài đặt Fabric Loader 0.14.25, lần sau hãy tìm kiếm để xem vấn đề của bạn đã được giải quyết chưa. Nếu điều này giải quyết được vấn đề của bạn, vui lòng đóng ticket. [Google Translated]

**Comment by Nob2244** [comment]
Cảm ơn bạn!

**Comment by Dracconis** [comment]
Không có gì.

> Cảm ơn bạn!
