### ISSUE TITLE
optiforge problem "This version of optifine is not compatible with your current minecraft version optifine requires 1.15.2 you have 1.16.4"

### ISSUE THREAD

**Issue by SamOnFabric** [Chocohead/OptiFabric#170]
when i launch minecraft on 1.16.4 with optifabric 1.16.4 and optifine 1.16.4 in my mods folder it sais "This version of optifine is not compatible with your current minecraft version optifine requires 1.15.2 you have 1.16.4" and i don't understand (i meant optifabric btw, my 2 braincells got that mixed up)
![image](https://user-images.githubusercontent.com/79587317/109030514-2a489700-76c4-11eb-82ae-11c74659d15c.png)

**Comment by Chocohead** [comment]
I've improved the error screen with the newest OptiFabric version which should help you work out what you need to fix
