### ISSUE TITLE
error optifabric 1.17.1 tlauncher

### ISSUE THREAD

**Issue by Osopolar811** [Chocohead/OptiFabric#1706]
![343932657-90d140c7-4596-40e9-aef5-e1d9dc26375d](https://github.com/Chocohead/OptiFabric/assets/174066076/c013186f-bfe2-496b-9f2f-9aef6bc1ae09)

**Comment by Dracconis** [comment]
Follow these instructions to install fabric loader version 0.14.25. IF this solves your error please close the ticket.
