### ISSUE TITLE
1.16.5 incompatibilities

### ISSUE THREAD

**Issue by scampertt** [Chocohead/OptiFabric#172]
When used in my friend's custom pack inside GDLanucher, optifabric 1.9.2 is incomaptible with; 

lambdynamiclights-fabric-1.3.4+1.16
sodium-extra-0.2.0
sodium-fabric-mc1.16.3-0.1.0
lithium-fabric-mc1.16.5-0.6.4

And when these mods are removed it wount even launch.

**Comment by IMS212** [comment]
lambdynamiclights and sodium will never be compatible with optifine, (lambdynamiclights is a replacement for an optifine feature and sodium completely changes rendering), and iirc there is a lithium patch but it hasn’t been updated in a while.

**Comment by Chocohead** [comment]
As mentioned there is no need for LambDynamicLights if you've got OptiFine, Sodium will never work (see #40), and Lithium [can work](//github.com/Chocohead/Lithium/actions/workflows/gradle.yml) it just needs a little change.
