### ISSUE TITLE
Game won't load with Optifine

### ISSUE THREAD

**Issue by SHXRKIEgg** [Chocohead/OptiFabric#173]
My game just instantly crashes when pressing play with the "Exit Code: 0".
When adding Optifine 1.16.5 G6 or G7, it does the Crash but removing Optfine its able to load but of course Optifabric tells me I need Optifine. So i'm wondering why I cant play with Optifine?

[latest.log](https://github.com/Chocohead/OptiFabric/files/6053865/latest.log)
[crash-2021-02-27_16.25.34-client.txt](https://github.com/Chocohead/OptiFabric/files/6053867/crash-2021-02-27_16.25.34-client.txt)

**Comment by zxcdevlop** [comment]
i think you should use the preview version of optifine, it works for me (latest one is G8_pre1)

**Comment by SHXRKIEgg** [comment]
I tried that one but didn't work

**Comment by Chocohead** [comment]
Actually a pair of issues in the report, one major the other minor. Both should be fixed with the newest OptiFabric.
