### ISSUE TITLE
good evening, I'm faced with this problem and I can't solve it, please help me main 1.16.5 fabric

### ISSUE THREAD

**Issue by prizrakdyshi** [Chocohead/OptiFabric#1744]
![2024-07-13_22 42 27](https://github.com/user-attachments/assets/922ac54e-c7e6-4dff-9117-5b5c9b59ad79)

**Comment by prizrakdyshi** [comment]
mods
![2024-07-13_23-09-14](https://github.com/user-attachments/assets/d0b0b737-aa3e-4ab4-95e5-ed4e5bae210d)

**Comment by prizrakdyshi** [comment]
fabric loader 14.25

**Comment by prizrakdyshi** [comment]
launcher tlaucher

**Comment by Zoowgo** [comment]
i have the same problem im on 1.16.5 too

**Comment by Dracconis** [comment]
Update your Optifabric to 1.13.16. If this solves your issue then please close the ticket, otherwise please leave new error message.
