### ISSUE TITLE
Keep crashing - Architectury api - 1.21

### ISSUE THREAD

**Issue by puppet04** [Chocohead/OptiFabric#1756]
The architectury api keep crashing my game
[crash-2024-07-24_18.45.09-client.txt](https://github.com/user-attachments/files/16367792/crash-2024-07-24_18.45.09-client.txt)
[latest.log](https://github.com/user-attachments/files/16367793/latest.log)

**Comment by Dracconis** [comment]
"[18:44:33] [main/INFO]: OptiFine was NOT detected.
[18:44:33] [main/INFO]: OptiFabric was NOT detected."
Since you are using neither **_please close this ticket_** and report your error to Architectury Reporting.
This Error Reporting Ticket is for Optifabric and not Architectury.

**Comment by puppet04** [comment]
Oh sorry
