### ISSUE TITLE
Optifabric Causing Crash

### ISSUE THREAD

**Issue by StarshellSys** [Chocohead/OptiFabric#1766]
My fabric crashes with error code one every time I try and use optifabric. It does not crash if I turn optifabric off, can someone help me please?

**Comment by Dracconis** [comment]
Minecraft versions, launcher being used, mods AND their versions

**Comment by StarshellSys** [comment]
@Dracconis 
Version is 1.20.4, just the regular minecraft launcher 
architectury-11.1.17-fabric
Bookshelf-Fabric-1.20.4-23.1.9
chat_heads-0.12.9-fabric-1.20.3
chat-coords-0.4.2338
cloth-config-13.0.121-fabric
EnchantmentDescriptions-Fabric-1.20.4-20.0
fabric-api-0.97.1+1.20.4
instantgroup-fabric-1.20.4-1.6.0
Jade-1.20.4-fabric-13.3.1
itematica-fabric-1.20.4-0.17.3
malilib-fabric-1.20.4-0.18.3
minihud-fabric-1.20.4-0.30.2
modmenu-9.2.0
optifabric-1.14.3
OptiFine_1.20.4_HD_U_17(1)
placeholder-api-2.4.0-pre.1+1.20.4
replaymod 1.20.4 and 1.20.3-2.6.14
RoughlyEnoughltems-14.1.742-fabric
roughly-searchable-2.6.1+1.20.4
visuality-0.7.4+1.20.4
voicechat-fabric-1.20.4-2.5.19
Xaeros_Minimap_24.2.0_Fabric_1.20.4

**Comment by Dracconis** [comment]
Which Fabric Loader are you using?

**Comment by StarshellSys** [comment]
@Dracconis Fabric 0.15.11 downloaded from forge

**Comment by Dracconis** [comment]
You need to remove Architecury and the mod that depends on it as well as replay mod. They are not currently compatible with optifabric

**Comment by StarshellSys** [comment]
Alright thank you

**Comment by Dracconis** [comment]
> Alright thank you

You're welcome. If this solves your issue please close the ticket.
