### ISSUE TITLE
MInecraft crash

### ISSUE THREAD

**Issue by ma-tteo** [Chocohead/OptiFabric#1767]
**minecraft crashes 1-2 second after it loads the loading screen
mods i used:**
antighost-1.20-fabric0.83.0-1.1.5.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
architectury-9.2.14-fabric.jar
armorchroma-1.2.6.jar
BadOptimizations-2.1.4-1.20.1.jar
Chunky-1.3.146.jar
CleanF3-0.4.6.jar
cloth-config-11.1.118-fabric.jar
CullLessLeaves-1.3.0.jar
dashloader-5.0.0-beta.2+1.20.0.jar
entityculling-fabric-1.6.6-mc1.20.1.jar
exordium-fabric-1.2.1-mc1.20.1.jar
fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
fastquit-3.0.0+1.20+.jar
ferritecore-6.0.1-fabric.jar
feytweaks-1.20-1.2.7.jar
From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar
geckolib-fabric-1.20.1-4.4.7.jar
krypton-0.2.3.jar
Ksyxis-1.3.2.jar
language-reload-1.6.1+1.20.1.jar
lazy-language-loader-0.3.3.jar
lazydfu-0.1.3.jar
lunade-fastanim-1.6-1.20.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
modelfix-1.15-fabric.jar
modernfix-fabric-5.19.0+mc1.20.1.jar
modmenu-7.2.2.jar
mods.txt
noisium-fabric-2.0.3+mc1.20-1.20.1.jar
optifabric-1.14.3.jar
OptiFine_1.20.1_HD_U_I6.jar
rrls-4.0.6.1+mc1.20.1-fabric.jar
SmoothScrollingRefurbished+1.20-1.1.2.jar
starlight-1.1.2+fabric.dbc156f.jar
TheManFromTheFog-1.1.1+fabric.mc.1.20.1.jar
YetAnotherConfigLib-3.5.0+1.20.1-fabric.jar

**crash log:**
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-07-31 16:51:55
Description: Ticking screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.class_442) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1816)
	at net.minecraft.class_437.fabric_getBeforeTickEvent(class_437.java:1829)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:148)
	at net.minecraft.class_310.handler$bbo000$fabric-screen-api-v1$beforeScreenTick(class_310.java:8060)
	at net.minecraft.class_310.method_1572(class_310.java:1875)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_310.method_1574(class_310.java:1875)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1816)
	at net.minecraft.class_437.fabric_getBeforeTickEvent(class_437.java:1829)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:148)
	at net.minecraft.class_310.handler$bbo000$fabric-screen-api-v1$beforeScreenTick(class_310.java:8060)
	at net.minecraft.class_310.method_1572(class_310.java:1875)
	at net.minecraft.class_437.method_25412(class_437.java:409)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_310.method_1574(class_310.java:1875)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, file/From-The-Fog-1.20-v1.9.2-Data-Resource-Pack.zip.zip, file/MinecraftTen 1.1 for 1.20-1.20.1.zip, file/TransparentGUI-1.20.X-R1.zip, fabric
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 869012072 bytes (828 MiB) / 1224736768 bytes (1168 MiB) up to 4831838208 bytes (4608 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 10621.81
	Virtual memory used (MB): 7838.05
	Swap memory total (MB): 4608.00
	Swap memory used (MB): 239.38
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4608m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		antighost: AntiGhost 1.20-fabric0.83.0-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		armorchroma: Armor Chroma 1.2.6
		badoptimizations: BadOptimizations 2.1.4
		chunky: Chunky 1.3.146
		clean-debug: Clean F3 0.4.6
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		cull-less-leaves: Cull Less Leaves 1.3.0
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		entityculling: EntityCulling 1.6.6
		exordium: Exordium 1.2.1-mc1.20.1
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		faster_entity_animations: FastAnim 1.6
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.1
		feytweaks: FeyTweaks 1.20-1.2.7
			midnightlib: MidnightLib 1.4.1
		geckolib: GeckoLib 4 4.4.7
			com_eliotlash_mclib_mclib: mclib 20
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ksyxis: Ksyxis 1.3.2
		languagereload: Language Reload 1.6.1+1.20.1
		lazy-language-loader: lazy-language-loader 0.3.3
		lazydfu: LazyDFU 0.1.3
		man: The Man from the Fog 1.1.1
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.15
		modernfix: ModernFix 5.19.0+mc1.20.1
		modmenu: Mod Menu 7.2.2
		noisium: Noisium 2.0.3+mc1.20-1.20.1
		optifabric: OptiFabric 1.14.3
			mm: Manningham Mills 2.3
			optifabric-libs: OptiFabric Libraries 1.14.3
		rrls: Remove Reloading Screen 4.0.6.1+mc1.20.1-fabric
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.2
		starlight: Starlight 1.1.2+fabric.dbc156f
		watching: From The Fog 1.9.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.16.0-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 4000 GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'optifine'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/From-The-Fog-1.20-v1.9.2-Data-Resource-Pack.zip.zip, file/MinecraftTen 1.1 for 1.20-1.20.1.zip, file/TransparentGUI-1.20.X-R1.zip, fabric
	Current Language: it_IT
	CPU: 4x Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.20.1_HD_U_I6
	OptiFine Build: 20231221-120401
	Render Distance Chunks: 11
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 10.18.10.5161
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.20.1
	OptiFine jar version: OptiFine_1.20.1_HD_U_I6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/matteo/AppData/Roaming/.minecraft/.optifine/OptiFine_1.20.1_HD_U_I6/Optifine-mapped.jar
	OptiFabric error: <None>

**video:**
https://github.com/user-attachments/assets/6ccbaee0-addc-49c3-8a16-5ce129e624a3

**Comment by ma-tteo** [comment]
and i forgot to say the version, wich is 1.20.1, fabric loader 0.16.0 and i use sklauncher 3.2

**Comment by Dracconis** [comment]
Fabric API 0.85.0 and Fabric Loader 0.14.25

**Comment by ma-tteo** [comment]
> Fabric API 0.85.0 and Fabric Loader 0.14.25

![image](https://github.com/user-attachments/assets/22695193-deea-4cda-8fa8-6a699c837c8b)
some mods are incompatible

**Comment by Dracconis** [comment]
Ok after some testing Fabric API 0.92.2, Optifabric 1.14.3, Optifine HD U I6 are fine, but the Fabric Loader needs to be version 0.15.11. Dont use 0.16.0.

**Comment by ma-tteo** [comment]
still crashes

try using my mods (2 files becouse they are too big):

[mods.zip](https://github.com/user-attachments/files/16447089/mods.zip)
[mods1.zip](https://github.com/user-attachments/files/16447094/mods1.zip)

**Comment by Dracconis** [comment]
Get rid of Dashloader and it will work just fine. If this resolves your issue then please close this ticket.

**Comment by ma-tteo** [comment]
still crashes
try using my mod to recreate the crash
[mods.zip](https://github.com/user-attachments/files/16453850/mods.zip)
[mods1.zip](https://github.com/user-attachments/files/16453852/mods1.zip)

**Comment by ma-tteo** [comment]
crashes when i open a world

https://github.com/user-attachments/assets/76ee7f2f-7448-4672-ba5b-74b07698b31c

**Comment by Dracconis** [comment]
I just went through your mod list intensively this time only adding 1 mod at a time unless it called for a dependency using the Vanilla MC Launcher. You cant use dashloader or the Geckolib (And I tried every version from 4.4.2-4.4.7) & Man from the fog mods. You need to report the error you get with these mods installed to their respective developers. It will run fin IF you do not use these 3 mods though. So if this resolves your issue please close this ticket.

**Comment by ma-tteo** [comment]
thank you very much, it worked. I appreciate you

**Comment by Dracconis** [comment]
> thank you very much, it worked. I appreciate you

You're welcome. I am glad to have helped.
