### ISSUE TITLE
Whenever I try to play minecraft with optifabric and replaymod, I get this b.s. It wasn't always the case can someone please help me with this?

### ISSUE THREAD

**Issue by KaySizzle** [Chocohead/OptiFabric#1774]
![2024-08-06_17 26 21](https://github.com/user-attachments/assets/6aa99c49-8b2d-43e7-b71b-75606f764581)

**Comment by Dracconis** [comment]
Which MC Version?
Also use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by KaySizzle** [comment]
1.17.1

**Comment by KaySizzle** [comment]
thats the version that I play

**Comment by Dracconis** [comment]
For 1.17.1 you should be using the following versions of these mods:
Fabric Loader	0.14.25
Fabric API	0.46.1
Optifabric	1.13.16
Optifine		HD U H1
IF you are still getting that error afterwards then please remove Replay Mod and try again.

**Comment by KaySizzle** [comment]
Thank you very much I miss playing replay mod with optifine
