### ISSUE TITLE
Failed to load optifine

### ISSUE THREAD

**Issue by skfad** [Chocohead/OptiFabric#1779]
The mods I use are:
fabric-api-0.77.0+1.18.2 Optifine_1.18.2_HD_U_H9 replaymod-1.18.2-2.6.18
optifabric-1.13.4 I am using Fabric loader 0.14.25. I tried many times but unfortunately I could not find a solution. What should I do?

**Comment by Dracconis** [comment]
Which MC Launcher are you using?

**Comment by skfad** [comment]
I am using tlauncher

**Comment by Dracconis** [comment]
> I am using tlauncher

Support isn't provided for cracked launchers.
