### ISSUE TITLE
Chat Heads Broken Again

### ISSUE THREAD

**Issue by ag120ah** [Chocohead/OptiFabric#178]
So the latest Optifabric version (1.9.6) broke Chat Heads again.. That's all I really have to say. Prior to 1.9.6, it was functional (last I checked was 1.9.2). Hope this gets resolved and thanks.

**Comment by Chocohead** [comment]
I gave it a go with OptiFabric 1.9.6, OptiFine G8_pre1 and Chat Heads 0.2.2 for what looks like a normal (working) result:

![2021-03-04_22 02 19](https://user-images.githubusercontent.com/4021725/110059801-dccfc800-7d5c-11eb-8ae3-4da5f0893735.png)

If you've got any logs from it not working that would be helpful to diagnosing what it going wrong for you
