### ISSUE TITLE
failed to load optifabric , failed to load optifine PLEASE HELP i have been dying from past 5 days :<

### ISSUE THREAD

**Issue by prayag8236** [Chocohead/OptiFabric#1786]
![image_2024-08-14_110106290](https://github.com/user-attachments/assets/2c2fdac9-beb9-4155-b8a5-07067df86425)

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by prayag8236** [comment]
it didnt solved the issue

**Comment by Dracconis** [comment]
Make sure you are using the new play profile that is created by the Fabric Loader installer. That WILL fix your issue I assure you. IF however it creates a different error then please post the new error, otherwise kindly close this ticket when your issue has been resolved.

**Comment by LambdaLaboratories** [comment]
You're probably using the wrong versions for optifine and optifabric, you can find them here
https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3927107
https://optifine.net/adloadx?f=OptiFine_1.16.5_HD_U_G8.jar&x=3619

**Comment by prayag8236** [comment]
how can i close the ticket?

**Comment by Dracconis** [comment]
> how can i close the ticket?

Down at the bottom next tot he comment button is another button that will allow you to close the ticket.
