### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by Kaieylo** [Chocohead/OptiFabric#1795]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of me.modmuss50.optifabric.mod.Text failed

what is happening:
When i load up the Optifine and Optifabric it Crashes on load, I removed all the mods but it still crashed on load. I followed a video on how to install everything before hand. Im running on 1.20.1 Fabric and minecraft when I take the two mods out it works like clock work just need some help on what the problem could be? 

here is my mod load out 
![image_2024-08-18_212704188](https://github.com/user-attachments/assets/d1a1fff9-1816-4137-a625-ad1a756696ef)

**Comment by Dracconis** [comment]
1. Get rid of geckolib mod as it is incompatible with 1.20.1. 2. Get rid of the optifine preview mod as you already have a more updated version in the list. 3. Update your Optifabric to 1.14.3 If this solves your issue please close this ticket.

**Comment by Kaieylo** [comment]
> 1. Get rid of geckolib mod as it is incompatible with 1.20.1. 2. Get rid of the optifine preview mod as you already have a more updated version in the list. 3. Update your Optifabric to 1.14.3 If this solves your issue please close this ticket.

what if Geckolib is need for another mod to work ??? And when I tried it without that mod in it still does not load 

![image_2024-08-18_235903003](https://github.com/user-attachments/assets/9b75afbd-c60d-4711-b40a-508fcf6e4510)

**Comment by Dracconis** [comment]
> > 1. Get rid of geckolib mod as it is incompatible with 1.20.1. 2. Get rid of the optifine preview mod as you already have a more updated version in the list. 3. Update your Optifabric to 1.14.3 If this solves your issue please close this ticket.
> 
> what if Geckolib is need for another mod to work ??? And when I tried it without that mod in it still does not load
> 
> ![image_2024-08-18_235903003](https://private-user-images.githubusercontent.com/128951079/358984410-9b75afbd-c60d-4711-b40a-508fcf6e4510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTE0MjksIm5iZiI6MTcyNDA5MTEyOSwicGF0aCI6Ii8xMjg5NTEwNzkvMzU4OTg0NDEwLTliNzVhZmJkLWM2MGQtNDcxMS1iNDBhLTUwOGZjZjZlNDUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxODEyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjZhZjllYTZiMzc3MmYyMWNkZWMyNDUyMjFlMTU3YjYyMjUxY2Q4MzEzMmExNmEzMjM4MmYzZWFmMmIzYzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmqOJ-JbG93Wndubgw8AraoUXll9t3SsXvkNuRhzrX4)

Then remove all the mods that need Geckolib to work. Trust me I have already done an extensive test using Geckolib for another player and the results are the same no matter what the setup is. Geckolib just doesnt work.

**Comment by Kaieylo** [comment]
> > > 1. Get rid of geckolib mod as it is incompatible with 1.20.1. 2. Get rid of the optifine preview mod as you already have a more updated version in the list. 3. Update your Optifabric to 1.14.3 If this solves your issue please close this ticket.
> > 
> > 
> > what if Geckolib is need for another mod to work ??? And when I tried it without that mod in it still does not load
> > ![image_2024-08-18_235903003](https://private-user-images.githubusercontent.com/128951079/358984410-9b75afbd-c60d-4711-b40a-508fcf6e4510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTE0MjksIm5iZiI6MTcyNDA5MTEyOSwicGF0aCI6Ii8xMjg5NTEwNzkvMzU4OTg0NDEwLTliNzVhZmJkLWM2MGQtNDcxMS1iNDBhLTUwOGZjZjZlNDUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxODEyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjZhZjllYTZiMzc3MmYyMWNkZWMyNDUyMjFlMTU3YjYyMjUxY2Q4MzEzMmExNmEzMjM4MmYzZWFmMmIzYzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmqOJ-JbG93Wndubgw8AraoUXll9t3SsXvkNuRhzrX4)
> 
> Then remove all the mods that need Geckolib to work. Trust me I have already done an extensive test using Geckolib for another player and the results are the same no matter what the setup is. Geckolib just doesnt work.

I removed all the mods and put the optifaric  and Optifine in and it still crashed the game and wouldn't load as I stated in my first ticket as shown 

![image](https://github.com/user-attachments/assets/ddd4984b-0a9e-422d-92b8-d25db2688874)

I have already tried your suggestion as Opitfabic and opitfine alone still crashed minecraft I did all my troubleshooting before making my ticket  and it still crashed minecraft im willing listen if you have anyother suggestion on how i can fix it that will be awesome

**Comment by Dracconis** [comment]
2 things then. Which Fabric Loader are you using and which Fabric API?

**Comment by Kaieylo** [comment]
> 2 things then. Which Fabric Loader are you using and which Fabric API?

Im using these two for it did I download the wrong ones???
![image](https://github.com/user-attachments/assets/cc0434f9-ceeb-4e6c-bb0a-3a93fdd43935)

**Comment by Dracconis** [comment]
> > 2 things then. Which Fabric Loader are you using and which Fabric API?
> 
> Im using these two for it did I download the wrong ones??? ![image](https://private-user-images.githubusercontent.com/128951079/359220070-cc0434f9-ceeb-4e6c-bb0a-3a93fdd43935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTcyNjEsIm5iZiI6MTcyNDA5Njk2MSwicGF0aCI6Ii8xMjg5NTEwNzkvMzU5MjIwMDcwLWNjMDQzNGY5LWNlZWItNGU2Yy1iYjBhLTNhOTNmZGQ0MzkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxOTQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWYzYjM4YmFmNDZiODIwNjk1MWEwYzk3M2IzMGFjN2YyNzZkOGE1ZTBmNWJlNjA2YWExM2RlNGY3OGY5MWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VmhpC3qNCRU2uUB93vkDLwl0UZBPy_vxdWgpflGWyMY)

The Fabric API is correct, but the other is the Fabric Loader Installer. What I meant was before you click 'play', the profile you are using should tell you which Fabric Loader 'version' you are using to play MC. example "release fabric-loader-0.14.25-x.xx.x"

**Comment by Kaieylo** [comment]
![image](https://github.com/user-attachments/assets/aabb10d0-7231-4953-997a-a35788fb027e)
it running this one could that be the issues ????? if so How can I get 0.14.25-1.20.1

**Comment by Dracconis** [comment]
There is your problem then. Fabric Loader for 1.20.1 should be 0.15.11 so it should look like release fabric-loader-0.15.11-1.20.1. Just use the installer again but this time choose the 0.15.11 for 1.20.1 and install it

**Comment by Kaieylo** [comment]
okay let give it a try then and see if that fixes it

**Comment by Dracconis** [comment]
Ok. Just so you know IF you are using these versions of the mods it should launch just fine:
Fabric Loader		0.15.11
Fabric API		0.92.2
Optifabric		1.14.3
Optifine			HD U I6

**Comment by Kaieylo** [comment]
It Crashed again hmmmmm im using the right one for it

![image](https://github.com/user-attachments/assets/4761931b-8434-40a2-a8ad-7b388b5ee3d8)

![image](https://github.com/user-attachments/assets/2c9dbe88-7069-4acb-aa25-e58c23e0c360)

update: They work for them selves I think another mod is doing it so thank you

**Comment by Dracconis** [comment]
Ok IF you are only using the 4 I mentioned and it works, then just add in 1 mod and any dependency that it needs to work and try again. You will eventually run into which mod is causing it to know why you are crashing

**Comment by Kaieylo** [comment]
okay

**Comment by Kaieylo** [comment]
Thank you I found at least  7 mod that are crashing 

![image](https://github.com/user-attachments/assets/865d82f3-fd64-4f82-a964-b0d8ee19e95c)

**Comment by Dracconis** [comment]
You're welcome, and I am glad that you found the culprits and everything is working.

**Comment by Kaieylo** [comment]
> You're welcome, and I am glad that you found the culprits and everything is working.

I mean yeah but i need those mod and it not working for those im happy the issues been fix but a new one not an option for me

**Comment by Dracconis** [comment]
> > You're welcome, and I am glad that you found the culprits and everything is working.
> 
> I mean yeah but i need those mod and it not working for those im happy the issues been fix but a new one not an option for me

Give me a minute to DL all the mods you are using so I can see IF there is a solution to your other issue.

**Comment by Kaieylo** [comment]
> > > You're welcome, and I am glad that you found the culprits and everything is working.
> > 
> > 
> > I mean yeah but i need those mod and it not working for those im happy the issues been fix but a new one not an option for me
> 
> Give me a minute to DL all the mods you are using so I can see IF there is a solution to your other issue.

Oh word thank you so much I need those for a server other wise i wont be able to join it

**Comment by Dracconis** [comment]
> > > > You're welcome, and I am glad that you found the culprits and everything is working.
> > > 
> > > 
> > > I mean yeah but i need those mod and it not working for those im happy the issues been fix but a new one not an option for me
> > 
> > 
> > Give me a minute to DL all the mods you are using so I can see IF there is a solution to your other issue.
> 
> Oh word thank you so much I need those for a server other wise i wont be able to join it

Yeah after extensively testing every mod combination as well as downgrading a bunch of the mods it seems that it genuinely might be a problem with Optifabric itself.

**Comment by Kaieylo** [comment]
Oh well then okay
