### ISSUE TITLE
Incompatibility Issue with Ugly Scoreboard Fix Mod

### ISSUE THREAD

**Issue by ag120ah** [Chocohead/OptiFabric#180]
The Ugly Scoreboard Fix Mod by Lortseam_ runs into rendering issues with the Optifabric mod. When configuring the scoreboard and saving options from Mod Menu, the scoreboard fails to render unless edited from config file in the config folder. I have already notified Lortseam_ and I thought I should also report this issue on here and hope this issue is resolved, thanks.

**Comment by Chocohead** [comment]
This has been fixed in 1.9.14, you'll probably have [to tell](https://gitlab.com/Lortseam/ugly-scoreboard-fix/-/issues/7) the Ugly Scoreboard Fix people though
