### ISSUE TITLE
[bug] JustMap

### ISSUE THREAD

**Issue by Romz24** [Chocohead/OptiFabric#181]
I am using JustMap mod for minimap and map. After I updated OptiFine to version G7, the minimap stopped displaying. If I go back to version G6, there is no such problem. It is worth noting that the HUD in the upper left corner is displayed, only the minimap is not visible. Can OptiFabric somehow fix this error?

![image](https://user-images.githubusercontent.com/2458113/110055540-312f7380-7d6e-11eb-842c-06daa0a50b36.png)

Minecraft: **1.16.5**
Just Map: [**1.2.16**](https://www.curseforge.com/minecraft/mc-mods/just-map/files/3102199)
OptiFabric: [**1.9.6**](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3223497)
OptiFine: [**HD U G7**](https://www.optifine.net/downloads)

I've already created this bug report [here](https://github.com/Bulldog83/JustMap/issues/97), but it looks like the mod has been abandoned since November.

**Comment by Chocohead** [comment]
If you go to your `config` folder, in the `justmap` folder, changing `"use_fast_render": "false"` to `"use_fast_render": "true"` in the `justmap.json` file it seems to fix this.
