### ISSUE TITLE
OptiFabric crash loop on startup.

### ISSUE THREAD

**Issue by StatusConnected** [Chocohead/OptiFabric#182]
OptiFabric starts a crash loop on startup, the reason I suspect that it is OptiFabric is that without it there aren't any crashes that seem to be related to it.

A Pastebin of the crash: https://pastebin.com/N9TzKUCS

**Comment by Chocohead** [comment]
Looks like a conflict with Custom Fog (Setadokalo/custom-fog#6), shouldn't be too hard to fix

**Comment by StatusConnected** [comment]
The crashes still happens when I remove custom-fog-1.4.0.jar from the mods folder. I have noticed that for a split second that instead of the title screen, it shows the options menu when loaded. This time it didn't produce a crash report though (By the way, I did check the crash-reports folder.)

**Comment by Chocohead** [comment]
Is there anything in the log file? Any mod which modifies the video settings screen might have issues with OptiFine replacing it

**Comment by StatusConnected** [comment]
I could not find any mod that modifies the video settings screen.

**Comment by Chocohead** [comment]
It was only an idea for which mod might be an issue. If there's no crash report or anything of note in the log files you've got to find the conflicting mod manually, so it can make the process quicker guessing more suspect mods to try removing first.

**Comment by StatusConnected** [comment]
Custom Fog does cause a crash but the crash loop comes from Hydrogen: https://modrinth.com/mod/hydrogen. After I found this out I found an issue on Hydrogens GitHub about being incompatible with Optifine: https://github.com/CaffeineMC/hydrogen-fabric/issues/20.

**Comment by StatusConnected** [comment]
test message
