### ISSUE TITLE
Optifine not load 1.15.2

### ISSUE THREAD

**Issue by Zack694** [Chocohead/OptiFabric#1828]
Idk how to fix it pls help me

**Comment by Dracconis** [comment]
Need the error message to know how to fix it.

**Comment by Zack694** [comment]
There ist it's just "Open help" and "Close Game"

**Comment by Dracconis** [comment]
Then provide a screenshot of THAT screen so we can see it

**Comment by Poopooracoocoo** [comment]
There's a fork that backports newer fixes to 1.15.2: https://www.curseforge.com/minecraft/mc-mods/optifabric-origins
