### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by BenProPlayz** [Chocohead/OptiFabric#185]
My game crashes when OptiFabric is installed on startup. Link to log: https://pastebin.com/hhsCdHVU

**Comment by KlaraChaos** [comment]
if your using mc version 1.16.5 then use optfine version OptiFine HD U G6 that version worked for me 
just got a wierd water glicth but im looking into that rn if i find a fix or if its just the shader im using

**Comment by Chocohead** [comment]
Looking through the mod list as the log doesn't really shed any light what it is crashing with, I'd try without Smooth Chunks: fl0gic/smooth-chunks#4

**Comment by BenProPlayz** [comment]
It was smooth chunks, what a shame I really liked that one. Thank you for the help! 😄

**Comment by Chocohead** [comment]
Smooth-Chunks will work with OptiFine's render regions off from 1.9.12
