### ISSUE TITLE
minecraft 1.16.5 will not load with optfine

### ISSUE THREAD

**Issue by MagmaVRC** [Chocohead/OptiFabric#187]
[crash-2021-02-28_23.25.22-client.txt](https://github.com/Chocohead/OptiFabric/files/6103821/crash-2021-02-28_23.25.22-client.txt)
[latest.log](https://github.com/Chocohead/OptiFabric/files/6103826/latest.log)
minecraft will not load with optfine with optfabric it crashes on run

**Comment by Chocohead** [comment]
The crash is from trying to use Canvas with OptiFine, they're both messing with the renderer so don't work together. The log file seems to be from another run (given the times are different to the crash) but isn't really conclusive of anything going wrong.
