### ISSUE TITLE
There was an error loading OptiFabric!

### ISSUE THREAD

**Issue by Zascar** [Chocohead/OptiFabric#1872]
OptiFabric could not find the Optifine jat in the mods folder:
![image](https://github.com/user-attachments/assets/ffcd1571-4630-4da0-a695-9418b1c14fef)
![image](https://github.com/user-attachments/assets/4750865a-4f97-425c-8bf6-35dc5b64b975)
![image](https://github.com/user-attachments/assets/837c491d-9758-445a-a898-11a8d7c9a001)

**Comment by Zascar** [comment]
Guys, don't make the same dumb mistake I did, DOWNLOAD OPTIFINE!!!!

**Comment by BioSurge** [comment]
I have OptiFine and it still gives me this error.
