### ISSUE TITLE
Connected textures don't work with 1.16.5

### ISSUE THREAD

**Issue by KayziiLOL** [Chocohead/OptiFabric#1896]
Hi, I recently wanted to use optifabric and I realized that there is an error and it is that the textures of the blocks are not connected, I tried to put it in "fast" and it did not work.

I also tried using a texture pack and it doesn't work either for some reason, please fix it if you can, thanks.

**Comment by KayziiLOL** [comment]
I forgot to mention that I'm using:

OptiFabric 1.13.16
OptiFine 1.16.5 HD U G8

**Comment by Dracconis** [comment]
Optifine does the connected textures not optifabric. Also you need a resource pack that has the connected texture files in it to begin with.

**Comment by KayziiLOL** [comment]
> Optifine crea las texturas conectadas, no OptiFabric. También necesitas un paquete de recursos que contenga los archivos de texturas conectadas para comenzar.

Yes, I know that optifine is the one that makes the connected textures and yes, the resource pack I use for some reason doesn't work when I use it with OptiFabric.

**Comment by KayziiLOL** [comment]
> Optifine does the connected textures not optifabric. Also you need a resource pack that has the connected texture files in it to begin with.

Yes, I know optifine is the one that makes the connected textures and yes, the resource pack I use for some reason doesn't work when I use it with OptiFabric.

**Comment by KayziiLOL** [comment]
Although for some reason when I use optifine HD U G7 the problem is solved, I don't know what caused the problem but for now everything is fine (I guess)

**Comment by Dracconis** [comment]
That is an Optifine versioning issue then. I am glad that you have it solved. You will need to take that issue up with the OptiFine devs. Please close this ticket.

**Comment by KayziiLOL** [comment]
> That is an Optifine versioning issue then. I am glad that you have it solved. You will need to take that issue up with the OptiFine devs. Please close this ticket.

Ok, thank u!.

**Comment by Dracconis** [comment]
> > That is an Optifine versioning issue then. I am glad that you have it solved. You will need to take that issue up with the OptiFine devs. Please close this ticket.
> 
> Ok, thank u!.

You are very welcome.
