### ISSUE TITLE
Crashes with aether reborn

### ISSUE THREAD

**Issue by Page3of9** [Chocohead/OptiFabric#199]
[crash-2021-04-03_01.09.11-client.txt](https://github.com/Chocohead/OptiFabric/files/6252145/crash-2021-04-03_01.09.11-client.txt)

**Comment by PiSkate** [comment]
Same here
[crash-2021-05-07_13.18.59-client.txt](https://github.com/Chocohead/OptiFabric/files/6443603/crash-2021-05-07_13.18.59-client.txt)
