### ISSUE TITLE
Compatibility with Sandwichable

### ISSUE THREAD

**Issue by thakyZ** [Chocohead/OptiFabric#20]
There is a bug, the game crashes when opening the inventory when this mod, OptiFine, and Sandwichable are installed

Fabric Loader: `0.9.2+build.206`
Fabric API: `1.19.0+build.398-1.16`
OptiFabric: `1.4.2`
OptiFine: `1.16.2_HD_U_G3`
Sandwichable: `1.1.2`

Log: [https://pastebin.com/pp0G7WtP](https://pastebin.com/pp0G7WtP)

**Comment by Chocohead** [comment]
So it does, will look into this tomorrow.

**Comment by thakyZ** [comment]
Ok sounds good
