### ISSUE TITLE
optifabric crashes in 1.16.5 and missing connected textures

### ISSUE THREAD

**Issue by XTUG25** [Chocohead/OptiFabric#205]
optifabric always crashes when i load it up on 1.16.5 and when im able to use it a while ago it doesnt even had connected textures pls. someone fix this

**Comment by A663S** [comment]
Same

**Comment by DuozLOL** [comment]
> optifabric always crashes when i load it up on 1.16.5 and when im able to use it a while ago it doesnt even had connected textures pls. someone fix this

you have the sodium in your modpack?

**Comment by XTUG25** [comment]
no i dont have

**Comment by sauced000** [comment]
i had the same problem until I switched to the optifine hd g7 version, not g6 or g8 for 1.16.5

**Comment by Chocohead** [comment]
If you're getting crashing I need the crash report from it (from the `crash-reports` folder). Issues with connected textures need to be checked against just OptiFine in case it's actually a resource pack/native OptiFine issue.
