### ISSUE TITLE
Lava colormap does not work

### ISSUE THREAD

**Issue by ShutUpFanta** [Chocohead/OptiFabric#206]
When using the Fabric api in my mods folder, the Colormap in the lava stops working, but if I remove the Fabric api, it works again, I already made sure that the texture pack is well programmed, but it still doesn't work

![2021-04-10_22 58 44](https://user-images.githubusercontent.com/70528642/114901250-3a364a80-9dda-11eb-8ada-30b9f12f4778.png)
![mods 10_04_2021 10_58_54 p  m](https://user-images.githubusercontent.com/70528642/114901298-47533980-9dda-11eb-8986-8684c898a6b5.png)
The folder called "Extraer" was temporary, since I was testing if there was any incompatibility with any mod(I'm from Mexico, that's why some files are in Spanish)

![2021-04-10_22 56 53](https://user-images.githubusercontent.com/70528642/114901558-871a2100-9dda-11eb-94b8-1a451e8f7ef8.png)
![mods 10_04_2021 10_57_43 p  m](https://user-images.githubusercontent.com/70528642/114901570-8aada800-9dda-11eb-838f-9fde2ec28668.png)

I already tried to reinstall all minecraft

**Comment by Chocohead** [comment]
You'll want to update OptiFabric, 1.1.0-beta2 is very, very old at this point so is missing many fixes
