### ISSUE TITLE
Recent issues with world rendering

### ISSUE THREAD

**Issue by pokegirl420** [Chocohead/OptiFabric#207]
Recently, since the latest update of Fabric API(i believe), my worlds have stopped loading to a certain point. All entities(zombies, sheep, etc) all freeze. Blocks no longer drop, y'all know the works. Upon closing the world. "Saving world..." indefinitely. I tried this alone with Fabric API and (obviously) Optifine, and it has the same issue. Switching to Sodium fixes this issue. Is anyone else having this same issue? Thanks.

**Comment by Chocohead** [comment]
Do you have any logs from when this happens? This is a classic sign the internal server has crashed
