### ISSUE TITLE
There is an error loading optifabric

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#210]
![Screenshot_20210421_154945](https://user-images.githubusercontent.com/79198391/115517471-bf799d80-a2b9-11eb-9f7c-52bfb57e9c9f.jpg)
I can't open it normally

**Comment by geckwwo** [comment]
pocket java launchers have some issues, so i reccomend you to not use poket launchers

**Comment by LeiZero** [comment]
You still need to download OptiFine, OptiFabric just makes OptiFine compatible for Fabric and is not included in the mod file so it means you need to download OptiFine separately.

**Comment by Chocohead** [comment]
There's extra handling added within OptiFabric 1.9.10 to try avoid cases where this arises. If you (or anyone else reading this) gets this again you can click the "Copy stack-trace" button and paste it in an issue here.
