### ISSUE TITLE
Lava colormap not working correctly

### ISSUE THREAD

**Issue by AlexTheDolphin0** [Chocohead/OptiFabric#215]
The colormap works, just the still lava color is incorrect. The flowing lava may be light blue, while still lava is a murky green.

**Comment by Chocohead** [comment]
This doesn't seem to be an issue with the newest OptiFabric version. If you're still getting this (and it doesn't happen with OptiFine on its own, occasionally it has bugs too) please do re-open and upload a link to the resource pack you're trying with and I can take a further look.
