### ISSUE TITLE
Laggy particles in Fabric 1.16.2 (OptiFabric1.4.3)

### ISSUE THREAD

**Issue by wdis01** [Chocohead/OptiFabric#22]
_[Google Translate/Bad English Alert]_

Some effects/mobs/break blocks/portals particles are laggy. I have been testing without fabric to see if it was an OptiFine bug but everything was lag free

**Comment by Chocohead** [comment]
Are you using Carpet Mod? It seems to have problems with particles and OptiFine

**Comment by Inksday** [comment]
I am not OP but I can confirm that I had this same issue and after disabling carpet the issue is gone.  I wonder why that happens.

**Comment by wdis01** [comment]
Effectively that problem is caused by carpet mod, I've removed it and everything is lag free with other mods
