### ISSUE TITLE
literally doesn't even work

### ISSUE THREAD

**Issue by invalidgdash** [Chocohead/OptiFabric#221]
crashes the game right after launching

**Comment by Chocohead** [comment]
Could you upload the crash report (in the `crash-reports` folder)? Or the log file (in `logs`)? Can't do anything without more of an idea what's gone wrong

**Comment by ghost** [comment]
> Could you upload the crash report (in the `crash-reports` folder)? Or the log file (in `logs`)? Can't do anything without more of an idea what's gone wrong

i have same problem, this is my latest.log https://hastebin.app/60b42e6c706e45001dfb024b

**Comment by ghost** [comment]
I found the problem, it somehow conflicts with the meteor client, deleted it and everything became fine

**Comment by Chocohead** [comment]
> 
> 
> I found the problem, it somehow conflicts with the meteor client, deleted it and everything became fine

There's already an issue for that: #203
