### ISSUE TITLE
So uh i have the same issue with the satin mod, here's a list of the current mods i have

### ISSUE THREAD

**Issue by Ameliaplayz** [Chocohead/OptiFabric#222]
Adorn
Artifacts
battle towers
better caves
better end
better mineshafts
better nether
better stronghold
extra origins
extra pieces
Fabric and other stuff like the language kotolin
fantasy craft
icarus
mermod
mod menu
optifine
origins and classes
origins plus
pehkui
trinkets
vanilla death chest
vanilla hammers
woodcutter

**Comment by lochnessdragon** [comment]
Hey, try and remove Origins Plus... I am working on a fix for this and will upload it soon.

**Comment by Ameliaplayz** [comment]
Ah thank you
