### ISSUE TITLE
Conflict with lamb dynamic lights

### ISSUE THREAD

**Issue by Facundo-Mourelle** [Chocohead/OptiFabric#223]
It appears when I'm starting the game. 

![image](https://user-images.githubusercontent.com/38925289/120055921-6cf57480-c00f-11eb-9443-c5e5078b6764.png)

**Comment by Ameliaplayz** [comment]
Even though i am not the creator, I know why it has a conflict, I think optifine has built-in dynamic lights, check the video settings to turn it on

**Comment by Chocohead** [comment]
OptiFine does indeed have its own dynamic lighting option, you're better turning that on and removing LambDynamicLights than trying to have both provide the same feature
