### ISSUE TITLE
Minecraft crashes with Carpet and Carpet-extra mods installed

### ISSUE THREAD

**Issue by 17wongam1** [Chocohead/OptiFabric#23]
Minecraft crashes upon launch when trying to load Optifabric with Carpet and Carpet Extra. The Exit Code is 0.

**Comment by Chocohead** [comment]
Make sure you're using the `_build2` version of Carpet if you're using 1.16.1 (see #4). Otherwise I'll need a crash report to work out what might be going wrong.
