### ISSUE TITLE
All of Fabric 3 - 1.16.5 v.2.8.2 Crashes with Optifabric v.1.10.2

### ISSUE THREAD

**Issue by adp-you** [Chocohead/OptiFabric#233]
Hi, I have downloaded the latest version of the All of Fabric modpack, and it crashes with the latest version of Fabric. This is the latest crash report:
[latest.log](https://github.com/Chocohead/OptiFabric/files/6603552/latest.log)

**Comment by Chocohead** [comment]
You'll want to use OptiFabric 1.11.1 and replace Lithium with [this one](https://github.com/Chocohead/OptiFabric/files/6618849/lithium-fabric-mc1.16.5-0.6.4-SNAPSHOT.zip) (extract the mod jar out of the zip)
