### ISSUE TITLE
Game just doesn't run

### ISSUE THREAD

**Issue by JuceInUse** [Chocohead/OptiFabric#234]
I open the game with Optifabric just fine but the second I open a world, for whatever reason I'm greeted to an entirely black screen. I can still interact and close out of the world, but I can't even see the escape screen until I'm back to the main menu. No clue why this is happening

**Comment by Chocohead** [comment]
Which mods are you using? This sounds similar to what Satin can do with shaders turned on but OptiFabric shouldn't let that happen any more.
