### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [Chocohead/OptiFabric#237]
Fresh install, apparently incompatible with 1.17?
![2021-06-08 21_14_06-Fabric Loader](https://user-images.githubusercontent.com/52252627/121243893-8a8fcd00-c89e-11eb-9ea3-9816adc7c500.png)

**Comment by Lovecrafts-Cat** [comment]
my bad, I am a dum dum

**Comment by epic0421** [comment]
Make sure your launcher is using Java 16 when trying to boot into your 1.17 instance.

**Comment by epic0421** [comment]
> 
> 
> Fresh install, apparently incompatible with 1.17?
> ![2021-06-08 21_14_06-Fabric Loader](https://user-images.githubusercontent.com/52252627/121243893-8a8fcd00-c89e-11eb-9ea3-9816adc7c500.png)

Make sure your launcher is using Java 16 when trying to boot into 1.17

**Comment by Big-Iron-Cheems** [comment]
> > Fresh install, apparently incompatible with 1.17?
> > ![2021-06-08 21_14_06-Fabric Loader](https://user-images.githubusercontent.com/52252627/121243893-8a8fcd00-c89e-11eb-9ea3-9816adc7c500.png)
> 
> Make sure your launcher is using Java 16 when trying to boot into 1.17

Already am, seems like the mod itself is not ready for 1.17

**Comment by Chocohead** [comment]
You need OptiFabric v1.11.1 or later to use 1.17, you'll be using something older than v1.11
