### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by maibigbutt** [Chocohead/OptiFabric#24]
I installed optifabric on 1.16.1 all of fabric modpack and it crashes plz fix it

**Comment by Chocohead** [comment]
I could do with a crash report, AoF is a big modpack so there's multiple possibilities what could be wrong.

**Comment by maibigbutt** [comment]
[latest.log](https://github.com/Chocohead/OptiFabric/files/5171126/latest.log)

will this do

**Comment by Chocohead** [comment]
Yes that's ideal, thank you.

**Comment by maibigbutt** [comment]
[Crash Report.txt](https://github.com/Chocohead/OptiFabric/files/5171213/Crash.Report.txt)
Just in case

**Comment by Chocohead** [comment]
Once v1.4.8 is on Curse please try with that and report back if there's still further troubles. Should fix Astromine at least, but no guarantees for any others which might be further into loading.

**Comment by maibigbutt** [comment]
Alright Thanks
