### ISSUE TITLE
1.17 Loading New Demension

### ISSUE THREAD

**Issue by AddictedPerson** [Chocohead/OptiFabric#242]
When i load into the nether from the overworld, or vice versa, only a 2 chunk radius loads, and i cant leave or load any more without closing and reloading the world, then the problem is fixed, until i go to the nether again. I was running a few of masa's mods, and they werent causing it, it resolved itself right after deleting optifabric.

**Comment by Chocohead** [comment]
This was an issue in earlier OptiFine previews: sp614x/optifine#5757
