### ISSUE TITLE
1.17 crashing

### ISSUE THREAD

**Issue by Vixen197** [Chocohead/OptiFabric#258]
When I have optifabric 1.17 and the latest optifine in the mods folder, the game wont launch. it crashes before i even see the loading screen. This may be a compatability issue since i have other mods, (Architectury, bits and chisels, carrier, cavebiomes, cloth config, croptopia, improved stations, inmis, mo's colors, riverredux, secretrooms, and transportables) But i dont think any of these would interfere with optifabric. All i get is an Exit code zero. I have been waiting for maybe a new release to come out but it hasnt yet.

**Comment by cerberi** [comment]
cloth config and architectury api

**Comment by Vixen197** [comment]
> cloth config and architectury api

Are you saying these arent compatibal with optifabric or...?

**Comment by cerberi** [comment]
Yeah, currently they are not compatible with optifabric. Hopefully they fix that soon

**Comment by Chocohead** [comment]
Duplicate of #238
