### ISSUE TITLE
Crash with Screenshot to Clipboard

### ISSUE THREAD

**Issue by comp500** [Chocohead/OptiFabric#26]
See crash log: https://paste.ee/p/mJ8I8 (versions: Minecraft 1.16.2, Fabric API 0.19.0+build.398-1.16, Optifabric 1.4.5, Optifine 1.16.2 HD U G3, Screenshot to Clipboard 1.0.6)

The change that seems to cause the crash is https://github.com/comp500/ScreenshotToClipboard/commit/c9f22805d1c1008ec93d40377cd5dc13573bb8fa, as Screenshot to Clipboard 1.0.5 works, however the error thrown should have been fixed by https://github.com/Chocohead/OptiFabric/commit/2d72826986ade38d32fd70d0201d8ba17e35d5ed (as you mentioned previously "OptiFabric on 1.15.2 won't account for Fabric API's new Mixin to MobEntity").

Installing Replay Mod 1.16.2-2.4.3 stops the crash from occurring, which suggests that this issue (mixin configurations not being applied because there is a mixin to the first class to be applied) was fixed by the workaround proposed in https://github.com/ReplayMod/ReplayMod/issues/327. I then tried adding the dummy prelaunch entrypoint on it's own to a Screenshot to Clipboard jar, and that also fixed the issue. It could be an issue with Fabric-ASM rather than Optifabric or Replay Mod?

**Comment by Chocohead** [comment]
I'd almost certainly say it's the exact same problem as Replay Mod, time to try the same fix.
