### ISSUE TITLE
Optifabric crashes apon entering the nether in 1.17

### ISSUE THREAD

**Issue by Thatengineerl** [Chocohead/OptiFabric#260]
so when i come into the nether on optifabric, after I move around in it for a bit it crashes for some reason, I can provide a crash report if you want it

**Comment by Chocohead** [comment]
The crash report will be very helpful if you have one. Make sure you're up to date on OptiFine preview versions though, there have been dimension related issues (e.g. sp614x/optifine#5757)

**Comment by Thatengineerl** [comment]
[latest.log](https://github.com/Chocohead/OptiFabric/files/6673182/latest.log)
heres the log

**Comment by Chocohead** [comment]
When you say crashes is the game actually closing or are you just getting GL errors spammed in the chat? That log doesn't have a crash of any kind at the end so just need to clear up whether it's just from another run or I'm interpreting your issue wrong

**Comment by Thatengineerl** [comment]
Im getting GL errors spammed, let me bring up another crash report

**Comment by Thatengineerl** [comment]
heres the full crash report of a run
https://mcpaste.io/7916eba479996f3a

**Comment by Chocohead** [comment]
The GL errors are apparently issues with NVidia drivers, there's some suggestions what to do here: sp614x/optifine5773

**Comment by Thatengineerl** [comment]
its sp614x/optifine#5773
