### ISSUE TITLE
Possible 1.11 Regression

### ISSUE THREAD

**Issue by greensad** [Chocohead/OptiFabric#264]
"There was an error loading OptiFabric!" 
stack-trace: https://pastebin.com/kZm80c7D

This doesn't appear to happen on 1.10.2.

**Comment by Chocohead** [comment]
It is an alpha for this reason. For reference was this running on 1.16 or 1.17?

**Comment by greensad** [comment]
1.16.5.

**Comment by Chocohead** [comment]
This should be fixed in v1.11.8
