### ISSUE TITLE
Runs but Shaders button is Greyed out

### ISSUE THREAD

**Issue by AlisterGontineac** [Chocohead/OptiFabric#266]
As the title implies. 
Is there another file I need other then Optifine and Optifabric ?

**Comment by Chocohead** [comment]
OptiFine hasn't finished porting shaders for 1.17 yet, as soon as it does you'll be able to use them

**Comment by AlisterGontineac** [comment]
*facepalm* Alright, well thanks for responding to my dumb question then XD
