### ISSUE TITLE
Chest render issues

### ISSUE THREAD

**Issue by unmoving-javi** [Chocohead/OptiFabric#267]
Chests render incorrectly in the inventory with this mod, not in the hotbar but specifically in the inventory. This may apply to other 3d blocks with multiple components but I couldn't find any other examples off the top of my head. This is using the 1.17 version of fabric with 1.17 versions of optifine.

**Comment by Chocohead** [comment]
Have you checked this doesn't happen with just OptiFine installed on its own? There's a chance this is just broken from OptiFine being a preview still
