### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by drawtaru** [Chocohead/OptiFabric#27]
Downloaded and installed the latest version of Optifine and OptiFabric (Fabric and Fabric API already installed).  Game says failed to launch, requires 1.15.2.
![crash2](https://user-images.githubusercontent.com/70715566/92144293-7e914f00-ede4-11ea-9c42-c59e0e79a0ee.jpg)

**Comment by Chocohead** [comment]
You want OptiFabric v1.4.5 as that is the one for 1.16.1/2, v1.0.1 is only for 1.15.2

The download button in the top right is often not the one you want on Curse by the way. It picks the latest in terms of upload rather than Minecraft version.
