### ISSUE TITLE
Crash with AdoptOpenJDK 16

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Chocohead/OptiFabric#270]
Whenever I try to open and close the inventory (or if VoxelMap is installed, try to hide the initial message), the game crashes without a crash report, but rather a dump:
https://femtopedia.de/hs_err_pid2432.log

The log doesn't show something interesting next to the errors with Sphax (since it isn't released to 1.17 yet):
https://femtopedia.de/2021-06-21-6.log

I strongly believe, this issue is related to OptiFabric as the client without it runs just fine (even with all my other mods installed).
As soon as I add OptiFabric, the crash happens.

**Comment by Chocohead** [comment]
Like #260 this is apparently an issue with some versions of the Nvidia drivers interacting with OptiFine: sp614x/optifine#5773. It doesn't seem to have an especially reliable pattern of reproduction/set of causes, just something that manages to get very unhappy

**Comment by ThexXTURBOXx** [comment]
Oh okay, sorry for bothering you then. Then I will wait until a proper fix is released on OptiFine's or Nvidia's side

**Comment by Chocohead** [comment]
It's no trouble, I'd rather people report things even if it's not necessarily OptiFabric than not report things that are
