### ISSUE TITLE
The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14.

### ISSUE THREAD

**Issue by Sokkacraft** [Chocohead/OptiFabric#273]
[latest.log](https://github.com/Chocohead/OptiFabric/files/6697265/latest.log)

I beleive there is compatibility issues with the New Java 16. I found this issue when trying to use Optifine with Replaymod.

**Comment by Chocohead** [comment]
It's an issue with Replaymod with OptiFine, although I didn't think it was (publicly) updated to 1.17 yet
