### ISSUE TITLE
Cant Even Start

### ISSUE THREAD

**Issue by thekryptonianmd** [Chocohead/OptiFabric#274]
game cant even start, crashes as soon as i press play.
my mods are as follows:

Adorn
Architectury
Backslot
Bedspreads
Better Ladders
Blockus
Carrier
Cavebiomes
Cleancut
Comforts
Croptopia
DiggusMaximus
DualRiders
Fabric API
Kotlin
VoxelMap
FallingTree
GreaterEye
ImmersivePortals
ImprovedStations
INMIS
Litematica
Malibib
Modmenu
MoreVillagers
MoStructures
RoughlyEnoughItems
SimpleBackpack
StaffOfBuilding
Stoneholm
Terra
Transportables
WilliamWythersOverhauledOverworld
Winged
WorldEdit
Wraith HarvestScythes
Wraith Waystones

Im not sure which one (or few) of these its incompatible with, i will test them one by one
![Crash-Github](https://user-images.githubusercontent.com/86356758/123092409-040dea80-d45d-11eb-8f21-72262fb101f8.png)
 and update this discussion, but if you know it would be better

**Comment by thekryptonianmd** [comment]
Staff of Building 1.3.0 -1.17 Doesn't work with it, at least for me. i see you have it in your list of compatible mods.
i also removed immersive portals, simple backpack and terra as i dont really use them much

**Comment by Chocohead** [comment]
Staff of Building will certainly have had problems, try with OptiFabric v1.11.17 (once it's up on Curse) and feel free to reopen if you're still having issues
