### ISSUE TITLE
Cant Click on Shaders

### ISSUE THREAD

**Issue by thekryptonianmd** [Chocohead/OptiFabric#275]
![2021-06-23_20 38 56](https://user-images.githubusercontent.com/86356758/123098108-60740880-d463-11eb-9d44-3f97c24863de.png)
shaders not clickable

**Comment by Chellyyyyy** [comment]
Not an Optifabric problem. Optifine 1.17 is in beta, therefore no shaders yet.

**Comment by thekryptonianmd** [comment]
ohhh, thanks, first time using mods and shaders and things, thanks
