### ISSUE TITLE
Issue with Xaeros Minimap

### ISSUE THREAD

**Issue by Mathead253** [Chocohead/OptiFabric#277]
When I use Optifine/Optifabric with Xaero's minimap on a server the skins are blurred. I do not know if this is a compatibility issue with Xaero's minimap or Optifine/Optifabric so I'll post this on both mods issue trackers. (Minecraft version 1.17)

What it looks like with both mods:
![2021-06-22_19 47 40](https://user-images.githubusercontent.com/83712695/123157265-4f61d200-d438-11eb-843d-b7e2045c482b.png)

What it looks like without Xaeros mods:
![2021-06-23_15 18 27](https://user-images.githubusercontent.com/83712695/123157281-54268600-d438-11eb-9c59-8862fdaa9903.png)

Xaero's minimap issue tracker: https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/437

**Comment by Chocohead** [comment]
This is apparently fixed in [v21.12.2](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/3365444) of Xaero's Minimap
