### ISSUE TITLE
Bootlooping With optifabric and first person model [1.17 only]

### ISSUE THREAD

**Issue by Blobanium** [Chocohead/OptiFabric#278]
so apparently when i try to start minecraft i get this bootloop with optifabric and first person model loaded..

anyways, heres the log. 
[latest.log](https://github.com/Chocohead/OptiFabric/files/6706121/latest.log)

and my mods
![Capture](https://user-images.githubusercontent.com/45613796/123200656-03c61d00-d466-11eb-87d4-1301aa2d0ae9.PNG)

tell me if you need anything else thanks!

**Comment by Chocohead** [comment]
This has been fixed in [First Person Mod v2.0.2](https://www.curseforge.com/minecraft/mc-mods/first-person-model/files/3374897)
