### ISSUE TITLE
Issue working with Litematica

### ISSUE THREAD

**Issue by WhiteKap** [Chocohead/OptiFabric#28]
I downloaded the latest version of optifabric, using it with the latest version of optifine, as well as the latest version of Litematica, and tried to load a schematic for a Witch Farm, and I got this weird artifacting-like effect, some of it with being warped versions of the blocks actually used in the design, and some being weird blocks, like lime wool and purpur pillars. Attached are some screenshots.
![2020-09-03_13 12 31](https://user-images.githubusercontent.com/70723751/92163067-f3b25380-ede7-11ea-821a-12abd299ff38.png)
![2020-09-03_13 12 38](https://user-images.githubusercontent.com/70723751/92163081-f90f9e00-ede7-11ea-94b0-60f043e463c5.png)

**Comment by Chocohead** [comment]
This is a long standing known problem, I'd suggest following #16 for keeping all developments (here at least) in one place.
