### ISSUE TITLE
will not open with origins (1.17)

### ISSUE THREAD

**Issue by lamp-posts** [Chocohead/OptiFabric#281]
when i try to open minecraft with this installed it doesn't open and says that it conflicts with origins, this doesn't happen in 1.16.5

**Comment by soupyfish** [comment]
same 
![image](https://user-images.githubusercontent.com/36567875/123516314-5d5f5f00-d693-11eb-92f9-73eba249fbeb.png)

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
same

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
fixed it use 1.0 origins

**Comment by Chocohead** [comment]
This is not something I have control over unfortunately. As far as I can tell the newer versions of OptiFabric should be fine with Origins, but it's Origins which explicitly doesn't allow it to try though: apace100/origins-fabric@84a8bb8016cdd682c19e77f8532760a959b9e1bf. Based on the issue report on Origin's repo (apace100/origins-fabric#338) it might change when OptiFine releases fully for 1.17

**Comment by Chocohead** [comment]
There might be a solution in the meantime if someone is feeling like testing it, try creating a [`fabric_loader_dependencies.json`](https://fabricmc.net/wiki/tutorial:dependency_overrides) file in the `config` folder with the following contents:
```json
{
	"version": 1,
	"overrides": {
		"origins": {
			"-breaks": {
				"optifabric": "It should work"
			}
		}
	}
}
```
So long as you're using at least Loader 0.11.1 this should allow you to try Origins versions which would otherwise conflict with OptiFabric.

**Comment by supertroopa** [comment]
I tried testing it.

"
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1
"
[crash-2021-07-13_03.05.16-client.txt](https://github.com/Chocohead/OptiFabric/files/6806995/crash-2021-07-13_03.05.16-client.txt)

**Comment by supertroopa** [comment]
I was using a couple other mods as well and that may have caused the crash, so apologies if that is the reason why it failed

**Comment by Cryothemium** [comment]
I tried it as well, it left me with no error message and Exit Code: 0.

**Comment by apace100** [comment]
> 
> 
> This is not something I have control over unfortunately. As far as I can tell the newer versions of OptiFabric should be fine with Origins, but it's Origins which explicitly doesn't allow it to try though: [apace100/origins-fabric@84a8bb8](https://github.com/apace100/origins-fabric/commit/84a8bb8016cdd682c19e77f8532760a959b9e1bf). Based on the issue report on Origin's repo ([apace100/origins-fabric#338](https://github.com/apace100/origins-fabric/issues/338)) it might change when OptiFine releases fully for 1.17

Hey. Origins dev here. I saw that you updated and apparently fixed it, so for my new update which I released a few hours ago I wanted to reduce the "breaks" statement to versions below the one you fixed the compatibility for. However, the game still crashed with Origins and OptiFabric installed (same crash as before, supertroopa posted their crash report). But I still changed it from all version down to all current ones, so if you update and fix the compatibility players should be able to use it without me having to update again.

**Comment by Chocohead** [comment]
Think I've finally nailed it down so it'll work correctly on both 1.16 and 1.17. So long as people don't use Origins 1.0.0 (as it's missing a bug fix in Apoli) it should just work with [OptiFabric v1.11.20](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3422922), thank you for being patient.
