### ISSUE TITLE
[1.17]Crashes when picking up items

### ISSUE THREAD

**Issue by Raionblade** [Chocohead/OptiFabric#284]
Mods used:

- minihud-fabric-1.17.0-0.19.0-dev.20210609.185508
- malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
- optifabric-1.11.9
- preview_OptiFine_1.17_HD_U_G9_pre22

**Comment by Chocohead** [comment]
This was fixed in MiniHUD: maruohon/minihud@f0570c97578d9df80477b73b13f8c721fcd987d7, so you'll just need to update it
