### ISSUE TITLE
Crashes whilst rendering item from Applied Energistics 2 (Fabric, 1.16.2)

### ISSUE THREAD

**Issue by luxmiyu** [Chocohead/OptiFabric#29]
- AE2 works perfectly fine without OptiFabric. And vice-versa.
- Only crashes when rendering an item. It crashes when going to the 2nd page of the creative inventory:
```
The game crashed whilst rendering item
Error: java.lang.NullPointerException: Rendering item
Exit Code: -1
```
- Full Crash Report here: https://pastebin.com/ig816xu5. Seems to be an item called "sky_compass" which I assume is the Meteorite Compass.
- Shaders being used doesn't matter, crashes anyway, crash report done without any shaders selected (Off).

Mods used:
- fabric-api-0.19.0+build.398-1.16.jar
- appliedenergistics2-fabric-8.1.0-alpha.6.jar (https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
- OptiFine_1.16.2_HD_U_G3.jar
- optifabric-1.4.8.jar

Side note: Forge OptiFine and Forge AE2 work together just fine.

**Comment by Chocohead** [comment]
As an experiment, try with Patchouli installed. I have a feeling it's the same issue it had, and if present it will apply the fix it needed automatically.

**Comment by luxmiyu** [comment]
It does fix rendering the item in the inventory/hotbar/hand/offhand! However it crashes when placed on the ground.

```
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.optifine.override.ChunkCacheOF cannot be cast to net.fabricmc.fabric.impl.client.indigo.renderer.accessor.AccessChunkRendererRegion
Exit Code: -1
```
Full Report: https://pastebin.com/piSZJnXz

Used with `Patchouli-1.16-40-FABRIC.jar`.

Note: the first time i tested, rendering had some issues, the Meteorite Compass' hand looked really weird, unfortunately I didn't have my recording program running so I didn't capture it. The second time i ran Minecraft, it rendered correctly in the inventory and hands. Screenshot below (Running SEUS shaderpack):
![javaw_pppkdj2I4M](https://user-images.githubusercontent.com/67873657/92226127-89abb400-eea4-11ea-8b98-b95c51daec22.png)

**EDIT:** This is what it looks like on the ground without OptiFabric. Entering this world with OptiFabric causes it to crash in the same way as above.
![javaw_qgLXOpJUkZ](https://user-images.githubusercontent.com/67873657/92226998-e2c81780-eea5-11ea-8b41-bfeb77fbf31d.png)
