### ISSUE TITLE
OptiFabric doesn't work with Origins.

### ISSUE THREAD

**Issue by ZaneFlynt01** [Chocohead/OptiFabric#292]
So, I was gonna use OptiFabric on my game, but it says that it doesnt work alongside the origins mod. So either I can use optifine without it, but then some of my worlds don't work, or I keep all my worlds going but without extra framerate fixes. Please try to get this fixed. Thanks.

**Comment by GamerWierdo100** [comment]
same here ited be awsome if this was fixed

**Comment by Chocohead** [comment]
Duplicate of #281
