### ISSUE TITLE
Crashes 1.17 

### ISSUE THREAD

**Issue by HexRegulus** [Chocohead/OptiFabric#295]
When I select a shader Minecraft goes to the Mojang Logo Loading screen then crashes before it can load.  

Running MultiMC Loader with 1.17
Optifine HDU G9 Pre24
running on a mac.

Other Modes I'm using

Letmatica
MaLiLb
MiniHUD
Tweakaroo

I tried disabling these modes (not removing) and had the same issue.

Server is using Carpet Mod for 1.17

**Comment by Chocohead** [comment]
OptiFine doesn't support shaders on Macs yet: sp614x/optifine#5900
