### ISSUE TITLE
Incompatible with Minecraft 1.17.1 releases

### ISSUE THREAD

**Issue by Terminal-Access** [Chocohead/OptiFabric#304]
You guys are probably already aware of this but i though id post just in case you're not.

Minecraft Version: 1.17.1
Server Jar: paper-1.17.1-90
Optifabric: 1.11.9
Fabric Loader: 0.11.6

> Could not find required mod: optifabric requires {minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17]}
> Creating Empty clause ?

From the Log File

> [20:26:16] [main/INFO]: Loading for game Minecraft 1.17.1
> [20:26:16] [main/FATAL]: A critical error occurred
> net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: optifabric requires {minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17]}
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
> 	... 13 more
> Process exited with code 1.

**Comment by thewilloftheshadow** [comment]
https://github.com/Chocohead/OptiFabric/issues/294

**Comment by ghost** [comment]
Having the same issue, unfortunately. I hope sending this crash log/info helps the developer of the mod somehow.

_**Versions**_:
• **Fabric Version**: fabric-loader-0.11.6-1.17.1
• **Optifine Version**: OptiFine HD U G9 pre26
• **OptiFabric Version**: OptiFabric-v1.11.9

_**Fabric Loader log**_
![image](https://user-images.githubusercontent.com/75284322/125170796-b85a8100-e17e-11eb-8bc8-a96703f246c7.png)

_**Crash log**_
```[12:56:40] [main/INFO]: Loading for game Minecraft 1.17.1
[12:56:40] [ForkJoinPool-1-worker-53/WARN]: Non-Fabric mod JAR at "C:\Users\Herculean\Documents\[ Minecraft ]\[1.17.1] Fabric\mods\preview_OptiFine_1.17.1_HD_U_G9_pre26.jar", ignoring
[12:56:40] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: optifabric requires {minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 5 more```

**Comment by Jack-the-Pro101** [comment]
Guys I know how to launch even without it being on 1.17.1. So since Optifine 1.17.1 seems like it's compatible with 1.17 and 1.17.1 from their website I decided to open the optifabric-1.11.9.jar file with 7zip as an archive to edit something inside which allowed me to launch without issues:
1. Open the OptiFabric JAR file as an archive in something like 7zip
2. Right click fabric.mod.json and click edit
3. Scroll down a bit until you see:
  "depends": {
    "fabricloader": ">=0.8.0 <0.12",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5",
      "1.17-alpha.21.8.b",
      "1.17-beta.4",
      "1.17"
    ], ...
    4. Add a comma after "1.17" (because this is a JSON file) then make a new line and add "1.17.1". It should look like this after:
      "depends": {
    "fabricloader": ">=0.8.0 <0.12",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5",
      "1.17-alpha.21.8.b",
      "1.17-beta.4",
      "1.17",
      "1.17.1"
    ], ...
     Save the file, then 7zip will prompt you if you want to save it in the archive, say yes, and launch Fabric. Done. The only reason why OptiFabric isn't launching is because it doesn't think the version is compatible even though in this case it is, and so there you go... how to launch before the team finishes the 1.17.1 release officially.

**Comment by RSNFreud** [comment]
[https://we.tl/t-J7rYsu3nKC](https://we.tl/t-J7rYsu3nKC
)
Lasts one week

**Comment by Blzd87** [comment]
> Guys I know how to launch even without it being on 1.17.1. So since Optifine 1.17.1 seems like it's compatible with 1.17 and 1.17.1 from their website I decided to open the optifabric-1.11.9.jar file with 7zip as an archive to edit something inside which allowed me to launch without issues:
> 
> 1. Open the OptiFabric JAR file as an archive in something like 7zip
> 2. Right click fabric.mod.json and click edit
> 3. Scroll down a bit until you see:
>    "depends": {
>    "fabricloader": ">=0.8.0 <0.12",
>    "minecraft": [
>    "1.16.1",
>    "1.16.2",
>    "1.16.3",
>    "1.16.4",
>    "1.16.5",
>    "1.17-alpha.21.8.b",
>    "1.17-beta.4",
>    "1.17"
>    ], ...
>    4. Add a comma after "1.17" (because this is a JSON file) then make a new line and add "1.17.1". It should look like this after:
>    "depends": {
>    "fabricloader": ">=0.8.0 <0.12",
>    "minecraft": [
>    "1.16.1",
>    "1.16.2",
>    "1.16.3",
>    "1.16.4",
>    "1.16.5",
>    "1.17-alpha.21.8.b",
>    "1.17-beta.4",
>    "1.17",
>    "1.17.1"
>    ], ...
>    Save the file, then 7zip will prompt you if you want to save it in the archive, say yes, and launch Fabric. Done. The only reason why OptiFabric isn't launching is because it doesn't think the version is compatible even though in this case it is, and so there you go... how to launch before the team finishes the 1.17.1 release officially.

Confirmed Works!

**Comment by SirRemus** [comment]
> > Guys I know how to launch even without it being on 1.17.1. So since Optifine 1.17.1 seems like it's compatible with 1.17 and 1.17.1 from their website I decided to open the optifabric-1.11.9.jar file with 7zip as an archive to edit something inside which allowed me to launch without issues:
> > 
> > 1. Open the OptiFabric JAR file as an archive in something like 7zip
> > 2. Right click fabric.mod.json and click edit
> > 3. Scroll down a bit until you see:
> >    "depends": {
> >    "fabricloader": ">=0.8.0 <0.12",
> >    "minecraft": [
> >    "1.16.1",
> >    "1.16.2",
> >    "1.16.3",
> >    "1.16.4",
> >    "1.16.5",
> >    "1.17-alpha.21.8.b",
> >    "1.17-beta.4",
> >    "1.17"
> >    ], ...
> >    4. Add a comma after "1.17" (because this is a JSON file) then make a new line and add "1.17.1". It should look like this after:
> >    "depends": {
> >    "fabricloader": ">=0.8.0 <0.12",
> >    "minecraft": [
> >    "1.16.1",
> >    "1.16.2",
> >    "1.16.3",
> >    "1.16.4",
> >    "1.16.5",
> >    "1.17-alpha.21.8.b",
> >    "1.17-beta.4",
> >    "1.17",
> >    "1.17.1"
> >    ], ...
> >    Save the file, then 7zip will prompt you if you want to save it in the archive, say yes, and launch Fabric. Done. The only reason why OptiFabric isn't launching is because it doesn't think the version is compatible even though in this case it is, and so there you go... how to launch before the team finishes the 1.17.1 release officially.
> 
> Confirmed Works!

worked for me, thanks.

**Comment by CivetKitty** [comment]
This ticket can be summed up as "Please make the 1.17.1 version," as Optifine is already out for this version, yet Optifabric decided to make the questionable decision of deleting the 1.17.0 version from the curseforge page. WTF?

**Comment by Chocohead** [comment]
> 
> 
> Optifabric decided to make the questionable decision of deleting the 1.17.0 version from the curseforge page. WTF?

None of the versions have been removed from CurseForge so I'm not sure what you mean? Not every individual version on Github gets uploaded, but the ones that were uploaded with 1.17 support (v1.11.1 and v1.11.9 when you asked, v1.11.17 and v1.11.18 also support 1.17 too) are still there, as is the now redundant test v1.11.6.

**Comment by Terminal-Access** [comment]
Just wanted to say thanks to the team for the 1.17.1 releace, it's greatly appreciated, and can confirm for you guys i have this running on my paperMC setup.

Thanks again guys!

have a great day
