### ISSUE TITLE
Crash using 1.11.17 OptiFabric & ReplayMod

### ISSUE THREAD

**Issue by AllOutJay** [Chocohead/OptiFabric#309]
#### Steps to reproduce:

1. Install the necessary mods and mod loaders below.
2. Create a Replay (I did it in a singleplayer world).
3. Open the Replay editor.
4. Press "T".
5. Crash thus occurs.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.17.1
- OptiFabric: 1.11.17
- OptiFine: preview_OptiFine_1.17.1_HD_U_G9_pre27
- ReplayMod: 1.17-2.5.2-88-g96bb1ab
- Fabric Loader: 0.11.6
- Fabric API: 0.36.1+1.17
- Other mods (if relevant): n/a

#### Your most recent log file where the issue was present: 

- https://bin.bloom.host/gugedefevi.yaml
- [Github version of crash report: crash-2021-07-11_23.11.35-client.txt](https://github.com/Chocohead/OptiFabric/files/6798376/crash-2021-07-11_23.11.35-client.txt)

**Comment by joshuaepstein** [comment]
I get this issue too.

**Comment by Chocohead** [comment]
Bit of an accident in the Mixin, should be happy with [v1.11.18](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3386848)
