### ISSUE TITLE
Game crash on startup All of Fabric 3 modpack.

### ISSUE THREAD

**Issue by LeeLR** [Chocohead/OptiFabric#31]
Game crashes on startup with all of fabric 3 modpack.  When i deactivate optifabric it starts up fine.
[crash-2020-09-05_01.13.05-client.txt](https://github.com/Chocohead/OptiFabric/files/5177688/crash-2020-09-05_01.13.05-client.txt)

**Comment by Miros77** [comment]
download notenoughcrashes
