### ISSUE TITLE
Entities and mobs going black

### ISSUE THREAD

**Issue by rudoszka** [Chocohead/OptiFabric#314]
Hi i have a problem with optifabric. Using only optifine works fine. I checked other mods and there wasnt any problem either. 
![obraz](https://user-images.githubusercontent.com/87429582/125628753-40c81b10-b184-4a44-a37a-c499f32b592f.png)

**Comment by Chocohead** [comment]
This is/was an issue with OptiFine itself: sp614x/optifine#6013
