### ISSUE TITLE
Origins conflicts optifabric 

### ISSUE THREAD

**Issue by fleefer** [Chocohead/OptiFabric#315]
From the text provided in the fabric loader log I'm starting to think that origins have outright just put a line of code to stop any and all versions of optifabric, or I have no idea what I'm talking about. the latter is a lot more likely
![Screenshot 2021-07-14 194128](https://user-images.githubusercontent.com/22572409/125719527-e828fbe3-4ec1-4ad4-b4cb-7c5536f59453.png)

**Comment by NyxTheKitsune** [comment]
I've been running into the same issue which is regrettable since a lot of the members of a server I run prefer to use Optifine. If anyone could give us an idea for a fix that'd be appreciated.

**Comment by AlySapphire** [comment]
Bumping this issue. It's quite frustrating playing without optifine on an Origins server.

**Comment by Rockstarbop** [comment]
2nd bump. Multiple issues opened with same problem. Origins is cool mod and it sucks we can't play it with optifine.

**Comment by Kiropo** [comment]
according to a reply to a issue raised to the origin dev it is optifabric that is the issue and why the mods won't work together, but it does take times for things like this to be fixed.
