### ISSUE TITLE
Crash diggusmaximus

### ISSUE THREAD

**Issue by Miros77** [Chocohead/OptiFabric#32]
[crash.txt](https://github.com/Chocohead/OptiFabric/files/5177953/default.txt)

**Comment by Chocohead** [comment]
Fairly sure this is just from using the 1.16.1 version of Diggus Maximus on 1.16.2. Try with [1.3.1](https://www.curseforge.com/minecraft/mc-mods/diggus-maximus/files/3033631).

**Comment by Miros77** [comment]
Verify

сб, 5 сент. 2020 г. в 17:04, Chocohead <notifications@github.com>:
