### ISSUE TITLE
Optifabric crashes 1.17

### ISSUE THREAD

**Issue by Kaiiserr** [Chocohead/OptiFabric#333]
I can't seem to add optifabric to my modpack, as it keeps crashing. i didnt get any fabric error logs, so here's the pastebin to my minecraft launcher log 

https://pastebin.com/K3fvRkUm

anyone know any possible fixes? or is it just a compatibility issue?

**Comment by Kaiiserr** [comment]
when i remove the optifine mod file it does launch, but as it should it just tells me the optifine mod is missing

**Comment by Chocohead** [comment]
You'll want to update OptiFabric, the crash with Stacc was fixed in 1.11.11
