### ISSUE TITLE
origins conflicts with {optifabric @ [<=1.11.18]} Creating Empty clause ?

### ISSUE THREAD

**Issue by VRDork** [Chocohead/OptiFabric#336]
![image](https://user-images.githubusercontent.com/88256590/127754946-f1b59108-9925-4a4b-91fb-440d5b5582aa.png)
Hi! I keep having this issue whenever i try to open up minecraft in order to join my modded server (i was just updating it to 1.17 accordingly), here's my mods folder:

![image](https://user-images.githubusercontent.com/88256590/127754962-40aa13c6-22ba-451f-9cb5-8a0a514310a8.png)

**Comment by fzxn** [comment]
I've got the same error but in the {optifabric @ [<=1.11.18]} part it doesn't state the version "1.11.18" (See image). Mod works fine if played with latest OptiFine (1.17 HD U G9 pre32) and Fabric API alone. I thought it could be a conflict with a mod that uses the Fabric API, so I tried mixing and matching and some mods do work with OptiFabric but others don't.
![image](https://user-images.githubusercontent.com/70920580/127755309-d55db628-3b04-4aa4-af8d-ebbdd19f89cf.png)

**Comment by Rick4242** [comment]
I seem to be having the same issue, origins conflicting with optifabric, a fix would be appreciated, meanwhile here's what I'm seeing and my mods folder
![Screenshot 2021-08-02 181119](https://user-images.githubusercontent.com/42255398/127935227-9b4cdded-fa6e-4e83-80da-3b001663e030.png)
![image](https://user-images.githubusercontent.com/42255398/127935234-7d94c2a3-9e1b-47b8-9d31-703ae14fe66a.png)

**Comment by Klerka** [comment]
And same here

If I use origins 1.0.3 I get the {optifabric @ [<=1.11.18]} error
![1](https://user-images.githubusercontent.com/55291179/128081284-f075a461-d32b-48e4-8be6-6b13e7512504.png)
If I use origins 1.0.2 i get  {optifabric @ [*]} error
![3](https://user-images.githubusercontent.com/55291179/128081347-a670ed9b-1395-42ef-99a0-c3c7601bc79f.png)

My mod list: 
![2](https://user-images.githubusercontent.com/55291179/128081112-8bbf02a1-7b12-4f74-9f33-f90bc9a0f476.png)

Every selected mod was tested, only origins is incompatible and therefore I wasn't able to check the origins addons

**Comment by OllieDarwin** [comment]
The origins mod has added a feature to stop the game from launching when the optifabric mod is present because they have problems with clashing mixins (meaning that they're incompatible with eachother). Unfortunately, this isn't an origins problem and until the optifabric devs produce a fix you won't be able to use both optifabric and Origins at the same time.
