### ISSUE TITLE
1.17 release version doesn't work with fabric API

### ISSUE THREAD

**Issue by Doughy11** [Chocohead/OptiFabric#342]
You'd think a fabric mod would work with fabric API but I guess not. Exit code 0 every time it crashes

**Comment by frugbug** [comment]
This is a problem with the latest version of optifine, install "OptiFine HD U G9 pre32" instead and it should work fine.

**Comment by Doughy11** [comment]
Ok thanks bb

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Andre601** [comment]
> This is a problem with the latest version of optifine, install "OptiFine HD U G9 pre32" instead and it should work fine.

Do you know if this requires a fix on OF's end or would OptiFabric need to update to fix this?

**Comment by Nick-77ab2** [comment]
I'd assume it's a change to a part of optifine that optifabric needs to change in order to deal with. Optifabric is the compatibility mod that allows optifine to work with fabric, so any issues would have to be due to that.

**Comment by Nick-77ab2** [comment]
> > This is a problem with the latest version of optifine, install "OptiFine HD U G9 pre32" instead and it should work fine.
> 
> Do you know if this requires a fix on OF's end or would OptiFabric need to update to fix this?

I'd assume it's a change to a part of optifine that optifabric needs to change in order to deal with. Optifabric is the compatibility mod that allows optifine to work with fabric, so any issues would have to be due to that.

**Comment by GagetGaming7** [comment]
> > > This is a problem with the latest version of optifine, install "OptiFine HD U G9 pre32" instead and it should work fine.
> > 
> > 
> > Do you know if this requires a fix on OF's end or would OptiFabric need to update to fix this?
> 
> I'd assume it's a change to a part of optifine that optifabric needs to change in order to deal with. Optifabric is the compatibility mod that allows optifine to work with fabric, so any issues would have to be due to that.

If it is on Optifabric's end doesn't that mean it won't be fixed? Hasn't the developer of Optifabric said they no longer plan to update it?

**Comment by BBloom81** [comment]
What?

First, OP says they have an issue with Fabric API, not Optifine.

Second, it is correct that Optifabric does not work with Pre-33, but that is NOT an Optifine issue/problem, that is Optifabric needing to be updated to support the latest Optifine.

Third, the original Optifabric dev stopped working on it back in 1.15 or maybe at the start of 1.16, but Chocohead has been updating for a while.  There has been nothing from Chocohead stating they are stopping development/support for Optifabric anywhere that I can find.  I just imagine they don't want to spend their time updating for every Pre-release and would rather just wait till the final release of Optifine is out, and I don't blame them one bit.

**Comment by Chocohead** [comment]
It was OptiFine including changes to Forge's patches which broke OptiFabric, it should behave again with [OptiFabric v1.11.20](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3422922)
