### ISSUE TITLE
Crash Thallium

### ISSUE THREAD

**Issue by Miros77** [Chocohead/OptiFabric#35]
[crash-2020-09-05_16.48.29-client.txt](https://github.com/Chocohead/OptiFabric/files/5178166/crash-2020-09-05_16.48.29-client.txt)

**Comment by Chocohead** [comment]
Thallium is too clunky and invasive to work around. It's additions to the options screen wouldn't work around OptiFine's, many of it's fixes are duplicated by OptiFine itself already, and the ones which aren't are generally taken as replacing methods completely which would break anything which OptiFine (as well as any other mod) might have put in said methods.

**Comment by Miros77** [comment]
OK

сб, 5 сент. 2020 г. в 18:20, Chocohead <notifications@github.com>:
