### ISSUE TITLE
7803 loop error's

### ISSUE THREAD

**Issue by morottao** [Chocohead/OptiFabric#350]
I had to send the error through dropbox, because no site accepted the file size. 

https://www.dropbox.com/sh/7mlwbo5u14svwxk/AABhDelB6a2OHa9xGopdzxAAa?dl=0

in the "clean error" version, the code that is giving an error 7803 times is erased, but the line in which it was generated is not, so the file decreases from 20mb to 1mb
The menu opens on line 145965

> [21:06:37] [Render thread/ERROR]: [OptiFine] 
> java.lang.IllegalAccessException: Can not set static final java.lang.String field net.minecraft.class_442.field_32272 to java.lang.String
> 	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.38) ~[?:?]
> 	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
> 	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
> 	at jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77) ~[?:?]
> 	at java.lang.reflect.Field.set(Field.java:793) ~[?:?]
> 	at net.optifine.reflect.Reflector.setFieldValue(Reflector.java:1277) ~[Optifine-mapped.jar:?]
> 	at net.minecraft.client.render.GameRenderer.updateMainMenu(GameRenderer:1792) ~[?:?]
> 	at net.minecraft.client.render.GameRenderer.frameInit(GameRenderer:1728) ~[?:?]
> 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:1128) ~[?:?]
> 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
> 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

the game opens, but even in the menu, the error continues
and sometimes it crashes for loading entities like the bunny, pig or bed
and when using the "Selective Entity Removal" mod to disable the bunny, the crashes stop

-- translated by google translator  --

**Comment by morottao** [comment]
solved, it was a conflict with the mod "crafted!", I removed it and switched to datapack and updated the fabricapi because it only worked with version 0.37.1

**Comment by MissGamerz** [comment]
please close the issue if you solved it

**Comment by Chocohead** [comment]
This is a bug in OptiFine itself: sp614x/optifine#6160
