### ISSUE TITLE
optifabric 1.17.1 does not want to start. please help me....

### ISSUE THREAD

**Issue by NiceGamer42** [Chocohead/OptiFabric#355]
Hello

sorry that i don't write so well in english because i'm  german
and i have no idea about programming and such.
so now to my problem: 

optifabric doesn't want to start for me, the same message always comes from the fabric loader:

Found conflicting mods: lambdacontrols conflicts with {optifabric @ [*]}
   Creating Empty clause ?
![bananen sind ok](https://user-images.githubusercontent.com/89472330/130650797-610d7bef-9587-4763-b4b6-c54973ccd8ff.PNG)
 
ich habe schon alles ausprobiert alle optifine versionen und alles 1.17.1 optifabri wersionen.   
and when I close the window of the fabric loader the minecraft launcher comes with the: exit-code: 0
![ich bin angemeldet](https://user-images.githubusercontent.com/89472330/130650800-3c375c8b-c49d-4a27-afbd-81589168ccdd.PNG)

please help me?

**Comment by themg95** [comment]
Remove LambdaControls

**Comment by NiceGamer42** [comment]
> Remove LambdaControls

i don't understand what you mean i have no idea and of mod end development and so on.

so please tell me what you mean and how to fix it.

**Comment by themg95** [comment]
Remove LambdaControls from your mods

**Comment by NiceGamer42** [comment]
> Remove LambdaControls from your mods

I thank you for helping me and sorry that I didn't understand you the first time. ^^ "

**Comment by Chocohead** [comment]
Duplicate of #51
