### ISSUE TITLE
optifabric error exite code -1

### ISSUE THREAD

**Issue by elfaco** [Chocohead/OptiFabric#356]
im new to using fabric and stuff and i get that error each time i put optifabric and optifine

mod i put  
AppleTreesRev-Fabric-1.17.1-v2.2
architectury-2.4.26-fabric
arma_infinitum-0.1
better-nether-5.1.3
cloth-config-5.0.38-fabric
dragonloot-1.0.9
DungeonsMod-1.12.2-1.0.8
ElementalSwords-1.17.1-2.0.2
enhancedcelestials-2.0.2-1.17
fabric-api-0.39.1+1.17
InventoryHUD-fabric-[1.17.x]-3.4.0
mcdw-3.4.1
MoreStructuresForWilliamWythersOverhauledOverworld-1.1
oresnmores1.2.2
optifabric-1.11.20
preview_OptiFine_1.17.1_HD_U_G9_pre34
RoughlyEnoughItems-6.0.272-alpha-fabric
WilliamWythersOverhauledOverworld-1.6(1.17.x)
Xaeros_Minimap_21.15.1_Fabric_1.17.1
x-enchant-1.0.5
thanks in advance for the help

**Comment by elfaco** [comment]
> im new to using fabric and stuff and i get that error each time i put optifabric and optifine
> 
> mod i put
> AppleTreesRev-Fabric-1.17.1-v2.2
> architectury-2.4.26-fabric
> arma_infinitum-0.1
> better-nether-5.1.3
> cloth-config-5.0.38-fabric
> dragonloot-1.0.9
> DungeonsMod-1.12.2-1.0.8
> ElementalSwords-1.17.1-2.0.2
> enhancedcelestials-2.0.2-1.17
> fabric-api-0.39.1+1.17
> InventoryHUD-fabric-[1.17.x]-3.4.0
> mcdw-3.4.1
> MoreStructuresForWilliamWythersOverhauledOverworld-1.1
> oresnmores1.2.2
> optifabric-1.11.20
> preview_OptiFine_1.17.1_HD_U_G9_pre34
> RoughlyEnoughItems-6.0.272-alpha-fabric
> WilliamWythersOverhauledOverworld-1.6(1.17.x)
> Xaeros_Minimap_21.15.1_Fabric_1.17.1
> x-enchant-1.0.5
> thanks in advance for the help

crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

**Comment by elfaco** [comment]
i found the problem enhancedcelestials-2.0.2-1.17

**Comment by Chocohead** [comment]
Duplicate of #375
