### ISSUE TITLE
MOD

### ISSUE THREAD

**Issue by J-a-y-d-y** [Chocohead/OptiFabric#358]
Doesn't work with the lambda controller mod. It crashes immediately and you can't play. witch sucks because im on a laptop because my desktop is packed as I am in between places. so I use a controller :/ Please fix it sooooon.

**Comment by MissGamerz** [comment]
seems like a incompatibility with optifine and that MOD nothing to do with optifabric.....

**Comment by Chocohead** [comment]
Duplicate of #51
