### ISSUE TITLE
Incompatibility with Iris Shaders & Sodium

### ISSUE THREAD

**Issue by EladBG-code** [Chocohead/OptiFabric#359]
To be honest I am aware why they conflict with one another but OptiFabric should let Iris Shaders handle the shaders while letting the user have the Optifine options in Video Options...

**Comment by gamemaster64665** [comment]
there 2 different shader works

**Comment by Chocohead** [comment]
OptiFine isn't in easy to break up chunks like that, either you have everything or nothing. Hence you can't skip its shaders for Iris or optimisations for Sodium (#40)
