### ISSUE TITLE
Seems to be incompatible with Lamdacontrol mod, crashes instantly upon trying to launch.

### ISSUE THREAD

**Issue by ShockinglySane** [Chocohead/OptiFabric#360]
As said, seems to crash the game immediately upon starting if I have the Lamdacontrol mod enabled as well.

**Comment by ShockinglySane** [comment]
NVM clicked the issue just called "MOD" and see it was already addressed and unfixable. Shame.

**Comment by Chocohead** [comment]
Duplicate of #51
