### ISSUE TITLE
Crashing upon startup

### ISSUE THREAD

**Issue by PassiveLemon** [Chocohead/OptiFabric#362]
Optifine HD-U-G9
Optifabric 1.11.20
Optifine1.16.5 and below work with their respective Optifabric versions but not 1.17.1.
[crash-2021-09-05_12.49.01-client.txt](https://github.com/Chocohead/OptiFabric/files/7112026/crash-2021-09-05_12.49.01-client.txt)
[latest.log](https://github.com/Chocohead/OptiFabric/files/7112027/latest.log)

**Comment by mullcom** [comment]
same here. dont want to move over to 1.17 yeat

**Comment by mullcom** [comment]
![image](https://user-images.githubusercontent.com/34793390/132993425-cdd42379-d9f4-4cd3-9efa-c923f9ecc2e3.png)

**Comment by mullcom** [comment]
are any looking in to this ?

**Comment by mullcom** [comment]
Got it working!!!!"

I use G7 file and it started.
