### ISSUE TITLE
No support for 1.17.1

### ISSUE THREAD

**Issue by basedSkeleton** [Chocohead/OptiFabric#365]
![Screenshot 2021-09-06 173859](https://user-images.githubusercontent.com/82617401/132268502-504d1520-1503-40a3-b66e-968e56c844fc.jpg)

**Comment by llama-for3ver** [comment]
Same with me :/

**Comment by llama-for3ver** [comment]
You need to download the latest version (1.11.20) [HERE](https://www.curseforge.com/minecraft/mc-mods/optifabric/download/3422922)

**Comment by Chocohead** [comment]
As mentioned you need OptiFabric 1.11.17+ for 1.17.1
