### ISSUE TITLE
Cant find Optifine H1 pre2 jar

### ISSUE THREAD

**Issue by dbrighthd** [Chocohead/OptiFabric#374]
I assume this is because the file locations were changed in order to work with forge 
![image](https://user-images.githubusercontent.com/68525639/134252040-ed6b018f-a94f-439d-adcc-4e65a8203e4c.png)

**Comment by ghost** [comment]
Instructions posted by sp614x. This is for jarmods but it may help here:

This is only applicable for versions beyond H1_pre2

Steps:
1. Extract the MOD jar in the OF installer
2. Open it with some archiver (7z, winrar, etc)
3. Move all classes from folder notch to the root* folder (preserving folder structure)
4. Proceed as normal when installing jar mod.

EDIT: Doesn't seem to help with Optifabric but helps with jarmods.

**Comment by sp614x** [comment]
Relevant: https://github.com/sp614x/optifine/issues/6216

**Comment by R00tB33rMan** [comment]
> I assume this is because the file locations were changed in order to work with forge
> ![image](https://user-images.githubusercontent.com/68525639/134252040-ed6b018f-a94f-439d-adcc-4e65a8203e4c.png)

I've implemented my fix and it works flawlessly with the latest public OptiFabric build.

Here are the steps:

1. Open your OptiFine container and extract utilizing 7-Zip or WinRar.
2. Then, click "notch -> net".
3. Move "minecraftforge & optifine" to where "net" is located.
4. Delete "net".
5. Return to the main directory of the OptiFine jar and rename "notch" to "net".

From there, everything should work in accordance with your expectations.

(Providing my compiled build if you trust me, and you should).
[preview_OptiFine_1.17.1_HD_U_H1_pre2.zip](https://github.com/Chocohead/OptiFabric/files/7206997/preview_OptiFine_1.17.1_HD_U_H1_pre2.zip)
[preview_OptiFine_1.17.1_HD_U_H1_pre3.zip](https://github.com/Chocohead/OptiFabric/files/7228486/preview_OptiFine_1.17.1_HD_U_H1_pre3.zip) - Just added latest version patch.
[preview_OptiFine_1.17.1_HD_U_H1_pre4.zip](https://github.com/Chocohead/OptiFabric/files/7254953/preview_OptiFine_1.17.1_HD_U_H1_pre4.zip) - Newest version that was released as of some time today.
[preview_OptiFine_1.17.1_HD_U_H1_pre5.zip](https://github.com/Chocohead/OptiFabric/files/7281424/preview_OptiFine_1.17.1_HD_U_H1_pre5.zip) - Latest version as of October 4, 2021.
[preview_OptiFine_1.17.1_HD_U_H1_pre6.zip](https://github.com/Chocohead/OptiFabric/files/7314044/preview_OptiFine_1.17.1_HD_U_H1_pre6.zip) - Latest version as of October 8, 2021. Though this compiled under these terms, the game no longer starts accordingly. From this point on, we'll need to wait for a patch from the developer.

Obviously, rename from ".zip" to ".jar".

**Comment by StarGuyR7** [comment]
> > I assume this is because the file locations were changed in order to work with forge
> > ![image](https://user-images.githubusercontent.com/68525639/134252040-ed6b018f-a94f-439d-adcc-4e65a8203e4c.png)
> 
> I've implemented my fix and it works flawlessly with the latest public OptiFabric build.
> 
> Here are the steps:
> 
> 1. Open your OptiFine container and extract utilizing 7-Zip or WinRar.
> 2. Then, click "notch -> net".
> 3. Move "minecraftforge & optifine" to where "net" is located.
> 4. Delete "net".
> 5. Return to the main directory of the OptiFine jar and rename "notch" to "net".
> 
> From there, everything should work in accordance with your expectations.
> 
> (Providing my compiled build if you trust me, and you should). [preview_OptiFine_1.17.1_HD_U_H1_pre2.zip](https://github.com/Chocohead/OptiFabric/files/7206997/preview_OptiFine_1.17.1_HD_U_H1_pre2.zip) [preview_OptiFine_1.17.1_HD_U_H1_pre3.zip](https://github.com/Chocohead/OptiFabric/files/7228486/preview_OptiFine_1.17.1_HD_U_H1_pre3.zip) - Just added latest version patch. [preview_OptiFine_1.17.1_HD_U_H1_pre4.zip](https://github.com/Chocohead/OptiFabric/files/7254953/preview_OptiFine_1.17.1_HD_U_H1_pre4.zip) - Newest version that was released as of some time today.
> 
> Obviously, rename from ".zip" to ".jar".

this doesn't work for me, it has the same problem or it'll say it's an unexpected error and won't load
![image](https://user-images.githubusercontent.com/89373364/135863381-6e5d208c-f6f9-42d5-84cf-3da647f1db3f.png)

**Comment by ZekerZhayard** [comment]
@LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot

**Comment by StarGuyR7** [comment]
> @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot

they're in the mod folder
![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)

**Comment by StarGuyR7** [comment]
> > @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot
> 
> they're in the mod folder ![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)

i just realized i forgot to add them back

**Comment by Neubulae** [comment]
> > > @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot
> > 
> > 
> > they're in the mod folder ![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)
> 
> i just realized i forgot to add them back

bruh

**Comment by StarGuyR7** [comment]
> > > @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot
> > 
> > 
> > they're in the mod folder ![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)
> 
> i just realized i forgot to add them back

added them back 
![image](https://user-images.githubusercontent.com/89373364/135873098-5d8a87ab-2368-4895-a72b-b3dc75e842a8.png)

**Comment by R00tB33rMan** [comment]
> > > > @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot
> > > 
> > > 
> > > they're in the mod folder ![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)
> > 
> > 
> > i just realized i forgot to add them back
> 
> added them back ![image](https://user-images.githubusercontent.com/89373364/135873098-5d8a87ab-2368-4895-a72b-b3dc75e842a8.png)

Glad you got that sorted! Just pushed the latest pre-release in here.

**Comment by StarGuyR7** [comment]
> > > > > @LittKingLoser it seems your optifine and optifabric jar are not in mods folder? I can't see them in your screenshot
> > > > 
> > > > 
> > > > they're in the mod folder ![image](https://user-images.githubusercontent.com/89373364/135868206-79c83e45-1732-406b-b945-f705cf518aee.png)
> > > 
> > > 
> > > i just realized i forgot to add them back
> > 
> > 
> > added them back ![image](https://user-images.githubusercontent.com/89373364/135873098-5d8a87ab-2368-4895-a72b-b3dc75e842a8.png)
> 
> Glad you got that sorted! Just pushed the latest pre-release in here.

i never fixed it life hurts

**Comment by DuskMC** [comment]
> > I assume this is because the file locations were changed in order to work with forge
> > ![image](https://user-images.githubusercontent.com/68525639/134252040-ed6b018f-a94f-439d-adcc-4e65a8203e4c.png)
> 
> I've implemented my fix and it works flawlessly with the latest public OptiFabric build.
> 
> Here are the steps:
> 
> 1. Open your OptiFine container and extract utilizing 7-Zip or WinRar.
> 2. Then, click "notch -> net".
> 3. Move "minecraftforge & optifine" to where "net" is located.
> 4. Delete "net".
> 5. Return to the main directory of the OptiFine jar and rename "notch" to "net".
> 
> From there, everything should work in accordance with your expectations.
> 
> (Providing my compiled build if you trust me, and you should). [preview_OptiFine_1.17.1_HD_U_H1_pre2.zip](https://github.com/Chocohead/OptiFabric/files/7206997/preview_OptiFine_1.17.1_HD_U_H1_pre2.zip) [preview_OptiFine_1.17.1_HD_U_H1_pre3.zip](https://github.com/Chocohead/OptiFabric/files/7228486/preview_OptiFine_1.17.1_HD_U_H1_pre3.zip) - Just added latest version patch. [preview_OptiFine_1.17.1_HD_U_H1_pre4.zip](https://github.com/Chocohead/OptiFabric/files/7254953/preview_OptiFine_1.17.1_HD_U_H1_pre4.zip) - Newest version that was released as of some time today. [preview_OptiFine_1.17.1_HD_U_H1_pre5.zip](https://github.com/Chocohead/OptiFabric/files/7281424/preview_OptiFine_1.17.1_HD_U_H1_pre5.zip) - Latest version as of October 4, 2021. [preview_OptiFine_1.17.1_HD_U_H1_pre6.zip](https://github.com/Chocohead/OptiFabric/files/7314044/preview_OptiFine_1.17.1_HD_U_H1_pre6.zip) - Latest version as of October 8, 2021. Though this compiled under these terms, the game no longer starts accordingly. From this point on, we'll need to wait for a patch from the developer.
> 
> Obviously, rename from ".zip" to ".jar".

Thank u so much, now i can finally use optifine on fabric! but it is only on optifine H1 pre 5, but for me this is good enough

**Comment by Zerphim** [comment]
I had the same issue where it could not find the Optifine jar file and for me the resolution was to use OptiFine_1.17.1_HD_U_G9 as any of the H1 previews would make my game crash instantly.

Also it appears that Optifabric 1.11.20 is not compatible with Lithium mod.

As an idea, it may be worth just adding the skeleton for the fabric mods [fabric API, Cloth Config API, modmenu, Architectury API] alongside Optifine and Optifabric and afterwards slowly adding the other fabric mods in order to see if maybe one of the mods may not be compatible if the game crashes instantly when opening it.

**Comment by iBrezz** [comment]
> > I assume this is because the file locations were changed in order to work with forge
> > ![image](https://user-images.githubusercontent.com/68525639/134252040-ed6b018f-a94f-439d-adcc-4e65a8203e4c.png)
> 
> I've implemented my fix and it works flawlessly with the latest public OptiFabric build.
> 
> Here are the steps:
> 
> 1. Open your OptiFine container and extract utilizing 7-Zip or WinRar.
> 2. Then, click "notch -> net".
> 3. Move "minecraftforge & optifine" to where "net" is located.
> 4. Delete "net".
> 5. Return to the main directory of the OptiFine jar and rename "notch" to "net".
> 
> From there, everything should work in accordance with your expectations.
> 
> (Providing my compiled build if you trust me, and you should). [preview_OptiFine_1.17.1_HD_U_H1_pre2.zip](https://github.com/Chocohead/OptiFabric/files/7206997/preview_OptiFine_1.17.1_HD_U_H1_pre2.zip) [preview_OptiFine_1.17.1_HD_U_H1_pre3.zip](https://github.com/Chocohead/OptiFabric/files/7228486/preview_OptiFine_1.17.1_HD_U_H1_pre3.zip) - Just added latest version patch. [preview_OptiFine_1.17.1_HD_U_H1_pre4.zip](https://github.com/Chocohead/OptiFabric/files/7254953/preview_OptiFine_1.17.1_HD_U_H1_pre4.zip) - Newest version that was released as of some time today. [preview_OptiFine_1.17.1_HD_U_H1_pre5.zip](https://github.com/Chocohead/OptiFabric/files/7281424/preview_OptiFine_1.17.1_HD_U_H1_pre5.zip) - Latest version as of October 4, 2021. [preview_OptiFine_1.17.1_HD_U_H1_pre6.zip](https://github.com/Chocohead/OptiFabric/files/7314044/preview_OptiFine_1.17.1_HD_U_H1_pre6.zip) - Latest version as of October 8, 2021. Though this compiled under these terms, the game no longer starts accordingly. From this point on, we'll need to wait for a patch from the developer.
> 
> Obviously, rename from ".zip" to ".jar".

I dont have notch and i have the same issue

**Comment by Chocohead** [comment]
This should (finally) be resolved with the [newest version](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3533297).
