### ISSUE TITLE
No longer compatible with Enhanced Celestials after 1.17

### ISSUE THREAD

**Issue by beetrootstew** [Chocohead/OptiFabric#375]
After the 1.17 update for enhanced celestials the LightmapTextureManagerMixin doesnt seem to fix the compatibility issues anymore and this is the crash report below. After removing enhanced celestials and keeping optifine on the game runs with no issue and same for removing optifabric and leaving enhanced celestials on so besides that theres no compatibility issues with the other mods listed in the crashlog

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/22/21, 9:00 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_757.<init>(class_757.java:269)
	at net.minecraft.class_310.<init>(class_310.java:565)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.enhancedcelestials.mixins.json:LightmapTextureManagerMixin] from phase [DEFAULT] in config [optifabric.compat.enhancedcelestials.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.enhancedcelestials.mixins.json:LightmapTextureManagerMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class corgitaco/enchancedcelestials/mixin/MixinLightMapTexture targetting net.minecraft.class_765
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:90)
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:57)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$eep000$fillPatchouliContext(class_128.java:1021)
	at net.minecraft.class_128.<init>(class_128.java:42)
	at net.minecraft.class_128.method_560(class_128.java:339)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 562982776 bytes (536 MiB) / 1170210816 bytes (1116 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e07
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39889.57
	Virtual memory used (MB): 21869.02
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 1122.85
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5120m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		additionalbars: Additional Bars 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancementplaques: Advancement Plaques 1.4.0
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.11
		amecsapi: Amecs API 1.1.5+mc21w16a
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		arcanus: Arcanus 1.13
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.5.27
		artifality: Artifality 0.3.5
		assembly: Assembly 21w06a-1.0.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.2
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.6
		bclib: BCLib 0.3.1
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.1
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterthirdperson: Better Third Person 1.5.0
		bewitchment: Bewitchment 1.17-6
		biomeinfo: Biome Info 1.17-7
		boatcontainer: BoatContainer 1.0.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.17.1
		caelus: Caelus API 0.0.17-1.17
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.6-1.17.1
		conjuring: Conjuring 1.0.7
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.5.0+1.17
		cozy_camping: Cozy Camping 1.0.0-1.17
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dataattributes: Data Attributes 1.0.3
		dawn: Dawn API 2.0.6
		deepslatecutting: Deepslate Cutting 1.2.0
		dehydration: Dehydration 1.2.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dragonloot: DragonLoot 1.0.9
		drinkbeer: Drink Beer 2.1
		drippyloadingscreen: Drippy Loading Screen 1.1.1
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		dynamicfps: Dynamic FPS 2.0.5
		dynmus: Dynamic Music 1.3.1
		earthtojavamobs: Earth2Java 1.7.3+1.17
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchant_giver: Enchant Giver 1.1.0
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		endrem: End Remastered 4.1.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhanced_mushrooms: Enhanced Mushrooms 1.0.5
		enhancedcelestials: Enhanced Celestials 2.0.0
		environmentz: EnvironmentZ 1.1.6
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fancymenu: FancyMenu 2.2.2
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		firstperson: FirstpersonModel 2.0.3
		flesh2leather: Flesh2Leather 1.0.2
		flintytools: Flinty Tools 1.0.0
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		forgottenrecipes: Forgotten Recipes 1.0.3
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.14
		go-fish: Go Fish 1.3.0-beta-1.17.1
		gobber2: Gobber2 2.4.48
		goldenhoppers: Golden Hoppers 1.1.0
		goosiklib: Goosik Lib 0.1.0
		grass_pass: Grass Bypass 1.0.0
		graveyard: The Graveyard 1.0
		harvest_scythes: Harvest Scythes 2.0.6
		hologram-api: Hologram API 0.2.1+1.17.1
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		icarus: Icarus 1.3
		illuminations: Illuminations 1.7.2
		impaled: Impaled 1.0.1
		impersonate: Impersonate 2.3.3
		inmis: Inmis 2.3.2-1.17.1
		interactic: Interactic 0.1.5-1.17
		inventoryhud: Inventory HUD + 3.4.0
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		just_end_anchor: Just An End Anchor 1.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.9.1
		konkrete: Konkrete 1.2.3
		krypton: Krypton 0.1.4
		kubejs: KubeJS 1605.3.10-build.9999
		lacrimis: Lacrimis 2.1.3+1.17.1
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magicfungi: Magic Fungi 0.3.1-BETA+1.17.1
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.7.10
		mcdar: MC Dungeons Artifacts 1.4.1
		mcdw: MC Dungeons Weapons 3.4.2
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.1.5
		megane: megane 5.3.0
		megane-base: megane-base 5.3.0
		megane-fabric-transfer: megane-fabric-transfer 5.3.0+1.3.0-fc40aa9d18
		megane-runtime: megane-runtime 5.3.0
		megane-vanilla: megane-vanilla 5.3.0+1.17.1
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.0-beta.7
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.2
		morerespawnanchors: More Respawn Anchors 1.0.2
		morevillagers-fabric: MoreVillagersFabric 2.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		multipart_entities: MultipartEntities 1.1.2-1.17
		mythic-mounts: Mythic Mounts 1.17.1-1.3
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		nearsightedly: Near-Sightedly 1.2.1
		net_objecthunter_exp4j: exp4j 0.4.8
		netherite_items: Netherite Items 1.1.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		optifabric: OptiFabric 1.11.20
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		outvoted: Outvoted 2.0.0-alpha.13
		owo: OwO 0.1.1
		oxidized: Oxidized 1.4.0
		oxidizelib: OxidizeLib 1.1.0
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.2.2
		pehkui: Pehkui 2.4.0+1.14.4-1.17.1
		pigsteel: Pigsteel Mod 1.6.6
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		playerex: PlayerEx 3.0.3
		polymer: Polymer 0.1.0-rc.4+1.17.1
		polymorph: Polymorph 0.0.13-1.17.1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		primordial-shores-add-on-for-wwoo: Primordial Shores add-on for William Wythers Overhauled Overworld 1.0
		promenade: Promenade 2.1.2
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		quartzelv: Quartz Elevator 1.2.5
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.17-3
		repurposed_structures: Repurposed Structures 2.3.3+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		rhino: Rhino 1605.1.2-build.40
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		runelic: Runelic 3.0.1
		scorch: Scorch 1.1.2
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		shwfox: Shadew's Foxes 1.0
		simple-rpc: Simple Rpc 1.17-2.3.1-fabric
		sit: Sit 1.17.1-13
		snowundertrees: Snow Under Trees 1.0.0
		somnus: Somnus API 0.0.14-1.17.1
		spark: spark 1.6.1
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		talking-villagers: Talking Villagers 1.1.3
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terraria_paintings: Terraria Paintings 1.0.0
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.5
		transliterationlib: TRansliterationLib 1.1.0
		traverse: Traverse 4.0.0-beta.2
		trinkets: Trinkets 3.0.4
		tweed: Tweed 3.0.0-beta.26
		universal-graves: Universal Graves 1.0.8+1.17.1
		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
		upgradedshulkers: Upgraded Shulkers 1.0.2-1.17
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.2.0
		veinmining: Vein Mining 0.0.10-1.17
		villagernames: Villager Names 2.0.0
		villagershats: Goosik's Villager Hats 1.2.0
		visuality: Visuality 0.1.3
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.4
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.6
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wrenchable: Wrenchable 1.1.0+1.17
		wthit: wthit 3.9.0
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		xps: Xp Obelisk 0.2.0_for_1.17.x_Fabric
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.17.1_HD_U_G9
	OptiFine Build: 20210831-004129
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-1.0.1.zip
	OpenGlVersion: 3.2.0 NVIDIA 471.96
	OpenGlRenderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/super/Twitch/Minecraft/Instances/Medieval Minecraft [FABRIC] - 1.17.1/.optifine/OptiFine_1.17.1_HD_U_G9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by kurokuma10** [comment]
Still non-compatible for any new visitors to the thread. 
Fabric Loader 0.12.5-1.17.1
Fabric api 0.43.1+1.17
Optifabric 1.12.5
Optifine 1.17.1 HD U H1
Enh Celestials 2.0.6

Side-Inquiry:
Do we know which mod is the root of the conflict between the two?
[crash-2021-11-26_03.31.39-client.txt](https://github.com/Chocohead/OptiFabric/files/7607736/crash-2021-11-26_03.31.39-client.txt)
