### ISSUE TITLE
Not compatible with "Dashloader" and "Iris" --> "Creating empty clause?"

### ISSUE THREAD

**Issue by Dantschl** [Chocohead/OptiFabric#376]

**Comment by MenacingPerson** [comment]
If you want shaders in optifabric.... Use optifabric

**Comment by MissGamerz** [comment]
why would you run iris and optifabric together....... they do the same thing 

as for dashloader its not compatible at all due to the hacking both parties do get their objective working properly

**Comment by Chocohead** [comment]
Iris is covered in #359, Dashloader could work if (probably quite fragile) OptiFine specific handling logic was added (#211)
