### ISSUE TITLE
Optifabric crashes at startup when Optifine is in the mod folder

### ISSUE THREAD

**Issue by dustplayschaos** [Chocohead/OptiFabric#381]
Whenever I try to launch Optifabric with Optifine G9 in the mod folder, the game crashes and gives an error code 0. When I try to do it with Optifine H1 prerelease 3 or 4, it says that Optifabric can't locate the JAR folder. How can I fix it?

**Comment by ZekerZhayard** [comment]
https://github.com/Chocohead/OptiFabric/issues/374
