### ISSUE TITLE
OptiFabric could not find the Optifine jar in the mods folder

### ISSUE THREAD

**Issue by SuperLazySnorlax** [Chocohead/OptiFabric#383]
Screenshot of MC:
![image](https://user-images.githubusercontent.com/91842178/135763467-1d93335f-d5d9-4b6b-a4eb-b8336915d379.png)

Mods folder:
![image](https://user-images.githubusercontent.com/91842178/135763698-477a5a85-af14-440a-82b4-34e413ef9c33.png)

What's going on here?

**Comment by ZekerZhayard** [comment]
https://github.com/Chocohead/OptiFabric/issues/374#issuecomment-924491077
