### ISSUE TITLE
Optifabric does not work with preview versions of Optifine

### ISSUE THREAD

**Issue by DieselDorky16** [Chocohead/OptiFabric#391]
Trying to load a preview version of Optifine via Optifabric will give you an error saying the Optifine jar is not installed, even though  it's in the mod folder
![Screen Shot 2021-10-07 at 1 49 44 PM](https://user-images.githubusercontent.com/43275803/136437180-47914759-61a2-4c77-b3ca-f1c452553003.png)

**Comment by NaiNonTH** [comment]
Same as #374
