### ISSUE TITLE
Incompatible with preview_OptiFine_1.17.1_HD_U_H1_pre6 (When you have Fabric API)

### ISSUE THREAD

**Issue by NaiNonTH** [Chocohead/OptiFabric#392]
When you install OptiFine with OptiFabric, Whenever you still have Fabric API (mine is 0.40.6), The game crashed after you launched.

**Comment by NaiNonTH** [comment]
OptiFabric is outdated. Plz update this :(

**Comment by JediM4ster** [comment]
I have the same issue. I can't get optifabric to work with optfine, fabric runs normally without it. I can't get into the game so the above link doesn't really apply. It crashes on launch.

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394
