### ISSUE TITLE
Doesn't work on 1.16.1

### ISSUE THREAD

**Issue by rbits0** [Chocohead/OptiFabric#4]
Minecraft crashes when trying to use OptiFabric 1.4.0 on 1.16.1. I removed both OptiFabric and OptiFine, and it started up normally.
I am using OptiFine 1.16.1 HD U G2.

[latest.log](https://github.com/Chocohead/OptiFabric/files/5146450/latest.log)

**Comment by Chocohead** [comment]
Make sure you're using the `_build2` version of Carpet, as per gnembon/fabric-carpet#405

**Comment by rubikgamer9** [comment]
Can I have a link to build 2, I can't seem to find the version for 1.16.1

**Comment by topia** [comment]
> Can I have a link to build 2, I can't seem to find the version for 1.16.1

I'm not sure that I understand your ask (especially what it mean is "build 2"), but you can find the version for 1.16.1 with curseforge's game version filtering.
https://www.curseforge.com/minecraft/mc-mods/optifabric/files/all?filter-game-version=2020709689%3A7892
As you can see, the latest version of optifabric (1.13.8) is compatible with 1.16.1.
