### ISSUE TITLE
Sodium compatibility issue

### ISSUE THREAD

**Issue by Atomibus** [Chocohead/OptiFabric#40]
![image](https://user-images.githubusercontent.com/50040354/92391310-149ae180-f125-11ea-84cd-a3fc844aa23d.png)

**Comment by Chocohead** [comment]
This is never going to work: Sodium replaces the renderer, OptiFine ~~replaces~~ heavily enhances the renderer. Given OptiFine doesn't have the patches split up for what they do (so there is no way to stop it changing the renderer), the only option would be for Sodium not to replace the renderer, at which point there is no reason to have it installed at all.
