### ISSUE TITLE
Optifabric wont detect optifine

### ISSUE THREAD

**Issue by DuskMC** [Chocohead/OptiFabric#400]
I used optifabric 1.11.20 and optifine HD_U_G_9 and I also tried with optifine HD_U_H1_pre7

**Comment by DuskMC** [comment]
i used fabric 0.11.17

**Comment by vCaliberz** [comment]
You need to actually run the optifine JAR file and install the mod into your folder. The Optifine file you have in your mods folder is most likely the installer. Good luck!

**Comment by ZekerZhayard** [comment]
same as #374

**Comment by DuskMC** [comment]
> You need to actually run the optifine JAR file and install the mod into your folder. The Optifine file you have in your mods folder is most likely the installer. Good luck!

Thanks for the advice!
I Will try, but i have already solved the problem but with optifine H5
