### ISSUE TITLE
Bug: Optifabric Incompatible with Fabric Loader 0.12.2

### ISSUE THREAD

**Issue by Kylebartaous** [Chocohead/OptiFabric#401]
Minecraft version:1.17.0
Fabric Loader version: 0.12.2
Fabric API version: 0.36.0-1.17
Optifabric version: 1.11.20
Optifine version: Preveiw_optifine_hd_ug9_pre26

Crash log: https://pastebin.com/trLWKwaP

![The error message](https://user-images.githubusercontent.com/11208209/137798735-ff6d1347-e3a3-475e-8e44-590046b93c4c.PNG)

Similar to these post:

#386
#394
#398

**Comment by vCaliberz** [comment]
Read your log, it tells you whats wrong. It says you need .8-.12 and you have .12.2, you are on 1.17 and not 1.17.1 which is the version you had downloaded for fabric. Please let me know if this helps!

**Comment by Kylebartaous** [comment]
I see now, thank you. My mistake on that, thinking that just updating & using the latest version would work, even if was just .2 versions ahead of what what mod can read as the version range it can use.
