### ISSUE TITLE
Found Conflicting Mod "lithium".

### ISSUE THREAD

**Issue by MrFreakOne** [Chocohead/OptiFabric#405]
Hello,

Translated into English with google.com.
I wanted to use Optifine, but you need "optifabric" so that it works under Fabric. I am not a computer expert or a professional. I got the following error message. I post that here, something else important, the game crashes and I keep getting this error message.

See You.

[latest.log](https://github.com/Chocohead/OptiFabric/files/7404838/latest.log)

**Comment by MacaylaMarvelous81** [comment]
The CaffeineMC mods are incompatible with Optifine and OptiFabric.

**Comment by MrFreakOne** [comment]
> 
> 
> The CaffeineMC mods are incompatible with Optifine and OptiFabric.


Hello,

"Translated into English with google.com".
many thanks for your response. This mod "CaffeineMC" is not included. It is the ModPack "All of Fabric 3 v2.8.5". Unfortunately I couldn't find a mod with this name "CaffeineMC".

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3

See You.

**Comment by MacaylaMarvelous81** [comment]
Hi! Sorry, I know I am very late, but [these](https://github.com/CaffeineMC) are what I mean by CaffeineMC mods. Lithium is a CaffeineMC mod.
