### ISSUE TITLE
not launching with fabric loader version 0.12.3 for 1.17.1

### ISSUE THREAD

**Issue by kann101** [Chocohead/OptiFabric#410]
Optifabric for 1.17.1 doesn't work with fabric loader 0.12.3. Minecraft launcher show me "exit code:0"

**Comment by 0xfeeddeadbeef** [comment]
Here's a modified version which works with fabric-loader 0.12.*:

[optifabric-1.11.20.jar](https://storage.googleapis.com/optifabric/optifabric-1.11.20.jar)

[VirusTotal scan results](https://www.virustotal.com/gui/file/69d14126249e858324f662d5d02a5d7f61ba16485174e87f4439ca221c9ff520)

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394
