### ISSUE TITLE
No Optifine Version found

### ISSUE THREAD

**Issue by xXLuKillerXx** [Chocohead/OptiFabric#414]
OptiFabric always give me the Error that ther is no Optifine Version in my Modsfolder. But ther is one, but its the pre Version. If i use the normal version everything works but the normal versin crashes with Texturepacks. How can i fix that?

**Comment by ZekerZhayard** [comment]
same as #374

**Comment by xXLuKillerXx** [comment]
Ohh thaks. Now its working fine :)
