### ISSUE TITLE
Optifabric doesn't launch in 1.17.1 READ !!!

### ISSUE THREAD

**Issue by Nikgm1** [Chocohead/OptiFabric#415]
This is the issue. NOTE i have everything working and ONLY when optifabric is in the mods folder this issue is present.

LAUNCH ERROR MSG:

net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.18 (C:\Users\User\AppData\Roaming\.minecraft\mods\optifabric-1.11.18.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.4!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.4 is being loaded from C:\Users\User\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.4\fabric-loader-0.12.4.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.18, reason: to remove
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b44633d, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57713, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.9+a722d8c013, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446313, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.12+6cefd57713, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab6121d5, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab61213d, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+198a96213d, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by iKarTehFox** [comment]
This error has to do with OptiFabric's incompatibility with Fabric loader versions >0.12.
Your best bet right now is to reinstall Fabric 0.11.7 and use OptiFine G9 and not the newer H version.

A [milestone](https://github.com/Chocohead/OptiFabric/milestone/2) has already been made, so keep your eyes peeled on that.

**Comment by thiagogebrimm** [comment]
Same

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394
