### ISSUE TITLE
Outdated Github redirection on OptiFabric error page

### ISSUE THREAD

**Issue by StayKwimp** [Chocohead/OptiFabric#420]
Hi there,

I was trying to make optifabric work with optifine H1 (which doesnt work for now i know) and I got this error screen. I clicked on the 'Open help' button which redirected me to the outdated modmuss50 optifabric page. What I suggest changing is making it redirect to this Github page.
It shouldn't be too hard to fix :)

![errorpage](https://user-images.githubusercontent.com/91032026/140549126-f84ca218-b6de-4662-9f13-c8cebad2e23e.png)

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/374

**Comment by Chocohead** [comment]
You're using a very old version if the buttons are using old links:
https://github.com/Chocohead/OptiFabric/blob/8044e8d0b2a83d6bb9b395c11ee17cefdbd75583/src/main/java/me/modmuss50/optifabric/mixin/MixinTitleScreen.java#L63-L81
