### ISSUE TITLE
OptiFabric 1.11.20 doesn't recognize OptiFine 1.17.1 H1

### ISSUE THREAD

**Issue by sapsicle** [Chocohead/OptiFabric#422]
Running Fabric with a couple mods and OptiFabric can't seem to find OptiFine 1.17.1 HD U H1 in the mods folder. 1.11.20 is the latest version of OptiFabric and I tried a couple different 1.17.1 versions of optifine, with H1 being the latest stable release but none worked.

Mods I'm running:
![image](https://user-images.githubusercontent.com/93958541/140847556-0ddda733-3acf-4386-bd90-4247943f8804.png)

Error:
![image](https://user-images.githubusercontent.com/93958541/140847769-f8f13ded-8281-4eb9-a1d8-5fcf29a29cf5.png)

**Comment by ThyDarkSorcerer** [comment]
The same issue is occurring for me.

**Comment by minhcrafters** [comment]
same for me
it only works for optifine g9 and older

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/374
