### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by icantthinkagoodnamesoiwhotethis** [Chocohead/OptiFabric#423]
![image_2021-11-09_205942](https://user-images.githubusercontent.com/93992528/140937429-3cacf327-bed1-46ff-939f-c0944f7c237a.png)
![Uploading image_2021-11-09_210001.png…]()

**Comment by Marvisbad** [comment]
If you used an optifine release from the H series than optifabric does not support it yet: https://github.com/Chocohead/OptiFabric/milestones

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/374
