### ISSUE TITLE
Crashes when running the Mubble mod.

### ISSUE THREAD

**Issue by KirbyKid256** [Chocohead/OptiFabric#43]
Optifabric causes my game to crash whenever I try to run the Mubble mod by Hugman_76. The Dawn API works, but Mubble doesn't. Oh also, while I'm here, it also crashes when I try to use the GUD FPS mod.

**Comment by Trirez** [comment]
Gud FPS mod conflicts with optifine. Only one should be used like sodium or optifine.

**Comment by 0xfeeddeadbeef** [comment]
Dawn Team recently updated their addons (Mubble, DawnAPI, WildExplorer, NookBuild) and as a result this crash is back.

No crash report or log entries, process dies instantly.

/cc @Chocohead

**Comment by Chocohead** [comment]
They've moved the problematic Mixin from Mubble to DawnAPI. Think the fix will still apply, it just needs to target a different class
