### ISSUE TITLE
optifabric won't work with 1.17.1

### ISSUE THREAD

**Issue by Shizzins** [Chocohead/OptiFabric#435]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (C:\Users\user\AppData\Roaming\.minecraft\mods\optifabric-1.11.20.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\user\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.20, reason: to remove
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57713, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.9+a722d8c013, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446313, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.12+6cefd57713, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b18, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://user-images.githubusercontent.com/74148456/141524555-8eb43c0e-eb37-418b-8cb6-d14dd363d882.png)
mods folder

**Comment by Andariel78** [comment]
Hi problem is fabric 0.12.5 as described here:

https://github.com/Chocohead/OptiFabric/issues/428

Still waiting for fix. Fastest way: use fabric 0.12.0 ;)

**Comment by ZekerZhayard** [comment]
same as #394

**Comment by CubiBox** [comment]
If you are using OptiFine_1.17.1_HD_U_G9, it works

**Comment by benjia0605** [comment]
[SOLVED]
The issue is the fabric installer, if you delete the 12.5 ver. of the fabric installer and install version 11.5 (this is the version that I installed to make the mod compatible), the mod will work. Be sure to delete the other installer version and select the correct version when you open up the Minecraft launcher. Hope this helps!

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7 
Use Optifine HD U G9
