### ISSUE TITLE
Fabric Server error

### ISSUE THREAD

**Issue by ltecheroffical** [Chocohead/OptiFabric#437]
I have a fabric server and have my custom mod in the mods folder and when with the mod I start the server then I get a error does anyone know why?

error info:
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br/>at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)<br/>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>at java.base/java.lang.reflect.Method.invoke(Method.java:567)<br/>at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)<br/>at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)<br/>at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)</html>

**Comment by VidTu** [comment]
AFAIK OptiFabric and OptiFine are clientside mods

**Comment by Chocohead** [comment]
The compatibility error will be just above what you've posted, but as mentioned OptiFine is solely clientside so there is no reason to include it on a server
