### ISSUE TITLE
Time to compile using the latest fabricmc version.

### ISSUE THREAD

**Issue by dryter97** [Chocohead/OptiFabric#440]
Simply incompatible using above 0.12

should be updated to follow at least requirement for the latest fabric version. 
anyway its going to be needed using the G9 of optifine and soon the 1.18 minecraft version

**Comment by dryter97** [comment]
![image](https://user-images.githubusercontent.com/16638986/141689975-92baccfa-1ee4-45e3-a1fb-090932694832.png)

**Comment by Ynaught** [comment]
Agreed. Worse part is, I don't even want it for the shaders. I just want it to make the Fresh Animations resource pack to work, but I have a mod ("roughly searchable") that requires fabric loader 0.12.0 or higher, which unlucky for me, is the first version above the cap that optifabric doesn't support.

**Comment by ZekerZhayard** [comment]
same as #394
