### ISSUE TITLE
Error while opening minecraft

### ISSUE THREAD

**Issue by TrueTheos** [Chocohead/OptiFabric#441]
![image](https://user-images.githubusercontent.com/26145867/141700865-494edac3-ea3e-4911-abf1-b248954cacd4.png)

Got this error ^. 
I have these files in my /mods folder

![image](https://user-images.githubusercontent.com/26145867/141700899-ae401437-c885-4e9e-9edc-ddf2657f4a17.png)

What am I missing/doing wrong?

**Comment by ZekerZhayard** [comment]
same as #394

**Comment by TrueTheos** [comment]
> same as #394

Okay, but still can't find the solution.

**Comment by SuryaRajgor** [comment]
your MC version is 1.16.4 ?

and which version of fabric loader are you using?

**Comment by srajanplshelpme** [comment]
same help

**Comment by srajanplshelpme** [comment]
i am using 1.16.3 version mc and fabric loader
