### ISSUE TITLE
Optifabric doesn't work with Fabric Loader 1.12.5

### ISSUE THREAD

**Issue by Lyraedan** [Chocohead/OptiFabric#443]
I tried using the latest version of Fabric for version 1.17.1 with this mod and it straight out refused to load.
Solution was stated as "Remove Optifabric"

**Comment by ZekerZhayard** [comment]
same as #394

**Comment by ImOliTheFrog** [comment]
a way to fix this, is by running version 11.7. anything above that won't work for now.

**Comment by amarisa4321** [comment]
But if you use that version you can't play with other mods that need fabric more up to date.

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7 
Use Optifine HD U G9
