### ISSUE TITLE
OptiFabric does not work

### ISSUE THREAD

**Issue by OriginQ8** [Chocohead/OptiFabric#444]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (C:\Users\user\AppData\Roaming\.minecraft\mods\optifabric-1.11.20 (6).jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\user\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.20, reason: to remove
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446318, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.4+a02b446318, reason: newer version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.2+36b77c3e18, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.12+6cefd57718, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.2+92519afa18, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b18, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Unkrown6YT** [comment]
bug

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7 
Use Optifine HD U G9

**Comment by OriginQ8** [comment]
thank you 
its work finally
