### ISSUE TITLE
Optifine Issue...

### ISSUE THREAD

**Issue by Sonnyyyyyyyyy** [Chocohead/OptiFabric#448]
When i load minecraft with optifabric and optifine it says it cant find optifine jar

**Comment by Sonnyyyyyyyyy** [comment]
anyone know a fix?

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7 
Use Optifine HD U G9
