### ISSUE TITLE
optifabric wont work

### ISSUE THREAD

**Issue by Caidennn7** [Chocohead/OptiFabric#449]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (C:\Users\caide\AppData\Roaming\.minecraft\mods\optifabric-1.11.20.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12.2 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\caide\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
	 - Mod 'Sodium' (sodium) is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.11.20!
		 - Mod 'OptiFabric' (optifabric) 1.11.20 is being loaded from C:\Users\caide\AppData\Roaming\.minecraft\mods\optifabric-1.11.20.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.20, reason: to remove
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b44633d, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.1.5+a02b446313, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.13+a02b446313, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab612113, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab61213d, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+198a96213d, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: incompatible
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7 
Use Optifine HD U G9
