### ISSUE TITLE
Where is Chocohead? (Fabric 0.12+ Issue)

### ISSUE THREAD

**Issue by Mathew322** [Chocohead/OptiFabric#450]
This probably isn't the best way to do this but yeah I'm having the same issue that everyone else if having with Optifabric not working with anything above Fabric 0.11.7 or OptiFine 1.17.1 HD U H1 pre1.
![Screenshot 2021-11-18 16 51 55](https://user-images.githubusercontent.com/38450575/142503040-08a4802a-2f4a-419d-93fa-f2d2cb97c9ba.png)
Chocohead hasn't made any contributions all November and I'm sure they have their own reasons for that, but at this rate someone else might want to Fork, Update, and Maintain a new Optifabric release on CurseForge.

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine 
Use Optifine HD U G9

**Comment by Mathew322** [comment]
> Its because Optifabric Is Not Updated So it does not work With New Fabric Version or New Optifine Use Optifine HD U G9

I literally said that in my post, obviously it doesn't work cause Optifabric isn't updated. Also why would I move to Optifine HD U G9 when OptiFine 1.17.1 HD U H1 pre1 is compatible? Isn't H1 pre1 newer?

**Comment by SuryaRajgor** [comment]
yes, I know what you say and I tried all versions of both so I just confirm that what you say so you don't waste your time to find a solution and just wait for an update. OptiFine 1.17.1 HD U H1 does not work and if you want to use then downgrade to U G9 otherwise remove optifabric and wait to update

**Comment by Mathew322** [comment]
Well no OptiFine 1.17.1 HD U H1 doesn't work, but preview version OptiFine 1.17.1 HD U H1 pre1 does work, it's the last update of OptiFine that OptiFabric registers compatibility with.

**Comment by SuryaRajgor** [comment]
oh now I read correctly it's my bad  H1 pre1 ,, I think H2 Pre1

**Comment by Mathew322** [comment]
It would appear Chocohead made some contributions yesterday so hopefully they get to Optifabric soon.
![Screenshot 2021-11-20 at 22-56-08 Chocohead - Overview](https://user-images.githubusercontent.com/38450575/142748976-5a191071-db8f-4da3-aa45-047c6ffe4915.png)
If you see this post Chocohead, I hope you don't take this issue as criticism, I definitely can't code so I really appreciate you taking your time to maintain this mod!

**Comment by Chocohead** [comment]
OptiFabric has always been worked on with a "when I have time" basis, given it can sometimes require quite a lot to fix some of the issues. It is open source so anyone who can help is welcome to make pull requests/suggestions, for those who can't just reporting bugs/compatibility problems as you find them and being patient is good enough for me ;)
