### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Whispity** [Chocohead/OptiFabric#451]
Im launching this so that i can have optifine and replay together yet it fails to launch and gets this error message, ill include the mods folder too
![Screenshot 2021-11-19 102620](https://user-images.githubusercontent.com/94654225/142513003-a502904d-5cb8-4042-8157-59ce35f632fa.png)
![Screenshot 2021-11-19 103018](https://user-images.githubusercontent.com/94654225/142513040-f0352956-e19c-4930-a886-0e40620df65f.png)

**Comment by SuryaRajgor** [comment]
Its because Optifabric Is Not Updated So its not work With New Fabric Version 

Go To Minecraft Folder then Versions and Delete Fabric 0.12.5
install Fabric With 0.11.7
