### ISSUE TITLE
Crashes when pressing "options" button

### ISSUE THREAD

**Issue by dbrighthd** [Chocohead/OptiFabric#455]
Welcome back chocohead, im happy to see the new version of optifabric released!

when I tried to run the game (with only this in my mods folder)

![image](https://user-images.githubusercontent.com/68525639/142786613-e7f163af-3a7b-4f8e-838a-d7175ba8352b.png)

the game crashed giving me this on the launcher:

The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_446 failed
Exit Code: -1

**Comment by dbrighthd** [comment]
this also shows up in logs

![image](https://user-images.githubusercontent.com/68525639/142786653-bed9c28e-465c-4d06-b98e-353a24839e56.png)

**Comment by majjestro** [comment]
I have the same problem.

**Comment by NaiNonTH** [comment]
Same here
