### ISSUE TITLE
Crash when navigating to options

### ISSUE THREAD

**Issue by valentinegb** [Chocohead/OptiFabric#456]
https://user-images.githubusercontent.com/35977727/142787148-68517504-1e46-4704-a3b8-f8beef233f4f.mp4

Sorry to make another issue so quickly after the last one (thanks for your help with the last one though!)

## Steps to Reproduce
1. Start Minecraft with specs detailed below.
2. Click "Options".
3. Minecraft shows "Saving world".
4. Minecraft crashes.

## Specs
**Minecraft:** 1.17.1
**Fabric Loader:** 0.12.5
**OptiFabric:** 1.12.0
**Mods:**
![image](https://user-images.githubusercontent.com/35977727/142786560-8b7d290c-7ef8-4b34-9c42-25859bae52d5.png)
**Windows 11 Pro:** 21H2 (22000.318)

**Comment by dbrighthd** [comment]
Im having the same issue on windows 10 (#455)
