### ISSUE TITLE
Minecraft Crashes opening Chat or Options

### ISSUE THREAD

**Issue by Mathew322** [Chocohead/OptiFabric#457]
As much as I appreciate seeing Optifabric updated, I regretfully have to report a crashing issue. Mod combinations I've run that have resulted in a crash when pressing T to open chat or opening the Options menu are:

Optifabric-1.12.0
OptiFine HD U H2 pre1
Fabric Loader 12.5

Optifabric-1.12.0
OptiFine HD U H1
Fabric Loader 12.5

Optifabric-1.12.0
OptiFine HD U H1
Fabric Loader 12.0

**Comment by AngelofWoe** [comment]
I just came here to report this bug. I have the same problem with the same mods.

**Comment by thiagogebrimm** [comment]
Same problem
