### ISSUE TITLE
mc crashes when clicking options there seems to be a problem crash logs here  https://pastebin.com/uYEjtknD

### ISSUE THREAD

**Issue by DarkBlox666** [Chocohead/OptiFabric#458]
I use optifabric replay mod optifine all in the latesnt update n in 1.17.1

**Comment by DarkBlox666** [comment]
it seems to give my a crash log
when i click options

**Comment by DarkBlox666** [comment]
i use optifabric replay optifine n the fabric luancher all latest update n in 1.17.1

**Comment by DarkBlox666** [comment]
https://pastebin.com/uYEjtknD

**Comment by JaclyNolan** [comment]
I got the same exact problem as well. https://pastebin.com/yCaKpC09
