### ISSUE TITLE
Incompatibility with MoEnchants mod for fabric.

### ISSUE THREAD

**Issue by JoSo1997** [Chocohead/OptiFabric#46]
When I try to open my Minecraft Game with this mod the game crashes and I think that this is the only mod that has an issue.

**Comment by 0xfeeddeadbeef** [comment]
@JoSo1997  See #37 and [the issue](https://gitlab.com/biom4st3r/moenchantments/-/issues/37) in official repository.

**Comment by JoSo1997** [comment]
> @JoSo1997 See #37 and [the issue](https://gitlab.com/biom4st3r/moenchantments/-/issues/37) in official repository.

Ohh, thank you :D
