### ISSUE TITLE
Minecraft is stuck at 100% when loading any world.

### ISSUE THREAD

**Issue by music-cat-bread** [Chocohead/OptiFabric#464]
When try to open any world using OptiFabric and Optifine it get frozen at 100%, but window is resizing correctly.

Game version: 1.17.1
Fabric Version: 0.12.5 - 1.17.1
OptiFabric Version: 1.12.2 (this is not the game version)
OptiFine Version: 1.17.1_HD_U_G9
Fabric API Versoin 0.43.0+1.17

Other mods:
mod_menu (for 1.17.1)
replaymod-1.17.1-2.6.1
NOTE: I tested it without additional mods but the result is still the same.

Log:
Log have over 410000 lines so I am uploading it to mediafire.
[Link](https://www.mediafire.com/file/ib120ux604s6tua/latest.log/file)

**Comment by Chocohead** [comment]
Looks like the newest Fabric API has a new conflict:

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onChunkUnload(IILnet/minecraft/class_4548;Lnet/minecraft/class_2540;Lnet/minecraft/class_2487;Ljava/util/BitSet;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ILnet/minecraft/class_2818;Lnet/minecraft/class_1923;)V in fabric-lifecycle-events-v1.mixins.json:client.ClientChunkManagerMixin from mod fabric-lifecycle-events-v1 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-lifecycle-events-v1-refmap.json

Should be easy enough to fix...
