### ISSUE TITLE
Crash: "Tesselating liquid in world"

### ISSUE THREAD

**Issue by f1refa11** [Chocohead/OptiFabric#468]
Mods im using:
- Optifabric
- Replay Mod
- Fabric API
Log: https://pastebin.com/fwjQ3Hgn

**Comment by Domthewiz** [comment]
Same problem

**Comment by f1refa11** [comment]
I solved the problem by deleting all mods i used(including optifabric, replay mod and fabric api) and reinstalling their last version

**Comment by Chocohead** [comment]
If anyone else gets this crash it's a result of using a narrow range of broken Fabric API versions, updating it should fix it
