### ISSUE TITLE
Optifabric 1.12.6 does not work with 1.18 snapshots

### ISSUE THREAD

**Issue by Dracconis** [Chocohead/OptiFabric#473]
Looking through the fabric site at optifabric and ensuring I wasn't going crazy, optifabric 1.12.6 lists the working versions of MC as 1.16+, 1.17+, and 1.18-snapshot as seen here in the description: https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3538275 . IF this is not the case then shouldn't the "1.18-snapshot" tag be removed?

**Comment by Cron1ca** [comment]
same thing here, I have been trying to find a fix for like 30 minutes :/

**Comment by FranklinShack** [comment]
The version wasn't updated in fabric.mod.json

**Comment by CuboidRaptor** [comment]
yeah, might not have been updated, I can fix that ig let's see if it works with modified manifest

**Comment by CuboidRaptor** [comment]
ok but OptiFIne doesn't work with 1.18 yet

**Comment by FranklinShack** [comment]
There is a prerelease, not sure if it works with the full release just yet

**Comment by CuboidRaptor** [comment]
OptiFabric might work, but OptiFine hasn't been updated for the full release so there'd be no point even if it worked.

**Comment by Dracconis** [comment]
Not everyone is playing FR of 1.18 and are still playing on the snapshots where both OF's will work. So fixing it isn't necessarily a bad thing.

**Comment by CuboidRaptor** [comment]
ah ok lemme try maybe test it on snapshot and if it works I can pull request or something

**Comment by CuboidRaptor** [comment]
I'm confused, when I run Optifine for 1.18 it says I have to use 1.18-rc4, when I run in 1.18-rc4 it says I have to run in 1.18 wha!???!?!????

**Comment by Chocohead** [comment]
OptiFabric works for a single 1.18 snapshot, 1.18-pre1, just like OptiFine:
![2021-11-25_22 50 20](https://user-images.githubusercontent.com/4021725/144332756-8fde5e95-cc58-49eb-b113-1bd359b5baea.png)
Unfortunately Curse doesn't have any more granular version selection for snapshots other than any or none.

**Comment by Dracconis** [comment]
So this won't be fixed to use with the snapshots then?

**Comment by Chocohead** [comment]
I don't see what else there is to fix, OptiFabric already supports everything OptiFine itself does. Maybe if you particularly wanted a different snapshot (to 1.18-pre1) working, but now 1.18 is released it seems a bit moot.

**Comment by Dracconis** [comment]
I was just curious. I started a world on 43a and just wasn't in a hurry to update it to the 1.18 FR

**Comment by Chocohead** [comment]
For what it's worth there were plans to try keep up with early 1.15 snapshots to prove it could be done, but 19w34a changed too much too quickly so it didn't really work out. Attempting to go beyond what an OptiFine version is designed for requires effectively updating OptiFine either through guessing what to change based on the binary patches or maintaining patches/mixins to sit on top of OptiFine to add the vanilla changes back.

Your case is certainly possible if you were inclined, 21w43a is only two snapshots back after all from 1.18-pre1, but it would very much take an active effort to do so (and would almost certainly be more than anything as simple as adding `1.18-alpha.21.43.a` to the `fabric.mod.json`).
