### ISSUE TITLE
Minecraft 1.18 crashes while using Optifabric with fabric-api

### ISSUE THREAD

**Issue by Kelpou** [Chocohead/OptiFabric#480]
It is possible to run Minecraft but, as mentioned above, if i try to enter a world MC crashes. 
I tryed only optifabric and it worked with a shader but i also want to install Xaero's wolrd and minimap so fabric-api is necessary.
Does anyone else have a problem like this or a recommendation how to fix it?

The versions im using are:
Fabric-api: 0.43.1+1.19
Optifabric: 1.12.6
OptiFine: preview_OptFine_1.18_HD_U_H3_pre4

**Comment by grimmyxx** [comment]
i had the same issue yesterday, the only fix that i found, until optifabric gets updated, is to not use any other additional mods other than optifabric and optifine itself

**Comment by fftop95** [comment]
gdfgfdgf

**Comment by fftop95** [comment]
fgfgdfgfg

**Comment by fftop95** [comment]
fgfgf

**Comment by juliocoliveira** [comment]
Same issue, modified the jar to load 1.18 but it crashes when loading the world, Here is my Log: (https://pastebin.com/bbgHBdga)
I can't play without a map mod so i'll have to wait until Optifabric is updated.

**Comment by TwoPointInfinity** [comment]
Yup Yup Yup Yup Yup Yup  came to say the same thing. 

```
Unmet dependency listing:
Mod 'OptiFabric' (optifabric) 1.12.6 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1 or version 1.18-beta.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18!

```
