### ISSUE TITLE
optifabric shaders problems 

### ISSUE THREAD

**Issue by Mitpatel2003** [Chocohead/OptiFabric#49]
so every time I load up shaders and go out the menu i see this 

![2020-09-13_21 09 26](https://user-images.githubusercontent.com/61388531/93035688-b0d45500-f60b-11ea-9ae0-319e92846269.png)
![2020-09-13_19 51 40](https://user-images.githubusercontent.com/61388531/93035682-ae71fb00-f60b-11ea-8a5a-96ed6935f43b.png)
![2020-09-13_19 51 35](https://user-images.githubusercontent.com/61388531/93035683-ae71fb00-f60b-11ea-8876-dd15df1f376e.png)
![2020-09-13_21 08 11](https://user-images.githubusercontent.com/61388531/93035684-af0a9180-f60b-11ea-95ec-22de276c0a50.png)

I dont know how to fix it and i dont know how it happened it never did this before I dont know if i did something to mess with it or if it just happened its self but I hope I can get help to fix it.

**Comment by IMS212** [comment]
can you test this on normal optifine / not Optifabric, to confirm this is an Optifabric issue?
