### ISSUE TITLE
Crash 1.18 

### ISSUE THREAD

**Issue by WolverStones** [Chocohead/OptiFabric#490]
https://paste.ee/p/nVO8p

Java is version 17.0.1, using 64-bit architecture, from Azul Systems, Inc..

preview_OptiFine_1.18_HD_U_H3_pre6
optifabric-1.12.7

**Comment by SparkdotIe** [comment]
I've been getting the same, ish Issue, the game goes to start but crashes with a code 1. It doesn't do it when I have two different optifine installations on, but of course that causes problems of its own.

https://pastebin.com/5D7q9DQA

I'm on 1.18
CurseForge launcher
running fabric 0.12.8
Optifabric 1.12.7
Optifine preview_OptiFine_1.18_HD_U_H3_pre6, 5 and 4 also have this problem, didn't check with previous versions tho

Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM	8.00 GB (7.84 GB usable)
System type	64-bit operating system, x64-based processor

 with
 
 Edition	Windows 10 Home
Version	20H2
OS build	19042.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

Using Java 8 Update 311 (build 1.8.0_311-b11)

Other mods include:
Architectury API (Fabric)
BetterF3
Damage Tilt
Fabric API
WTHIT (What the hell is that)
AppleSkin
Armor Sound Tweak
Beenfo
BerdinskiyBear's Armor HUD
Better Mount HUD
Better Third Person
CameraOverhaul
Carpet
Carpet Extra
Chat Heads
Chunky Pregenerator (Fabric)
Cloth API (Fabric)
Cloth Config API (Fabric)
CraftPresence
Custom Stars [Fabric]
Customizable Player Models (Fabric)
Dark Loading Screen
DefaultSettings Fabric
Dynamic FPS
Dynamic Sound Filters
EasierVillagerTrading
Eating Animation [Fabric]
Entity Culling Fabric/Forge
FancyMenu [Fabric]
First-person Model (Forge/Fabric)
FPS Monitor
Illuminations 🔥
Inventory Control Tweaks
Inventory Profiles Next
Item Scroller
Konkrete [Fabric]
Light Overlay (Rift/Forge/Fabric)
MaLiLib
Mod Menu
Name Pain
Not Enough Animations (Forge/Fabric)
Pling
Presence Footsteps
Replanter
Roughly Enough Items Fabric (REI)
Skin Layers 3D (Fabric/Forge)
SlotLock
ToolTipFix
Xaero's Minimap
Xaero's World Map

**Comment by CHLOzzz** [comment]
> I've been getting the same, ish Issue, the game goes to start but crashes with a code 1. It doesn't do it when I have two different optifine installations on, but of course that causes problems of its own.
> 
> https://pastebin.com/5D7q9DQA
> 
> I'm on 1.18 CurseForge launcher running fabric 0.12.8 Optifabric 1.12.7 Optifine preview_OptiFine_1.18_HD_U_H3_pre6, 5 and 4 also have this problem, didn't check with previous versions tho
> 
> Processor Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz 2.40 GHz Installed RAM 8.00 GB (7.84 GB usable) System type 64-bit operating system, x64-based processor
> 
> with
> 
> Edition Windows 10 Home Version 20H2 OS build 19042.1348 Experience Windows Feature Experience Pack 120.2212.3920.0
> 
> Using Java 8 Update 311 (build 1.8.0_311-b11)
> 
> Other mods include: Architectury API (Fabric) BetterF3 Damage Tilt Fabric API WTHIT (What the hell is that) AppleSkin Armor Sound Tweak Beenfo BerdinskiyBear's Armor HUD Better Mount HUD Better Third Person CameraOverhaul Carpet Carpet Extra Chat Heads Chunky Pregenerator (Fabric) Cloth API (Fabric) Cloth Config API (Fabric) CraftPresence Custom Stars [Fabric] Customizable Player Models (Fabric) Dark Loading Screen DefaultSettings Fabric Dynamic FPS Dynamic Sound Filters EasierVillagerTrading Eating Animation [Fabric] Entity Culling Fabric/Forge FancyMenu [Fabric] First-person Model (Forge/Fabric) FPS Monitor Illuminations 🔥 Inventory Control Tweaks Inventory Profiles Next Item Scroller Konkrete [Fabric] Light Overlay (Rift/Forge/Fabric) MaLiLib Mod Menu Name Pain Not Enough Animations (Forge/Fabric) Pling Presence Footsteps Replanter Roughly Enough Items Fabric (REI) Skin Layers 3D (Fabric/Forge) SlotLock ToolTipFix Xaero's Minimap Xaero's World Map

Hey, I'm just a random and not a dev, but reading the error, it seems this mod isn't for 1.18 release but for 1,18-pre1; at the very least that is my issue. I'm just waiting until they release 1.12.8 (or later) before I bother trying to run the mod again on 1.18 release. Luckily, the devs seem pretty active.

**Comment by SparkdotIe** [comment]
> > I've been getting the same, ish Issue, the game goes to start but crashes with a code 1. It doesn't do it when I have two different optifine installations on, but of course that causes problems of its own.
> > https://pastebin.com/5D7q9DQA
> > I'm on 1.18 CurseForge launcher running fabric 0.12.8 Optifabric 1.12.7 Optifine preview_OptiFine_1.18_HD_U_H3_pre6, 5 and 4 also have this problem, didn't check with previous versions tho
> > Processor Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz 2.40 GHz Installed RAM 8.00 GB (7.84 GB usable) System type 64-bit operating system, x64-based processor
> > with
> > Edition Windows 10 Home Version 20H2 OS build 19042.1348 Experience Windows Feature Experience Pack 120.2212.3920.0
> > Using Java 8 Update 311 (build 1.8.0_311-b11)
> > Other mods include: Architectury API (Fabric) BetterF3 Damage Tilt Fabric API WTHIT (What the hell is that) AppleSkin Armor Sound Tweak Beenfo BerdinskiyBear's Armor HUD Better Mount HUD Better Third Person CameraOverhaul Carpet Carpet Extra Chat Heads Chunky Pregenerator (Fabric) Cloth API (Fabric) Cloth Config API (Fabric) CraftPresence Custom Stars [Fabric] Customizable Player Models (Fabric) Dark Loading Screen DefaultSettings Fabric Dynamic FPS Dynamic Sound Filters EasierVillagerTrading Eating Animation [Fabric] Entity Culling Fabric/Forge FancyMenu [Fabric] First-person Model (Forge/Fabric) FPS Monitor Illuminations 🔥 Inventory Control Tweaks Inventory Profiles Next Item Scroller Konkrete [Fabric] Light Overlay (Rift/Forge/Fabric) MaLiLib Mod Menu Name Pain Not Enough Animations (Forge/Fabric) Pling Presence Footsteps Replanter Roughly Enough Items Fabric (REI) Skin Layers 3D (Fabric/Forge) SlotLock ToolTipFix Xaero's Minimap Xaero's World Map
> 
> Hey, I'm just a random and not a dev, but reading the error, it seems this mod isn't for 1.18 release but for 1,18-pre1; at the very least that is my issue. I'm just waiting until they release 1.12.8 (or later) before I bother trying to run the mod again on 1.18 release. Luckily, the devs seem pretty active.

Ah, yeah that'd make sense... I'm not that knowledgeable when it comes to this kinda stuff so I guess I kinda missed that it wasn't for 1.18, either way, hope an update comes soon... I'm fine with using sodium but damn I want my optifine

**Comment by WolverStones** [comment]
After update to OptiFine 1.18_HD_U_H3_pre7 is working for me
