### ISSUE TITLE
optifabric and fabric api

### ISSUE THREAD

**Issue by Turtle418** [Chocohead/OptiFabric#493]
It crashes with fabric api, optifabric, and optifine pre8, but if I take fabric api out it works.

**Comment by DrSNAFU** [comment]
I'm having the same issue: Fabric loader 12.8, fabric-api-0.44.0+1.18, optifabric-1.12.7, preview_OptiFine_1.18_HD_U_H3_pre8

I can only get minecraft to work if I either remove fabric-api entirely, or downgrade to optifine pre7.  Including log.

[crash-2021-12-05_18.50.23-client.txt](https://github.com/Chocohead/OptiFabric/files/7657230/crash-2021-12-05_18.50.23-client.txt)

**Comment by juliocoliveira** [comment]
Indeed, I'm having the same issue, And using pre7 works just fine, you can get pre7 here (https://github.com/Chocohead/OptiFabric/files/7664165/preview_OptiFine_1.18_HD_U_H3_pre7.zip)
