### ISSUE TITLE
Crash when using the OptiFine_1.18_HD_U_H3

### ISSUE THREAD

**Issue by CormacZ** [Chocohead/OptiFabric#499]

**Comment by Brixkee** [comment]
Yes I also had the same problem with the 2 preview versions of optifine 1.18

**Comment by juliocoliveira** [comment]
Me too, i can confirm that standalone optifine works fine.
And that any preview up to pre7 works fine too.

**Comment by Lou9896** [comment]
For me preview_OptiFine_1.18_HD_U_H3_pre7.jar works just fine with optifabric-1.12.7, but OptiFine_1.18_HD_U_H3.jar causes the gam to crash when opening a world or joining a server.

**Comment by monpjc** [comment]
Can confirm will work with preview ok however when opening world and generating view will crash out.

**Comment by MyrddinN** [comment]
Can confirm this happens with me since pre 6 (here is the crash log from my recent crash)
[crash-2021-12-07_20.03.36-client.txt](https://github.com/Chocohead/OptiFabric/files/7670986/crash-2021-12-07_20.03.36-client.txt)
re

**Comment by BadMapper** [comment]
both preview and normal crash for optifabric, was working a couple of days ago mustve been a change on optifines end.

**Comment by juliocoliveira** [comment]
> both preview and normal crash for optifabric, was working a couple of days ago mustve been a change on optifines end.

Try pre7, its working fine for me

**Comment by tameableflame** [comment]
Personally, the game works fine with Optifabric and non-API mods, but it results in a crash when you use OptiFine with Fabric API and Fabric API mods

**Comment by Nuanulla** [comment]
Can confirm.
1. Loading OptiFabric with OptiFine H3 works fine if both .jar files are the only ones in the mods folder
2. Loading OptiFabric, OptiFine H3, and Fabric API 0.44 crashes the game on loading a saved world.

**Comment by SleepyTonia** [comment]
Using `preview_OptiFine_1.18_HD_U_H3_pre7` also does fix this for me.

**Comment by edbarbera** [comment]
Can confirm using `pre7` version of Optifine has fixed this. That's with other mods and single/multiplayer. 👍

**Comment by Scoooolzs** [comment]
i am using `pre7` is didn't work for me
