### ISSUE TITLE
Update for 1.16.3

### ISSUE THREAD

**Issue by ftrocchi** [Chocohead/OptiFabric#50]
Title says it all.  Thanks!

**Comment by Ludi87** [comment]
Theres a pull request for it, so probably just a matter of time :) Be patient :D

**Comment by ThexXTURBOXx** [comment]
In the pull request, there is also instructions on how to get the mod for 1.16.3: https://github.com/Chocohead/OptiFabric/pull/48#issuecomment-693627211

**Comment by Chocohead** [comment]
This is available [on Curse](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3060791) now.
