### ISSUE TITLE
Crash with Replay mod 1.18+

### ISSUE THREAD

**Issue by Assassinater206** [Chocohead/OptiFabric#507]
Whenever I launch mc it crashes....
Cause,Replay mod,optifine & optifabric

**Comment by StarWolfProtogen** [comment]
no other mods for now

**Comment by juliocoliveira** [comment]
Use pre7 release of optifine, should work.

**Comment by Frumpy9** [comment]
> Use pre7 release of optifine, should work.

Without OptiFabric? I thought it wouldn't work because OF isn't updated to 1.18.1

**Comment by Assassinater206** [comment]
> Use pre7 release of optifine, should work.

It didn't though
