### ISSUE TITLE
Optifabric 1.18 crashes

### ISSUE THREAD

**Issue by PunchTRK** [Chocohead/OptiFabric#512]
So the problem is whenever the % gets to 100 while opening a world it just says saving world and then game crashes. Exit Code:-1

**Comment by ghost** [comment]
I have the same issue, I was running other mods when this crash report was taken, but I have also tried it with only Optifine, Optifabric, and Fabric API, and still get the same error.

https://pastebin.com/qsUK6b2m

**Comment by INFINI7I** [comment]
Use OptiFine_1.18_HD_U_H3_pre5
I have same trouble too. On pre6 and higher Minecraft crushes when loading the world
https://github.com/Chocohead/OptiFabric/files/7662272/OptiFine.zip

**Comment by HeroGamesDz** [comment]
Same issue here. Exit Code: -1
