### ISSUE TITLE
OptiFabric-v1.12.7 issues towards 1.18.0

### ISSUE THREAD

**Issue by abelblue3** [Chocohead/OptiFabric#518]
I recognize that when I launch 1.18.0 Fabric in MC Launcher, it crashes instantly without giving the logs to the issues the mods file may have. This is one issue I would like to note.

Another issue is how OptiFabric-v1.12.7 was reported to not work (or be compatible) to MC version 1.18.1. I don't know whether if this OptiFabric version suppose to be supported for 1.18.1, but if it's the case, can you fix or create an OptiFabric version especially for 1.18.0/1.18.1+?

**Comment by danrtz** [comment]
To use OptiFabric with 1.18.0, you must use OptiFine HD U H3 pre7. 1.18.1 does not work regardless.
