### ISSUE TITLE
Letters won't show up at all (1.16.1)

### ISSUE THREAD

**Issue by InsaanNotFound** [Chocohead/OptiFabric#52]
![2020-09-19_13 18 21](https://user-images.githubusercontent.com/69729089/93666196-68d68780-fa7c-11ea-8de0-6bcbd2b0878b.png)

**Comment by Wolfieheart** [comment]
First thing to ask:

What other mods other than Optifine and Optifabric are you using (if any)?

**Comment by InsaanNotFound** [comment]
Yes, but way too many to list. I could send error report here, when i get home

**Comment by IMS212** [comment]
Does this issue occur with no mods other than optifabric and optifine?

**Comment by Chocohead** [comment]
This will certainly be an incompatibility from another mod, without a list at least (or better narrowing it down to which one it is) there's not really anything that can be done for this.
