### ISSUE TITLE
Optifabric + Minecraft 1.18.1 + Replay mod

### ISSUE THREAD

**Issue by Xlawi** [Chocohead/OptiFabric#520]
Hey, i wanna use optifine, fabric, and replay mod. But Optifabric didn't work, i read #511 , optifine work without replay mod. My mods is Modmenu, optifabric, optifine, and replay mod. (Modmenu didn't give problems, i test him before)

**Comment by ChromesDuzez** [comment]
currently, optifabric does not work on 1.18.1 with the fabric API so the replay mod won't work yet cuz the replay mod requires the fabric API

**Comment by thecreare** [comment]
"replay mod won't work yet cuz the replay mod requires the fabric API"
I can run replay mod on fabric without fabric API
and I can run optifabric with the fabric api


(x = its enabled)


This config works

Fabric API [X]
Optifabric [X]
OptiFine [X]
Replay Mod [ ]

This config works

Fabric API [ ]
Optifabric [ ]
OptiFine [ ]
Replay Mod [X]

This config DOSENT work

Fabric API [X]
Optifabric [X]
OptiFine [X]
Replay Mod [ X]

EDIT
I am using MultiMC 5
And I loaded fabric into a version
So might fabric api just exist in there even though I dont have it put in the loader mods?

**Comment by ChromesDuzez** [comment]
^I have this same issue

**Comment by IceMan70mc** [comment]
same problem here.
OptiFabric + Fabric-API without replaymod = load the game
replaymod  + Fabric-API without OptiFabric = load the game
but OptiFabric + replaymod = crash while loading
