### ISSUE TITLE
Not working with Fabric API 1.18.1

### ISSUE THREAD

**Issue by Rippedbird** [Chocohead/OptiFabric#525]
I thought the update would fix it but it still is not working, It just crashes my game the instant I press play. If I take Fabric API and the mods that use it out it works fine. But I need these mods to play. Anyone know anything?

**Comment by R00tB33rMan** [comment]
> I thought the update would fix it but it still is not working, It just crashes my game the instant I press play. If I take Fabric API and the mods that use it out it works fine. But I need these mods to play. Anyone know anything?

Solved here: https://github.com/Chocohead/OptiFabric/commit/d444e69642439648300b739be6bd76b33ceb7b80

**Comment by Rippedbird** [comment]
> > I thought the update would fix it but it still is not working, It just crashes my game the instant I press play. If I take Fabric API and the mods that use it out it works fine. But I need these mods to play. Anyone know anything?
> 
> Solved here: [d444e69](https://github.com/Chocohead/OptiFabric/commit/d444e69642439648300b739be6bd76b33ceb7b80)

I have no idea what any of that means, I've downloaded the latest versions of everything the instant I take FabricAPI out it works
