### ISSUE TITLE
Game crash Exit Code: 0

### ISSUE THREAD

**Issue by taddmencer** [Chocohead/OptiFabric#528]
I got everything updated.

fabric-api-0.44.0+1.18.jar
fabric-installer-0.10.2.jar
optifabric-1.12.9.jar
OptiFine_1.18.1_HD_U_H4.jar
replaymod-1.18.1-2.6.3.jar

I get this 
![image](https://user-images.githubusercontent.com/1148597/146089950-0e9d4b6d-3454-4a42-b661-b2e07dbdee32.png)

If I remove OptiFabric, it loads Fabric & ReplayMod with no problem. Second I toss OptiFine in, everything goes pear-shaped.

Now, if I delete OptiFine, it naturally gives an error wanting OptiFine. So I know SOMETHING is working. 

I've removed ALL the mods and redownloaded them to make sure nothing was corrupt to no avail. 

![image](https://user-images.githubusercontent.com/1148597/146090731-0c51b383-b23e-4cbd-b601-6a0f7385529a.png)

My profile is the latest

![image](https://user-images.githubusercontent.com/1148597/146090377-2413d109-6651-4a67-b081-b00a07e894be.png)

**Comment by Mollfunn** [comment]
It won't work with replay mod, I don't know why exactly but that's it.

**Comment by taddmencer** [comment]
Yup, you're right. Not sure how I missed that. What a bummer. Kind of needed that one too. Ok, so ... I'll move this over to ReplayMod's Discord. Thanks, stomno.
