### ISSUE TITLE
Optifabric crashing with Inmis 1.16.1

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#54]
Crashlog: https://paste.ee/p/rfsup

Removing inmis seems to fix the problem, but here are the other mods I have installed:
![image](https://user-images.githubusercontent.com/55637354/93687656-46009f00-fa8d-11ea-94a5-27936aab4b0d.png)

I've tried previous versions of optifabric as well and they seem to be causing similar crashes

**Comment by Chocohead** [comment]
The 2.4.2 update to Cardinal Components API fixed this (OnyxStudios/Cardinal-Components-API@bfc9b63), you should be able to download the item part [here](https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3007262) given that's all which was broken.
