### ISSUE TITLE
1.18.1 crash with OptiFine > H5 pre2

### ISSUE THREAD

**Issue by Nuanulla** [Chocohead/OptiFabric#540]
When only OptiFabric 1.12.10 and OptiFine H5 pre3 are present in mods folder, game crashes with the following error:
_The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: Mixin transformation of net.optifine.CustomColors failed
Exit Code: 255_

**When Fabric API is present, the game reloads perpetually on the logo + loading bar screen.**

Crash log:
https://pastebin.com/S7ERUFQM

Seems to be an issue with some sort of new change done to OptiFine's CustomColors functionality. The last compatible OptiFine version with optifabric-1.12.10 is H5 pre2. The latest compatible publicly available version is H4.

Edit: Persists with pre4
Edit: Perpetual reload persists with Fabric API 0.45

**Comment by juliocoliveira** [comment]
Indeed for pre4 it keeps reloading forever, on the "final" release H4 works just fine.

**Comment by ShayBox** [comment]
Any update? H4 has a problem where you can't see under water with shaders on.

**Comment by RyanCR03** [comment]
i think thats your shaderpack. i use bsl and the water is fine

**Comment by Nuanulla** [comment]
> Any update? H4 has a problem where you can't see under water with shaders on.

Might be as @RyanCR03 mentioned.
Also, check to see if you can replicate the issue with OptiFine as game loader and/or Forge mod. Then, contact either the shaderpack's creator or open an issue on OptiFine's GitHub. If the issue only occurs on Fabric with that specific shaderpack, create a new issue here on OptiFabric's page.

**Comment by ShadeTheCat** [comment]
Well friends, looks like i stumbled apon this bug too, oddly with 1.12.9 optifabric.
i had updated my optifine because it was needed for a texture pack

**Comment by XavierBit** [comment]
Same problem persists with preview OptiFine 1.18.1 HD U H5 pre3.
Log: https://paste.ee/p/aByO1

**Comment by LegendOfCatBro** [comment]
Same issue, i gave my details in the above issue before realizing it was a duplicate. Any updates on fixing this?

**Comment by NaiNonTH** [comment]
> Same issue, i gave my details in the above issue before realizing it was a duplicate. Any updates on fixing this?

@LegendOfCatBro All you can do is to wait for Chocohead to come back and update their mod.

**Comment by Nuanulla** [comment]
Fixed with OptiFabric-v1.13.0

**Comment by isavailablh** [comment]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5705(float)" because "renderViewEntity" is null
Using litematica & Malilib with Optifabric 1.19 and Optifine H9

When Fabric API is present it stops at ~90% on Mojang Studios loading screen, otherwise game starts but when loading into a world game crashes.
Both issues stated persist to this day.
