### ISSUE TITLE
Game Loading

### ISSUE THREAD

**Issue by GreyWolfGamingHQ** [Chocohead/OptiFabric#58]
When ever I launch Fabric 1.16.3 I get a crash notice. I've checked all my mods, and it only happenes with Optifabric. Any help, or suggestions?

**Comment by ghost** [comment]
> When ever I launch Fabric 1.16.3 I get a crash notice. I've checked all my mods, and it only happenes with Optifabric. Any help, or suggestions?

Same here.

**Comment by ice21415** [comment]
Same here.

**Comment by redsoilfarmer** [comment]
Same here.

**Comment by johnnygoboy** [comment]
Yeah seems to load fine on its own - says  Optifine is not installed, seems to be an incompatibility with Optifine, have tried two releases of Optifine U3 and U4 and both cause the crash - something about returning error 0 - whatever that means.

**Comment by Wolfieheart** [comment]
Sorry but does not appear to be happening with the Latest Optifabric (1.16.3-1.6.2) and the Latest Optifine (1.16.3-U-G3), with the following mods enabled:

![image](https://user-images.githubusercontent.com/18635695/93708385-0477fe80-fb36-11ea-8cfb-e154bbc40087.png)

Questions from our side:

1. What Other Mods are you using along side OptiFabric and OptiFine?
2. Which version of Optifabric are you using? As the Artifact version (that has been going around on reddit), is not intended for everyday use. We recommend using the latest version from our Curseforge.
3. What Version of FabricLoader and FabricAPI are you using?

**Comment by GreyWolfGamingHQ** [comment]
here are my mods. 
![image](https://user-images.githubusercontent.com/71578157/93714949-a80fe180-fb2b-11ea-96d7-2017bc63cda5.png)

**Comment by Wolfieheart** [comment]
Things that jump out:

Sodium is not compatible with Optifabric. Carpet is not currently working with Optifabric (See Issue #59 ). Try disabling those 2 and going again. 

If it breaks again, please post the crash report

**Comment by GreyWolfGamingHQ** [comment]
Ok thank you!

**Comment by johnnygoboy** [comment]
Ah I was running carpet.
