### ISSUE TITLE
Architectury API compat code outdated with arch api 3.6.15+

### ISSUE THREAD

**Issue by Juuxel** [Chocohead/OptiFabric#598]
Relevant snippet from someone's log in the Architectury discord:
```
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class dev/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757
    at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:90) ~[optifabric-1.12.10.jar:?]
    at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:57) ~[optifabric-1.12.10.jar:?]
```

It seems to be caused by Arch API's update to have a separate mixin with Loader 0.13 (due to the mixin lvt mess): https://github.com/architectury/architectury-api/commit/6530f388a945e572685820db53f39f4a8d781117

**Comment by Hebgbs** [comment]
So just to be clear, what is at fault here? Which plugin is to blame for this? Is this a problem caused by Fabric 0.13.0 or a commit to Architectury?

**Comment by Juuxel** [comment]
This is caused by Optifabric having broken compatibility code because it modifies Arch API's internals which have been refactored. (And Fabric messing with Mixin's LVT handling by adding broken compatibility modes, which made us update Arch API's internals in the first place)

**Comment by muluffel** [comment]
Chocohead needs to fix it 😢

**Comment by ghost** [comment]
Support has been added via the latest build on the 1.18.2 PR. This is still testing but works fine. To use, you need to edit the Architectuary Fabric-mod.json in the architectuary jar and remove the breaks part for Optifabric until they remove themselves.
