### ISSUE TITLE
Crash when starting on fabric 0.13.x

### ISSUE THREAD

**Issue by Seeloewen** [Chocohead/OptiFabric#603]
Minecraft simply crashes if you start it with optifabric installed on **fabric 0.13.x**
There seems to be incompatibility with the new fabric 0.13.x as it only crashes on those versions.

To be exact, I am using **Optifabric 1.12.10 on 1.18.1 with OptiFine 1.18.1_HD_U_H4, running on fabric 0.13.2.**
Used fabric 0.12.12 before, worked fine. Also tested if its an compatibility issue with another mod, doesn't seem to be the case.

Fabric Crash log when starting minecraft is attached.
[Fabric Crash Log.txt](https://github.com/Chocohead/OptiFabric/files/8064193/Fabric.Crash.Log.txt)

**Comment by Mobmaker55** [comment]
I am having this issue too! It's not just you. 
**Optifabric 1.12.10** on **1.16.5** with any version of 1.16.5 OptiFine (I tried them all) on **Fabric 0.13.1-1.16.5**
Anything below version 0.13 of Fabric works fine.

**Comment by Seeloewen** [comment]
Closed issue as I believe that this has been fixed.
