### ISSUE TITLE
Optifabric not finding Optifine

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Chocohead/OptiFabric#610]
I am using the latest version of optifabric available on curseforge (1.12.10) and I am using the latest version of optifine (1.18.1 HD_U_H4) but when I launch minecraft I get an error saying optifabric could not find optifine in my mods folder even though it is present.
![image](https://user-images.githubusercontent.com/87249339/155388178-22475243-c6c4-49a0-8975-e3e6fb649fa0.png)

**Comment by KeeveeKoomoo** [comment]
And yes, I have tried without the better third person mod, it still says that optifabric could not find optifine regardless of the presence of BetterThirdPerson

**Comment by ghost** [comment]
Rename your optifine jar to OptiFine_1.18.1_HD_U_H4.jar, that should fix your issue. Thats the official Jar name, which works for me.

**Comment by dommilosz** [comment]
Make sure to use extract option in OptiFine installer it worked for me. I use 1.16.5 and extracted OptiFine is 5-6MB, the not extracted jar is larger like 15MB. In your case I see the file is the large one so I suspect you didn't extract it.

**Comment by ghost** [comment]
You shouldn’t need to run the installer with Optifabric… the installer is for the Optifine profile.

**Comment by dommilosz** [comment]
Yes the installer installs the profile or extracts the mod which is needed here

**Comment by ghost** [comment]
> Yes the installer installs the profile or extracts the mod which is needed here

Not sure what you’ve been smoking, but in all my time of using optifabric, I’ve never run the optifine installer, and it still works fine. The OPs issue is the Optifine jar he has is named incorrectly, that’s all. In fact, you can confirm you don’t need to extract since Optifine can be installed to the mods folder with Forge, WITHOUT installing.

**Comment by KeeveeKoomoo** [comment]
> Rename your optifine jar to OptiFine_1.18.1_HD_U_H4.jar, that should fix your issue. Thats the official Jar name, which works for me.

If you look in the screenshots, I am pretty sure that is the name already present, however, instead, for me, it was 
OptiFine-1.18.1_HD_U_H4.jar instead of OptiFine_1.18.1_HD_U_H4.jar. regardless, I changed the - to a _ but the issue still persists. idk if you saw the name in the screenshot before offering this answer but ye this answer didn't work.

**Comment by KeeveeKoomoo** [comment]
> Make sure to use extract option in OptiFine installer it worked for me. I use 1.16.5 and extracted OptiFine is 5-6MB, the not extracted jar is larger like 15MB. In your case I see the file is the large one so I suspect you didn't extract it.

Ye I got the optifine jar from the installation folder of optifine in the minecraft launcher by pressing install and not extract. I'll try this to make sure tho.

**Comment by KeeveeKoomoo** [comment]
ok for some reason right now the optifine website is down so it will take a while for me to be able to try this, however I have used optifine with other mods before trying optifabric, can't remember how, but I have never used the extract function so I can't see that being the solution

**Comment by KeeveeKoomoo** [comment]
> B, the not extracted jar is larger like 15MB. In your case I see the file is the large one so I suspect you didn't extract it.

Thanks a bunch, this did the trick.
