### ISSUE TITLE
OptiFabric keeps Mojang Studios Loader Stuck

### ISSUE THREAD

**Issue by alexpatney** [Chocohead/OptiFabric#611]
![mojangstudios](https://user-images.githubusercontent.com/70240335/155600728-89f1708a-22de-48a8-910d-64b8662780f0.png)
Whenever I load in Minecraft with OptiFabric it stays stuck on the loading screen. I know its not frozen because the bar gets to the end, stops, and starts from the beginning and goes to the end. It is OptiFabric because when I remove it and Optifine from my mods folder it works perfectly

Update: Fixed

**Comment by JoelDugong10** [comment]
how did u fix it?  my discord is Shithead#6544 id love if youd held me
