### ISSUE TITLE
the game crashes because of optifabric , on the red loading page 

### ISSUE THREAD

**Issue by Frostash** [Chocohead/OptiFabric#62]
if i remove optifabric the game works normally {optifine gets disabled but rest fabric mods work } 
mods that i have : 
voxel map 
wrust client
fabric api
optifine and optifabric

https://pastebin.com/qF90ydE9 there is a crash report , sorry for my potato pc

all mods are on latest version

and optifabric for 1.16.2 worked good af for me 
you guys are doing a great job , making game more insane to play :)

**Comment by Chocohead** [comment]
This looks to have already been resolved: Wurst-Imperium/Wurst7#183
