### ISSUE TITLE
Minecraft loops on loading when using minecraft 1.18.1

### ISSUE THREAD

**Issue by RobXol4535** [Chocohead/OptiFabric#621]
When I open Minecraft on 1.18.1, the game starts boot looping.

The mods I have installed
![image](https://user-images.githubusercontent.com/89336053/157043372-6f720649-f9a7-4165-8298-05d8a85459f9.png)
I don't know what is wrong but it's probably something to do with the Fabric API

**Comment by topia** [comment]
maybe duplicate of https://github.com/Chocohead/OptiFabric/issues/620#issuecomment-1059905605

**Comment by RobXol4535** [comment]
> maybe duplicate of [#620 (comment)](https://github.com/Chocohead/OptiFabric/issues/620#issuecomment-1059905605)
no its not bruh

**Comment by topia** [comment]
if this is a different issue from other loop issues, I think we need the crash report to know the details.

**Comment by RobXol4535** [comment]
> if this is a different issue from other loop issues, I think we need the crash report to know the details.

Minecraft wont crash and the problem is the optifine version

**Comment by eltrevii** [comment]
@RobXol4535 use optifine hd u h4. h5 is not compatible.
