### ISSUE TITLE
VoxelMap compatibility

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [Chocohead/OptiFabric#63]
[VoxelMap](https://www.curseforge.com/minecraft/mc-mods/voxelmap), arguably the best mapping mod, shows empty blue void instead of the world (I mean, not the map, it shows terrain, but player's surroundings do not show up). When used without OptiFine+OptiFabric, it works as intended.

The maintainer of VoxelMap does not respond to bug reports at all for a while now.

Can you look into it, maybe the issue can be resolved by OptiFabric?

**Comment by IMS212** [comment]
I do not have this issue on 1.16.3, do you have any other mods installed?

**Comment by 0xfeeddeadbeef** [comment]
I've turned off "In-game waypoints" feature of VoxelMap, and now it is working as intended (minus the in-game waypoints, of course).
