### ISSUE TITLE
Minecraft never loading when optifabric is installed, PLEASE HELP

### ISSUE THREAD

**Issue by AnekoNya** [Chocohead/OptiFabric#637]
When I try to run Optifabric on 1.18.1 it just does this. I have tried redownloading the mods and reinstalling fabric multiple times over and I don't know what's wrong. I have also attached a picture of my mods folder just in case. 

https://user-images.githubusercontent.com/101608930/158285991-87375be4-08fb-4235-bc12-5f13c796b99c.mp4

![Screenshot 2022-03-15 091038](https://user-images.githubusercontent.com/101608930/158286325-5433e900-b5ff-46a3-87b0-593fa9a1ec00.png)

**Comment by voximir-p** [comment]
Did you use the correct version of fabric API? And please check if you are using the lasted version of java.

**Comment by AnekoNya** [comment]
I have the latest version of Java installed, and I am using the correct fabric API. Any other ideas?

**Comment by voximir-p** [comment]
OMG it happen to me too, I think this version is buggy and you can use forge for normal optifine or the better way that still using fabric is to use Sodium and Iris instead of using optifine and optifabric.

**Comment by Kokonico** [comment]
Weird. Never Happened to me. I'm using a mac though.

**Comment by voximir-p** [comment]
else, just use other version of this mod e.g. 1.12.9

**Comment by AnekoNya** [comment]
It's because I wanted to join a server that wanted fabric for the proximity voice chat mod, but I really want the connected textures as well, because sodium and Iris don't have that. But some people in that server have said they can get it to work with optifabric

**Comment by voximir-p** [comment]
Oh… so use that 1.12.9 version

**Comment by Kokonico** [comment]
I heard that optifabric does not work with fabric 13. Not sure though.

**Comment by AnekoNya** [comment]
Im trying that now

**Comment by voximir-p** [comment]
lol this become live chat

**Comment by AnekoNya** [comment]
haha yeah

**Comment by Kokonico** [comment]
my inbox is blowing up aaaaaaaa

**Comment by voximir-p** [comment]
same

**Comment by Drunknbyte** [comment]
dude for 1.18.1 use this OptiFine_1.18.1_HD_U_H4 the H5 does that.  Let me know you results. Maybe im wrong, but i think there is no optifabric for _H5. 
![image](https://user-images.githubusercontent.com/83468615/158317864-ec4dce8a-834d-4766-b2c6-b349da76da24.png)

**Comment by AnekoNya** [comment]
Thanks, that fixed it :D
