### ISSUE TITLE
Optifabric for 1.18.2?

### ISSUE THREAD

**Issue by Nivo12** [Chocohead/OptiFabric#638]
Is there going to be a release of optifabric for 1.18.2? I cant use optifine without it. Wondering when it might be out.

Also, I have tried 1.18.1 optifabric on 1.18.2, the game didnt launch.

**Comment by Skywalker8510** [comment]
its being worked on and there is even a experimental jar here https://github.com/Chocohead/OptiFabric/pull/630#issuecomment-1066541646
I have been using it since it was posted with no problems.

**Comment by Nivo12** [comment]
> its being worked on and there is even a experimental jar here [#630 (comment)](https://github.com/Chocohead/OptiFabric/pull/630#issuecomment-1066541646) I have been using it since it was posted with no problems.

Thanks!
