### ISSUE TITLE
Hungerbar Invisible

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [Chocohead/OptiFabric#64]
Cannot see the hungerbar when using OptiFabric-v1.6.4 and OptiFine 1.16.3 HD U G3. No matter what shader I cannot see it. Tested without optifine/optifabric and works fine.

**Comment by Chocohead** [comment]
What mods are you using alongside OptiFabric? Presumably this is an interaction issue with something else

**Comment by DJTobi1Kenobi** [comment]
Yes it is! After some testing I have found t is "Age of Exile" that it is having trouble with: https://www.curseforge.com/minecraft/mc-mods/age-of-exile
