### ISSUE TITLE
Looped loading screen because of Optifabric

### ISSUE THREAD

**Issue by EnusaC** [Chocohead/OptiFabric#646]
While checking out mods, i kept coming across the problem that the loading bar keeps looping non stop. I checked my other mods and optifabric is the problem. Fabric is up to date with the latest version, optifabric is also on the latest version, optifine is installed and also on the latest version. With no other mods loaded, optifine seems to be the only problem. I'm running it on 1.18.1, everything from the start has always been set to 1.18.1. 

Any help would be appreciated.

**Comment by Goofball2** [comment]
I have this same problem, no idea how to fix just want an answer...

**Comment by Goofball2** [comment]
Hi, looking at other threads: its not compatible with optifine H5, use H4

**Comment by EnusaC** [comment]
Solved! Thanks Goofball2
