### ISSUE TITLE
Using This Mod Breaks MaLiLib

### ISSUE THREAD

**Issue by RU-B0** [Chocohead/OptiFabric#650]
Using This Mod Breaks MaLiLib
When I try to press MaLiLib shortcuts, it breaks my keyboard inputs to MaLiLib but not my mouse inputs

**Comment by ghost** [comment]
Theres something else causing that. I use Litematica, Tweakaroo, and Minihud all with Malilib and no issues. I can use Keyboard shortcuts for all.

**Comment by RU-B0** [comment]
I went through all my mods, only enabling one at a time, and the only thing that broke it was optifabric
