### ISSUE TITLE
1.16.2-3 w/108 mods modpack works greately alone but Optifabric

### ISSUE THREAD

**Issue by Misterboy64** [Chocohead/OptiFabric#66]
My friend is costantly having a problem with mods, so i'm usual to try and find what mod causes the error
Usually i load the whole modpack to be sure that every mod works altogether, and sometimes there's an actual mod that annoys even my minecraft, among these it's the Optifabric
yes, i know, the mods are too many (actually loaded 108 around but it's registred as 213), and most of the should be compatible, hell it even work.
I will be sending the log that registred the crash of the game, doesn't even start up mc at all:
[latest.log](https://github.com/Chocohead/OptiFabric/files/5288131/latest.log)
Please take your time as this is just a bug report, thanks in advance

**Comment by Chocohead** [comment]
The first part of the log suggests that the OptiFine jar is missing from the mods folder which your friend will need to add. There is also a problem with dark-loading-screen further down which I don't think is related. If it still doesn't work please do mention as it could be dark-loading-screen is struggling with OptiFine's changes.

As another aside once it does work, they will want to add `mixin.world.chunk_access=false` in the Lithum config to avoid heavy stalling with newer OptiFine versions.
