### ISSUE TITLE
Figura is incompatible.

### ISSUE THREAD

**Issue by Phighter14** [Chocohead/OptiFabric#669]
I cannot launch Minecraft with both Figura and OptiFabric in my mods folder, as it just provides an error saying that figura-0.0.8-1.18 is not compatible with any version of OptiFabric. Here's the given error.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Figura' (figura) 0.0.8+1.18 with any version that is compatible with:
		 - optifabric 1.13.0
Unmet dependency listing:
	 - Mod 'Figura' (figura) 0.0.8+1.18 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

It would be beneficial to others as well as myself if this is resolved.
I apologize if I am bothering you too much, or if this is too much to do. Please remember that you are not required to fix this. We should be able to find possible alternatives(that may or may not work) if this cannot be resolved. Even if we do not find working alternatives, it is not like we will die without it.
Stay safe!

**Comment by ghost** [comment]
This isn't down to Optifabric, its down to the creator of Figura marking it incompatible.

**Comment by Phighter14** [comment]
> This isn't down to Optifabric, its down to the creator of Figura marking it incompatible.

Alright, thank you.
