### ISSUE TITLE
Incompatibility with Sildur's shaders (1.16.3)

### ISSUE THREAD

**Issue by nielsmittertreiner** [Chocohead/OptiFabric#68]
I tried to play with multiple shaders, however, Sildur's shaders don't work with OptiFabric, I just get a black screen.
I've tested it in regular Optifine too, and it works as expected there.

I've tested both Sildur's Enhanched Default and Sildur's Vibrant Shaders

**Comment by IMS212** [comment]
Works perfectly for me, are you using any other mods?

**Comment by nielsmittertreiner** [comment]
Nope, I'm not using any other mods

**Comment by Chocohead** [comment]
Has this been resolved with the newest OptiFine version? It came with some fixes especially for Sildur's things
