### ISSUE TITLE
minecraft can't find the .jar file in the mods folder 

### ISSUE THREAD

**Issue by nitaz** [Chocohead/OptiFabric#71]
Minecraft can't find the .jar file in the mods folder when optifabric is in the mods folder.
and I don't know what to do

![Untitled png jar file](https://user-images.githubusercontent.com/56861758/94850416-9550b300-042f-11eb-9bb7-4a71faa48612.png)

**Comment by Chocohead** [comment]
Can we get a screenshot of your mods folder?

**Comment by nitaz** [comment]
yes

**Comment by nitaz** [comment]
![image](https://user-images.githubusercontent.com/56861758/95013522-70378c80-0649-11eb-8d52-a3f9bbc1da26.png)

**Comment by 0xfeeddeadbeef** [comment]
Hmm. Error message does not lie, there is no OptiFine jar to be found in your mods folder...
[Download it from the OptiFine home page](http://optifine.net/adloadx?f=OptiFine_1.16.3_HD_U_G3.jar).

**Comment by nitaz** [comment]
im trying to use optifabric not optifine

**Comment by 0xfeeddeadbeef** [comment]
OptiFabric is **a loader** of OptiFine, it does not work alone.

**Comment by nitaz** [comment]
Ooooo

**Comment by nitaz** [comment]
thank you very much

**Comment by Shkoop** [comment]
I am having the same issue except I have the latest versions of both mods

![image](https://user-images.githubusercontent.com/72365578/95031823-dc77b780-066c-11eb-8303-c8c4c9f5a9e9.png)

**Comment by 0xfeeddeadbeef** [comment]
That looks weird: OptiFine jar is usually named 'OptiFine_X.X.X_HD_U_GX.jar', it does not begin with version number. Did you download it from [the official web site](https://optifine.net/adloadx?f=OptiFine_1.16.3_HD_U_G3.jar)?

**Comment by ghost** [comment]
yikes

**Comment by IMS212** [comment]
yeah, do you know where you got that version of optifine from? You should never download optifine anywhere but https://optifine.net or (backup site: old) https://optifined.net

**Comment by Gabrz** [comment]
The OptiFine jar you see in the screenshot is the jar from the .minecraft/versions folder (that jar is created when you install Optifine by executing the downloaded OptiFine jar file).

It is not the same (anymore) as the OptiFine jar you download from the website. 

To use OptiFine with (Opti)Fabric, you'll need the downloaded jar file.
