### ISSUE TITLE
Error transforming Optifine

### ISSUE THREAD

**Issue by Icecat113** [Chocohead/OptiFabric#73]
I keep getting this error message when I try running Optifabric and I'm not really sure what to do
![2020-10-05_20 10 32](https://user-images.githubusercontent.com/50216287/95154519-dc4bea80-0746-11eb-9c4f-624f087e68cf.png)

Here's the log file:
[latest.log](https://github.com/Chocohead/OptiFabric/files/5331183/latest.log)

**Comment by IMS212** [comment]
does this happen with no other mods?

**Comment by Icecat113** [comment]
Yeah, I made sure to try running it without my other mods

**Comment by Chocohead** [comment]
This is much more likely an issue with the OptiFine jar itself rather than another mod, I'd say from it not downloading properly/completely. Try replacing the OptiFine jar you're using with a fresh one downloaded from the [official site](https://optifine.net/downloads).

**Comment by Icecat113** [comment]
I figured out what the problem was. There was something wrong with the files in my .optifine folder. I deleted the files and now the optifabric mod works
