### ISSUE TITLE
Update to 1.19 

### ISSUE THREAD

**Issue by LeviiiCraft** [Chocohead/OptiFabric#742]
Update to 1.19 pls

**Comment by LeviiiCraft** [comment]
Hi, can someone update Optifabric für 1.19? I   hope it is possible. So pls update it.
Thank you

**Comment by moonsunrise** [comment]
hhhhhhhhh

**Comment by Luke-The-Duke** [comment]
> Hi, can someone update Optifabric für 1.19? I hope it is possible. So pls update it. Thank you

Oh, shut up. People like you are the worst. They will update it for 1.19 eventually. It doesn't just happen overnight.

**Comment by LeviiiCraft** [comment]
Sry but i don‘t understand your problem, I only ask for!

**Comment by SJ-Tom** [comment]
OptiFine for 1.19 isn't out so why are you need OptiFabric for it

**Comment by LeviiiCraft** [comment]
Yes sry but last time they created the Optifabric 1.18.2 Version before Optifine was out. And I Need Optifabric because I play only with Fabric

**Comment by LeviiiCraft** [comment]
Sry but I really don‘t understand your problems, I only ask but then… Bye bye

**Comment by osfanbuff63** [comment]
> Yes sry but last time they created the Optifabric 1.18.2 Version before Optifine was out. And I Need Optifabric because I play only with Fabric

This isn't true at all, #630 was created *after* OptiFine's 1.18.2 update...

**Comment by Skywalker8510** [comment]
> > Yes sry but last time they created the Optifabric 1.18.2 Version before Optifine was out. And I Need Optifabric because I play only with Fabric
> 
> This isn't true at all, #630 was created _after_ OptiFine's 1.18.2 update...

yea we just need to wait till optifine 1.19 comes out. then development on optifabric will start.

**Comment by muluffel** [comment]
When there is no OptiFine for 1.19 there's no reason for optifabric to exist for 1.19
