### ISSUE TITLE
1.19 progress?

### ISSUE THREAD

**Issue by asheden** [Chocohead/OptiFabric#749]
how far along is optifabric 1.19's development?

**Comment by asundrus** [comment]
Considering that Optifine only just released pre-release 2 for 1.19, I would arm myself with patience.

**Comment by fabricws** [comment]
When will the 1.19 optfabric come out?

**Comment by rrvk** [comment]
When it is ready ;) Just be calm.
And if you want it to be faster you can probably help with a pr?

**Comment by James-Tripper** [comment]
Yeah, i could see it being hard to put out the optifabric/optiforge without a completed optiine to work from.
