### ISSUE TITLE
will there be a optifabric update released with optifines prerelease version or is the creator going to wait for a full release first?

### ISSUE THREAD

**Issue by blulev** [Chocohead/OptiFabric#750]
what has he done with previous versions like from 1.17 to 1.18? did he do prerelease versions back then or no?

**Comment by blulev** [comment]
i dont get what im supposed to see on that link looks like a bunch of code can u just answer the question...

**Comment by Chocohead** [comment]
The code did (sort of) answer the question, it needed to be pushed first so it could go [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3857232). Just has the unfortunate side effect of closing the issue before the upload is done
