### ISSUE TITLE
Crash on world load with Optifabric 1.19

### ISSUE THREAD

**Issue by DomQuantum** [Chocohead/OptiFabric#753]
I'm using file version [OptiFabric-v1.13.4](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3857232)

This is the error I'm getting.

The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1

Here's the crash report.

[crash-2022-07-03_08.06.03-client.txt](https://github.com/Chocohead/OptiFabric/files/9034690/crash-2022-07-03_08.06.03-client.txt)

**Comment by SStatZX** [comment]
This seems to have to been a bug caused by optifine that has been [fixed](https://github.com/sp614x/optifine/issues/6858) (as of pre4)

**Comment by Chocohead** [comment]
OptiFine issue (since fixed): sp614x/optifine#6858
