### ISSUE TITLE
Optifine Crashing with Fabric-lookup-api

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#754]
As title states, running Optifabric with JEI for 1.19 results in a crash on launch of the above error, so must be related as once I uninstall JEI everything works.

Log
[2022-07-03-1.log](https://github.com/Chocohead/OptiFabric/files/9034715/2022-07-03-1.log)
:

**Comment by Chocohead** [comment]
This is almost certainly from your Fabric API jar being corrupt, if you re-download it that should fix this crash.
