### ISSUE TITLE
Minecraft does not start

### ISSUE THREAD

**Issue by TheDrMike** [Chocohead/OptiFabric#760]
Good afternoon, could you help solve the problem, when I run the assembly of mods (1.19Fabric) minecraft, an error comes to me. If you remove Optifabric from the list of mods, then everything works, and if there is an error with it, what should I do in this situation?
[latest.log](https://github.com/Chocohead/OptiFabric/files/9044402/latest.log)

**Comment by Chocohead** [comment]
You need to update OptiFabric to at least 1.13.4 for 1.19, preferably the newest version
