### ISSUE TITLE
Optifabric crashes with latest optifine pre-release (1.19 pre5)

### ISSUE THREAD

**Issue by SStatZX** [Chocohead/OptiFabric#761]
### Optifabric (1.13.4) seems to not be able to launch minecraft with Optifine. (1.19 pre5)
Latest fabric-api is in use (0.57.0+1.19) as well as fabric-loader. (0.14.8)
Optifine pre4 + Optifabric works fine for me.

**Here's the crash log:**
[crash-2022-07-05_18.35.27-client.txt](https://github.com/Chocohead/OptiFabric/files/9048420/crash-2022-07-05_18.35.27-client.txt)

**Comment by screechystrings** [comment]
I'm having the same problem.

**Comment by XIAYM-gh** [comment]
same xD

**Comment by Rangelito1** [comment]
same :(

**Comment by Dr-kukumber** [comment]
crushing when i use fabric api, it runs fine without it

**Comment by juliocoliveira** [comment]
same here, happens on pre5 or pre6, pre4 is unavailable to download. Can you upload it here?
