### ISSUE TITLE
Game Crashes when loaded with Optifine Pre6 and Fabric API

### ISSUE THREAD

**Issue by LouisHitchcock** [Chocohead/OptiFabric#765]
[latest.log](https://github.com/Chocohead/OptiFabric/files/9055807/latest.log)
When game is loaded iwth Fabric API and Optifine Pre6 on latest download of Optifabric it is unable to complete load and crashes.

I have attached my latest.log file

**Comment by cbeasle** [comment]
Same issue.  Here is my crash report.
[crash-2022-07-06_10.02.58-client.txt](https://github.com/Chocohead/OptiFabric/files/9055958/crash-2022-07-06_10.02.58-client.txt)

**Comment by juliocoliveira** [comment]
Same here, happens with pre5 or pre6
[crash.log](https://github.com/Chocohead/OptiFabric/files/9056493/crash.log)

**Comment by Rogow** [comment]
Same issue, also happens with pre7

**Comment by hectorviov** [comment]
Still happening on pre7

**Comment by thiagogebrimm** [comment]
Same problem

**Comment by TaaTra** [comment]
Same problem, Game Crashes when loaded with Optifine Pre7 and Fabric API. Please fix this ;)

**Comment by Bruh2801** [comment]
same problem

**Comment by Sebyx1** [comment]
Have the same problem, wait vor OptiFine Full Release :)
