### ISSUE TITLE
I cant load any single player worlds on version 1.18.2

### ISSUE THREAD

**Issue by MrTophatMan** [Chocohead/OptiFabric#776]
The mods I have installed: replaymod 1.18.2, fabric api 1.18.2, optifine 1.18.2, optifabric mod ver. 1.13.0

When I get on minecraft everything seems fine, but when I join a singleplayer world it gets stuck on 100% and never loads.
When I try removing optifabric and optifine everything is fine and working but the framerate isnt good so I am stuck not being able to use optifine and the replay mod together.

**Comment by Derp33** [comment]
As a workaround, try using Fabric API 0.53. I had the same issue loading any world/server.

**Comment by Chocohead** [comment]
Try updating to at least OptiFabric 1.13.4, newer 1.18 Fabric API versions have an issue on 1.13.0

**Comment by MrTophatMan** [comment]
it works now thx
