### ISSUE TITLE
Will not load properly with the newest version of sodium in 1.19

### ISSUE THREAD

**Issue by squidprobe21** [Chocohead/OptiFabric#778]
Every time i try to boot my game up it just says incompatible mod set and tells me to replace it with a version that works with optifabric 1.13.5, yet sodium 0.4.2+ is the ONLY version currently available for 1.19. please fix this.
This is the error i get everytime i launch the game:

A potential solution has been determined:
Replace mod 'Sodium' (sodium) 0.4.2+build.16 with any version that is compatible with:
optifabric 1.13.5

Unmet dependency listing:
Replace mod 'Sodium' (sodium) 0.4.2+build.16 with any version that is compatible with:
<html>Mod 'Sodium' (sodium) 0.4.2+build.16 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching<br>version is present: 1.13.5!</html>

Tried everything i could think of, if theres something i didnt try let me know. currently ive tried replacing the optifabric version with 1.13.4, same error happens. also tried looking for a didnt version of sodium but could only find the one (on curseforge at least). couldnt really think of any other ways of fixing it though.

**Comment by topia** [comment]
sodium and optifabric/optifine are incompatible by design. they are patching the same place in different ways.

**Comment by squidprobe21** [comment]
oh, im an idiot, idk how i immediately forgot that it was a performance mod, for some reason i though it was on of the library mods i had. my bad!

**Comment by Thetripper** [comment]
how did you fix it in the end?

**Comment by JustAHuman-xD** [comment]
> how did you fix it in the end?

you just dont use the 2 of them together, they are incompatible with no exceptions

**Comment by Thetripper** [comment]
oh, ok. thank you.

**Comment by Chocohead** [comment]
As mentioned, you can't use OptiFabric and Sodium at the same time.

**Comment by AyoTedd** [comment]
> As mentioned, you can't use OptiFabric and Sodium at the same time.

When I removed Sodium, it still gave me the error and told me to install it.
![image](https://user-images.githubusercontent.com/109137390/179768816-648aab90-6d4b-4ac9-927c-b563682d53cf.png)

**Comment by topia** [comment]
Please remove iris and indium too.
