### ISSUE TITLE
slower than optifine

### ISSUE THREAD

**Issue by zxcdevlop** [Chocohead/OptiFabric#78]
When I run OptiFabric I get 30 fps max, but with Optifine itself I get 70 fps max. Can you fix this, please? I use Fabric for the ReplayMod and would love to use it with OptiFabric. Thanks.

**Comment by Chocohead** [comment]
There's no practical difference in the way OptiFabric applies OptiFine than OptiFine itself would to vanilla. As such any performance problems which are that drastic are likely to come down to the instances of Minecraft itself being configured differently (presuming Fabric API isn't present but even that shouldn't be even nearly halving your FPS). I'd make sure your Fabric instance has the configurations like RAM allocation as your OptiFine one does as that's most likely to be making the difference.
