### ISSUE TITLE
Optifabric incompatible with iris, sodium and lithium.

### ISSUE THREAD

**Issue by Dberg04** [Chocohead/OptiFabric#797]
"Mod 'Iris' (iris) 1.2.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is<br>present: 1.13.8!
1.13.8 is the one I used

**Comment by topia** [comment]
Optifine is incompatible with iris, sodium, and lithium. So optifabric is incompatible.
Please use either optifine or optifine-alternatives, not both.

**Comment by Chocohead** [comment]
As mentioned, you simply can't use OptiFabric at the same time as those mods. They change the same parts of Minecraft in a way that just isn't compatible together.
