### ISSUE TITLE
Crash incompatibly with Origins 0.4.0-0.4.1

### ISSUE THREAD

**Issue by XSilverBerryX** [Chocohead/OptiFabric#80]
The game cannot get past the loading screen before crashing when using the most recent version of both Origins and Opitfrabric/Optifine
these are the exact mods loaded with the Fabric loader 0.10.3:
![image](https://user-images.githubusercontent.com/73409738/97096104-db620500-16c3-11eb-89ef-45cf180e736a.png)
this is the crash report:
[crash-2020-10-25_13.16.04-client.txt](https://github.com/Chocohead/OptiFabric/files/5433965/crash-2020-10-25_13.16.04-client.txt)
and this is the error the minecraft launcher brings up:

> The game crashed whilst initializing game
> Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> Exit Code: -1

it constantly brings up this error everytime it crashes, including when launching with Origins 0.4.0

**Comment by Chocohead** [comment]
Looks to be the same problems #9 had, Origins has just changed their versioning scheme so OptiFabric thinks it doesn't need to apply the patch for it anymore.
