### ISSUE TITLE
Crashing on start with Fabric API installed

### ISSUE THREAD

**Issue by grob-ik** [Chocohead/OptiFabric#805]
[latest.log](https://github.com/Chocohead/OptiFabric/files/9182337/latest.log)

**Comment by topia** [comment]
No mention of the optifine version, but I doubt you use the H9 (pre) version.
https://github.com/Chocohead/OptiFabric/issues/794#issuecomment-1193435751
Could you confirm it? If so, maybe you want to try optifine H8 instead.

**Comment by grob-ik** [comment]
Yes, i also tried H8 version and still it's crashing

**Comment by topia** [comment]
> Yes, i also tried H8 version and still it's crashing

Really? I confirmed I can start with the following combination:
```
  [✔] fabric-api-0.58.0+1.19
  [✔] optifabric-1.13.8
  [✔] OptiFine_1.19_HD_U_H8
```

**Comment by grobikkk** [comment]
Looks like I was using an older version of fabric api, I updated it and minecraft doesn't crash anymore

**Comment by grob-ik** [comment]
Looks like I was using an older version of fabric api, I updated it and minecraft doesn't crash anymore
