### ISSUE TITLE
Incompatible with Just Enough Items (JEI)

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#811]
Optifabric is incompatible with Just Enough Items (JEI), the game crashes at startup.
Link of the most recent version of JEI (Fabric):
[jei-1.19-fabric-11.1.1.239.jar](https://www.curseforge.com/minecraft/mc-mods/jei/files/3903066)

**Comment by GEkXD3** [comment]
Just use REI :)

(just joke, idk what to do it, good luck)

**Comment by GEkXD3** [comment]
Can you list your system (Win 10, Win 11 etc.), all mods and latest crash logs?

**Comment by ghost** [comment]
Win 10 and is not necessary list all mods because i try load MC with Optifine,Optifabric and JEI.

**Comment by ghost** [comment]
https://github.com/IntMarco/Crash-JEI

**Comment by dusbn** [comment]
Is this still a thing? I am getting the same error :(

**Comment by GEkXD3** [comment]
> Is this still a thing? I am getting the same error :(

Idk, i haven't this error. You tried using REI?
