### ISSUE TITLE
Unknown crashing

### ISSUE THREAD

**Issue by GEkXD3** [Chocohead/OptiFabric#812]
In General, when I launch Minecraft, I get an error. Obviously.

**[Crash log](https://pastebin.com/8bNzTtpU)**

So please help. Thanks!

**EDIT: Minecraft version - 1.19**

FIXING ISSUE: In my situation - delete EmotionCraft

**Comment by topia** [comment]
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method addInfo(Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1920;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLnet/minecraft/class_5819;Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/lang/Throwable;Lnet/minecraft/class_128;Lnet/minecraft/class_129;)V in optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap optifabric-refmap.json
```
I saw the similar error with older fabric API or optifine H9.
Could you check #805?

**Comment by GEkXD3** [comment]
> ```
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method addInfo(Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1920;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLnet/minecraft/class_5819;Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/lang/Throwable;Lnet/minecraft/class_128;Lnet/minecraft/class_129;)V in optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap optifabric-refmap.json
> ```
> 
> I saw the similar error with older fabric API or optifine H9. Could you check #805?

Installed the latest Fabric API and OptiFine H8 and nothing helped. Maybe I'm installing the OptiFine mod somehow wrong. I can open the OptiFine.jar file and the installer opens, I try to unpack, and the error "Minecraft 1.19 was not found, go from the official launcher and install it" appears. Maybe you can somehow give a link or the OptiFine_MOD.jar file itself, I saw it somewhere. (sorry from bad english i'm from Lithuania)

**Comment by topia** [comment]
You don't need "install" optifine to use with optifabric, please refrain from doing it.
Please create a fresh fabric installation and just put optifine (installer, downloaded jar) and optifabric to the mod folder.

**Comment by GEkXD3** [comment]
> You don't need "install" optifine to use with optifabric, please refrain from doing it. Please create a fresh fabric installation and just put optifine (installer, downloaded jar) and optifabric to the mod folder.

Yes, it's working. I'll test turning off some mods in MultiMC and share the result.

**Comment by GEkXD3** [comment]
> You don't need "install" optifine to use with optifabric, please refrain from doing it. Please create a fresh fabric installation and just put optifine (installer, downloaded jar) and optifabric to the mod folder.

Thanks! I deleted EmoteCraft and all fixed! Very very big thanks!
