### ISSUE TITLE
1.19.1 not compatible with optifabric

### ISSUE THREAD

**Issue by Majerier** [Chocohead/OptiFabric#813]
The title say it

**Comment by topia** [comment]
optifabric is not compatible until optifine for 1.19.1 is released (at least).

**Comment by juliocoliveira** [comment]
Pre1 is already out

**Comment by Gyztor** [comment]
> Pre1 is already out

actually 1.19.1 is fully released now

It was fully released on july 27th if i remember correctly, But not Optifine's 1.19.1 version. So they will update optifabric when a full release comes out for optifine

Edit: i realize now you don't mean the 1.19.1 as a version but optifine's 1.19.1 version

**Comment by topia** [comment]
> Pre1 is already out

Oh, OptiFine 1.19.1_HD_U_H9_pre1 had released today.
I advise you to refrain from using "already" for the announcement at fifteen-minutes ago. I think it confuses and causes miscommunication.
