### ISSUE TITLE
OptiFine 1.19 HD U H9 not working with OptiFabric

### ISSUE THREAD

**Issue by AmbassadorLaZer** [Chocohead/OptiFabric#814]
OptiFabric doesn't work with 1.19 HD U H9.

**Comment by Icy9ptcl** [comment]
[crash-2022-08-02_11.45.48-client.txt](https://github.com/Chocohead/OptiFabric/files/9238665/crash-2022-08-02_11.45.48-client.txt)

Let me provide a crash report about this.

Note:
Fabric loader 0.14.8
Optifabric 1.13.8
Optifine 1.19 HD U H9
javaw runtime is provided from Minecraft Launcher

btw Optifine 1.19 HD U H9 was released on Jul 31st so it could be too early to discuss right now?

-- added 11:55
Optifabric 1.13.8 works very well with Optifine 1.19 HD U H8, so take your time.

**Comment by FlashLight34** [comment]
same here, minecraft crash

**Comment by Timey5Wimey** [comment]
i found the problem their two mod i have that incompatible with Optifabric (Moonlight Lib) and (Just Enough Items)

**Comment by Toma400** [comment]
I have almost no mods on my launcher, yet it crashes with almost solely OptiFine/OptiFabric used

[latest.log](https://github.com/Chocohead/OptiFabric/files/9268534/latest.log)

**Comment by Rexgram** [comment]
I'm pretty sure its just something to do with optifine itself.. I tried all of my mods without optifine, and it worked perfectly fine, but, once I added optifine to the mod folder, the game would crash.

**Comment by AmbassadorLaZer** [comment]
> I'm pretty sure its just something to do with optifine itself.. I tried all of my mods without optifine, and it worked perfectly fine, but, once I added optifine to the mod folder, the game would crash.

Yeah, it's something to do with OptiFine. OptiFine 1.19 H8 works but H9 doesn't, its most likely to be fixed with OptiFabric's next update.
