### ISSUE TITLE
optifabric not compatible

### ISSUE THREAD

**Issue by CaptnSexy** [Chocohead/OptiFabric#815]
Mod 'OptiFabric' (optifabric) 1.13.8 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version<br>1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18,<br>version 1.18.1, version 1.18.2 or version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present:<br>1.19.1!

**Comment by Graghoon** [comment]
I am having the same issue, and just adding "1.19.1" to the required versions in the 'fabric.mod.json' lets the game load but optifine doesn't work :/
![Capture](https://user-images.githubusercontent.com/52905964/182416541-15c6d221-bee8-4a8d-882d-e1cb3c6dad70.PNG)
e
