### ISSUE TITLE
Optifabric incompatible with Fabric 1.19.1

### ISSUE THREAD

**Issue by Graghoon** [Chocohead/OptiFabric#816]
Using the latest version of Optifine as of 8/2/22 "OptiFine_1.19_HD_U_H8", and the latest version of Optifabric as updated on 7/17/22 from Curseforge. "optifabric-1.13.8" will get you a 

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'OptiFabric' (optifabric) 1.13.8 with any version that is compatible with:
		 - minecraft 1.19.1
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.13.8 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18, version 1.18.1, version 1.18.2 or version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Tried adding the 1.19.1 in the "fabric.mod.json" and it loaded the game but optifine never showed up ingame.

"1.18.1",
      "1.18.2",
      "1.19",
      "1.19.1"  <- here
    ],

**Comment by topia** [comment]
This ticket is duplicated of #813. and optifine for 1.19 is not compatible with Minecraft 1.19.1.

**Comment by ArtoxFR** [comment]
Hey, 

Little trick to make it work :

Open "optifabric-1.13.8.jar" with WinRAR
Find & Open "fabric.mod.json" (Recommand Visual Studio Code or Sublitme Text or Notepad++ to open it)
Locate this section : 

```
"depends": {
    "fabricloader": ">=0.8.0",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5",
      "1.17-alpha.21.8.b",
      "1.17-beta.4",
      "1.17",
      "1.17.1",
      "1.18-beta.1",
      "1.18",
      "1.18.1",
      "1.18.2",
      "1.19"
    ],
    "mm": ">=2.0"
  },
```

At the end of this code, edit like this :

```
"1.19",
"1.19.1"
```
Save file, replace in archive with WinRAR, enjoy !
