### ISSUE TITLE
OptiFine_1.19_HD_U_H9 + fabric-api-0.58.0+1.19 crushing

### ISSUE THREAD

**Issue by MrJakeMC** [Chocohead/OptiFabric#823]
Minecraft 1.19 is crashing using only 3 mods: Optifabric 1.13.8, Optifine 1.19_HD_U_H9 and Fabric api 0.58.0. 
Can this be fixed somehow?

**Comment by MrJakeMC** [comment]
New version of Optifine need for Fresh Animations 1.7 resource pack and Fabric api 0.58.0 need for many other mods, but Minecraft crashing even when using these 3 mods standalone. Although Minecraft is not crushing without Fabric api.

**Comment by AmbassadorLaZer** [comment]
It's just OptiFine 1.19 HD U H9 that's causing the problem, reverting it back to H8 will fix the problem. It will most likely be fixed on OptiFabric's next update.
