### ISSUE TITLE
Update to 1.19.2

### ISSUE THREAD

**Issue by creeperNoob303** [Chocohead/OptiFabric#824]
Please update it to 1.19.2

**Comment by Graghoon** [comment]
we dont even have 1.19.1 yet :/

**Comment by math0898** [comment]
It would appear as there aren't any plans to update OptiFabric.

[The future of OptiFabric and Recommended alternatives](https://github.com/Chocohead/OptiFabric/blob/0495d5b23e185daa01bb52d41d9dfc0de45ee49d/README.md)

**Comment by topia** [comment]
~~This is the document which the previous developer wrote, isn't it?
By the way, I personally agree with that.~~

(This comment is a reply to the removed comment.)

**Comment by StereoMadnessss** [comment]
As some people use custom versions that have fabric that are limited or able to install the mods for sodium but the game crashes, that's why OptiFabric exists. As a way to make these situations bearable, OptiFabric exists.

**Comment by 4567gio** [comment]
you can close this because
optifabric is dependent of well optifine and theres is not optifine for 1.19.2

**Comment by juliocoliveira** [comment]
Yes, optifine for 1.19.2 is not yet available but its compatible with 1.19.2.
You can run Optfine 1.19.1 HD U H9 pre1 on 1.19.2 no problems

**Comment by topia** [comment]
At least optifabric checks optifine/Minecraft compatibility, so you can't use optifine for 1.19.1 on Minecraft 1.19.2.

**Comment by juliocoliveira** [comment]
Yes there is a check, i added the version on the fabric.mod.json and it blocked from running on fabric.
There is anyway to fake the version? Anyway to force it to run?
Tried to rename it to 1.19.2 and it didn't worked.

**Comment by topia** [comment]
Nothing except [changing optifabric code](https://github.com/Chocohead/OptiFabric/blob/1db17754ec7dd5cf813edf4c53d979a0c4c6c029/src/main/java/me/modmuss50/optifabric/mod/OptifineVersion.java#L118-L122) or patching optifine version definition (embedded in class)

**Comment by YTiceice** [comment]
I changed optifabric code, then it can work on 1.19.2
[mod download link](https://drive.icehost.xyz/optifabric-1.13.10.jar)
Put this file and `OptiFine HD U H9 pre1` in mods folder then startup minecraft
Screenshot:
![image](https://user-images.githubusercontent.com/87787929/184660044-4253c37a-34c7-4026-87df-0ffa0ee4fcef.png)
![image](https://user-images.githubusercontent.com/87787929/184660120-99407f1e-836e-4d9a-88f0-82bcc59e240b.png)
![image](https://user-images.githubusercontent.com/87787929/184660152-53b3f3f9-4cef-4804-a62d-459b89700ee1.png)

**Comment by juliocoliveira** [comment]
> 

Your version works fine. Thanks!

**Comment by akemin-dayo** [comment]
I've implemented a similar temporary workaround (disabling the version check) [in my fork of OptiFabric](https://github.com/akemin-dayo/OptiFabric).

The source code is freely available for those who want to see exactly what was changed, and/or those who prefer building their own binaries locally.

I've changed the version number to `1.13.10~akemi` (plus the Git commit short SHA-1) in order to clearly differentiate it from the official upstream OptiFabric versions.

**※ IMPORTANT NOTE:** OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer.
Please use Fabric API 0.59.0+1.19.2 (or older) instead.

My fork explicitly marks Fabric API 0.60.0+1.19.2 and newer as incompatible, so if you get an "Incompatible mod set!" error, that's why.

**If you don't want to build OptiFabric yourself, and you trust me / are comfortable running unofficial binaries, here's a prebuilt jar:** https://developer.akemi.ai/Minecraft/optifabric-1.13.10~akemi-git-1f436b3.jar

**I've tested this to work with the following OptiFine versions:**
* OptiFine 1.19.2 HD U H9 (latest stable version as of this writing, get it from [the OptiFine downloads page](https://optifine.net/downloads))
* OptiFine 1.19.1 HD U H9 pre1 (the only 1.19.2-compatible version that was available when I initially wrote this post)

**Comment by CormacZ** [comment]
> I've implemented a similar temporary workaround (disabling the version check) [in my fork of OptiFabric](https://github.com/akemin-dayo/OptiFabric).
> 
> The source code is freely available for those who want to see exactly what was changed, and/or those who prefer building their own binaries locally.
> 
> I've changed the version number to `1.13.10~akemi` (plus the Git commit short SHA-1) in order to clearly differentiate it from the official upstream OptiFabric versions.
> 
> **※ IMPORTANT NOTE:** OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer. Please use Fabric API 0.59.0+1.19.2 (or older) instead.
> 
> My fork explicitly marks Fabric API 0.60.0+1.19.2 and newer as incompatible, so if you get an "Incompatible mod set!" error, that's why.
> 
> **If you don't want to build OptiFabric yourself, and you trust me / are comfortable running unofficial binaries, here's a prebuilt jar:** https://developer.akemi.ai/Minecraft/optifabric-1.13.10~akemi-git-1f436b3.jar
> 
> **I've tested this to work with the following OptiFine versions:**
> 
> * OptiFine 1.19.2 HD U H9 (latest stable version as of this writing, get it from [the OptiFine downloads page](https://optifine.net/downloads))
> * OptiFine 1.19.1 HD U H9 pre1 (the only 1.19.2-compatible version that was available when I initially wrote this post)

Oh wow nice, they updated to 1.19.2 already. I hope Chocohead update this mod. Or maybe you will do it before him :P

**Comment by FlashLight34** [comment]
i tryed with latest fabric API and that crash , but with [[1.19.2] Fabric API 0.58.6+1.19.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3919445) that work :)

**Comment by MOOOOs** [comment]
Why wont 0.60.0 be incompatible what needs to be changed to make it compatible i want to learn so I can make patches for other mods also myself

**Comment by topia** [comment]
Optifabric is an exceptional mod.
Ordinary fabric mod (including fabric API) is patching Minecraft code straight, so major Minecraft updates or (sometimes) another mod make an incompatibility. in contrast, optifine seems to be created by decompiling Minecraft class, modifying and recompiling it, and replacing the original one.
Optifabric replaces the Minecraft class with optifine's one in a more fabric-compatible way, but it's somewhat destructive because the optifine class and Minecraft class are not the same. So optifabric also patches fabric API and other incompatible mods to work with optifine.

**Comment by GEkXD3** [comment]
> > I've implemented a similar temporary workaround (disabling the version check) [in my fork of OptiFabric](https://github.com/akemin-dayo/OptiFabric).
> > The source code is freely available for those who want to see exactly what was changed, and/or those who prefer building their own binaries locally.
> > I've changed the version number to `1.13.10~akemi` (plus the Git commit short SHA-1) in order to clearly differentiate it from the official upstream OptiFabric versions.
> > **※ IMPORTANT NOTE:** OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer. Please use Fabric API 0.59.0+1.19.2 (or older) instead.
> > My fork explicitly marks Fabric API 0.60.0+1.19.2 and newer as incompatible, so if you get an "Incompatible mod set!" error, that's why.
> > **If you don't want to build OptiFabric yourself, and you trust me / are comfortable running unofficial binaries, here's a prebuilt jar:** https://developer.akemi.ai/Minecraft/optifabric-1.13.10~akemi-git-1f436b3.jar
> > **I've tested this to work with the following OptiFine versions:**
> > 
> > * OptiFine 1.19.2 HD U H9 (latest stable version as of this writing, get it from [the OptiFine downloads page](https://optifine.net/downloads))
> > * OptiFine 1.19.1 HD U H9 pre1 (the only 1.19.2-compatible version that was available when I initially wrote this post)
> 
> Oh wow nice, they updated to 1.19.2 already. I hope Chocohead update this mod. Or maybe you will do it before him :P

![javaw_0kHXPEUQkV](https://user-images.githubusercontent.com/106906668/187041716-d5e11f25-7c85-4ee8-a144-24af6d1296bc.png)

Not working

**Comment by GEkXD3** [comment]
> I've implemented a similar temporary workaround (disabling the version check) [in my fork of OptiFabric](https://github.com/akemin-dayo/OptiFabric).
> 
> The source code is freely available for those who want to see exactly what was changed, and/or those who prefer building their own binaries locally.
> 
> I've changed the version number to `1.13.10~akemi` (plus the Git commit short SHA-1) in order to clearly differentiate it from the official upstream OptiFabric versions.
> 
> **※ IMPORTANT NOTE:** OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer. Please use Fabric API 0.59.0+1.19.2 (or older) instead.
> 
> My fork explicitly marks Fabric API 0.60.0+1.19.2 and newer as incompatible, so if you get an "Incompatible mod set!" error, that's why.
> 
> **If you don't want to build OptiFabric yourself, and you trust me / are comfortable running unofficial binaries, here's a prebuilt jar:** https://developer.akemi.ai/Minecraft/optifabric-1.13.10~akemi-git-1f436b3.jar
> 
> **I've tested this to work with the following OptiFine versions:**
> 
>     * OptiFine 1.19.2 HD U H9 (latest stable version as of this writing, get it from [the OptiFine downloads page](https://optifine.net/downloads))
> 
>     * OptiFine 1.19.1 HD U H9 pre1 (the only 1.19.2-compatible version that was available when I initially wrote this post)

Not working
![javaw_0kHXPEUQkV](https://user-images.githubusercontent.com/106906668/187041744-afe02bb9-c330-4a01-aee4-3b42f68ee322.png)

**Comment by akemin-dayo** [comment]
@GEkXD3 You need to download OptiFine and put it in your mods folder. https://optifine.net/downloads

**Comment by ghost** [comment]
> @GEkXD3 You need to download OptiFine and put it in your mods folder. https://optifine.net/downloads

Hey Karen, may I ask if you know why it won't work with Fabric API 0.60? Also Nice to see an iOS developer elsewhere, Used your tweaks for years!

**Comment by MOOOOs** [comment]
You need 0.59 Api to work i guess 0.60 changed something that broke compatibility and needs patching

**Comment by ghost** [comment]
> You need 0.59 Api to work i guess 0.60 changed something that broke compatibility and needs patching

Yeah, I mean I aint updated Optifabric to 1.13.10 either, so was more curious if she knew what broke more than anything. Im well aware I can't use latest API..
