### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by BoyceKRP** [Chocohead/OptiFabric#832]
Hello,

I can't seem to open my game with OptiFabric, and I can't understand where the issue lies.

![Capture](https://user-images.githubusercontent.com/111043426/184081744-d5d241c1-09b1-4b14-b238-c085454d1b8d.PNG)

The game will launch with API 0.59.0 but crashed when I attach the updated Optifabric 0.13.10.
The suggested remedy is to change to Minecraft 1.19.1, however that does not work either. I've ran the game in vanilla 1.19.2 to launch already.

**Comment by topia** [comment]
Optifabric doesn't support minecraft 1.19.2 yet, and its development will not start until optifine supports 1.19.2

**Comment by topia** [comment]
And you installed optifine for 1.19 on your mod folder, it does not support 1.19.1.

**Comment by BoyceKRP** [comment]
Do I need to change my Fabric file then?? The issue occurred before I had the optifine file installed.

**Comment by topia** [comment]
I think you have three options:

1. using Minecraft 1.19.2 without optifabric/optifine
2. downgrade to Minecraft 1.19.1 (and compatible fabric-api), change optifine to 1.19.1 pre1.
3. downgrade to Minecraft 1.19 (and compatible fabric-api, xaeros mods)

**Comment by BoyceKRP** [comment]
The second option worked out for me. Thank you!
