### ISSUE TITLE
[1.19] Crash when rendering some Supplementaries objects

### ISSUE THREAD

**Issue by JLUsr** [Chocohead/OptiFabric#837]
OptiFabric-v1.13.10

The following Objects from Supplementaries will not render when placed if OptiFabric is present, resulting in a crash. The crash report contains the same content regardless of which one caused the crash to occur, the crash will also occur regardless of if shaders are enabled or disabled.

- Hanging Sign
- Sign Post
- Wall Lantern (works just fine if placed normally)
- Flower Box
- Blackboard
- Rope attached to a Fence (works fine in other instances)

Report generated when placing the object in a world
crash-2022-08-12_17.42.23-server.txt

Report generated when loading world with objects already placed
crash-2022-08-12_18.01.04-server.txt

**Comment by MehVahdJukaar** [comment]
If anybody knows anything about this let me know. I assume it's due to optifabric changing the vertex format for baked models

**Comment by JLUsr** [comment]
These object are able to render in 1.19.2 now. I haven't encountered any issues personally; however, it should be noted that baked models have resulted in crashes with OptiFabric under unknown circumstances for some of my acquaintances.
