### ISSUE TITLE
Failed to load the game

### ISSUE THREAD

**Issue by Tenta-dev** [Chocohead/OptiFabric#842]
When i start the game it crash and idk why, if a mod cause that idk what is it and i do not have Twilight forest.

i tried some test but i'm lost.
Thx for the help !

[crash-2022-08-17_14.09.23-client.txt](https://github.com/Chocohead/OptiFabric/files/9359395/crash-2022-08-17_14.09.23-client.txt)

**Comment by topia** [comment]
#375 - incompatible between enhancedcelestials and optifabric

**Comment by Tenta-dev** [comment]
Okay thx i'll check that. Have a nice day
