### ISSUE TITLE
OptiFine 1.19.1 does not load...  OptiFabric itself works fine tho.

### ISSUE THREAD

**Issue by dagniuskasoje** [Chocohead/OptiFabric#845]
![image](https://user-images.githubusercontent.com/111526420/185451821-51cf79c5-1910-43b9-8683-6ba1a4300dd4.png)
![image](https://user-images.githubusercontent.com/111526420/185451844-c6cb68be-2536-4b9f-ae3c-df49fc4e19d7.png)

**Comment by topia** [comment]
On [the reply on 1.19.2 issue](https://github.com/Chocohead/OptiFabric/issues/824#issuecomment-1216366222), they mentioned about Fabric API 0.60.0+1.19.2 is incompatible with optifabric (1.13.x).
> ※ IMPORTANT NOTE: OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer.
Please use Fabric API 0.59.0+1.19.2 (or older) instead.

This should be applied to you too, could you try downgrading it (fabric API)?

**Comment by dagniuskasoje** [comment]
> On [the reply on 1.19.2 issue](https://github.com/Chocohead/OptiFabric/issues/824#issuecomment-1216366222), they mentioned about Fabric API 0.60.0+1.19.2 is incompatible with optifabric (1.13.x).
> 
> > ※ IMPORTANT NOTE: OptiFabric 1.13.10 is incompatible with Fabric API 0.60.0+1.19.2 and newer.
> > Please use Fabric API 0.59.0+1.19.2 (or older) instead.
> 
> This should be applied to you too, could you try downgrading it (fabric API)?

Thank you so much. It works now,
