### ISSUE TITLE
I'll wait for 1.19.2

### ISSUE THREAD

**Issue by ZMGrey** [Chocohead/OptiFabric#852]
I know making a mod loader is not easy, so I can wait a little while for the 1.19.2 MC version of OptiFabric.
Keep up the awesome work that is being done.
Thank you for making a mod loader that connect OptiFine capabilities with Fabric simplicity.

Sincerley ZMGrey

**Comment by umioMikket** [comment]
yea im waiting update

**Comment by akemin-dayo** [comment]
If you would like to use it right now: https://github.com/Chocohead/OptiFabric/issues/824#issuecomment-1216366222

**Comment by MOOOOs** [comment]
> If you would like to use it right now: [#824 (comment)](https://github.com/Chocohead/OptiFabric/issues/824#issuecomment-1216366222)

hey is this possible to make fork for 0.60 i want to learn but idk where to start
