### ISSUE TITLE
Batching Chunks Error(Only occurs with optifabric using optifine shaders but not with Sodium+Iris)

### ISSUE THREAD

**Issue by Tawhirimatea5** [Chocohead/OptiFabric#859]
[crash-2022-08-30_04.44.41-server.txt](https://github.com/Chocohead/OptiFabric/files/9452613/crash-2022-08-30_04.44.41-server.txt)

So for the 1.19 version of the mod I consistently crash in a specific chunk region everytime and so far it has only occurred in that specific area. I already have a solid amount of playtime on the world before the error started happening and it appears to not occur if I can get away from the area in time, although this is tedious. I was wondering if anyone has had the issue before or if it is a known issue and a fix is in the works? Many thanks.

**Comment by djsimmonds** [comment]
Is there any chance this fix for ChunkCacheOF will be backported to 1.18.2? Just checking, thanks for all your work.
