### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Zarpyk** [Chocohead/OptiFabric#87]
OptiFine HD U G4 pre2
Optifabric 1.7.0
Log: https://gist.github.com/GuerreroCraft61/65a70e2ea67cb9016a14d727859e0a0b

"Fixed" when update dawn-api mods (now I have other crashs XD)

**Comment by Chocohead** [comment]
This will be a problem for any Dawn API version between 1.3 (inclusive) and 1.4.1 (exclusive), shouldn't be a difficult fix.
