### ISSUE TITLE
Crash while initializing 1.19.2 - mixin problem

### ISSUE THREAD

**Issue by MIHR413** [Chocohead/OptiFabric#874]
I'm seeing this issue when trying to launch the game:
![image](https://user-images.githubusercontent.com/83557519/189494557-fe7d2141-50f1-46ea-a544-ebf8e3201b0c.png)

And these are the versions of the mods I have:
![image](https://user-images.githubusercontent.com/83557519/189494580-0e5a6821-1d84-4b2c-bea9-0e8455c152cf.png)

The full crash log is here:  https://pastebin.com/YN1y01YC

I've redownloaded the Optifabric and Optifine files in case they were damaged, but that hasn't fixed the problem. Any advice appreciated. Thank you!

**Comment by topia** [comment]
Please update optifabric to 1.13.16.

**Comment by MIHR413** [comment]
Don't know how I missed that! It's working fine now, thank you.
