### ISSUE TITLE
Conflict with Blur mod

### ISSUE THREAD

**Issue by Romz24** [Chocohead/OptiFabric#91]
When using the Blur mod, the game crashes. There is no problem without it. The problem appeared only on version 1.16.4 of minecraft, this was not the case before.

[crash-2020-11-04_22.09.10-client.txt](https://github.com/Chocohead/OptiFabric/files/5490014/crash-2020-11-04_22.09.10-client.txt)
[crash-2020-11-04_22.09.10-server.txt](https://github.com/Chocohead/OptiFabric/files/5490015/crash-2020-11-04_22.09.10-server.txt)

**Comment by Chocohead** [comment]
Did Blur actually work with OptiFabric before 1.16.4? I had only ever seen people saying it freeze the screen to dirt immediately after entering a world.

**Comment by IMS212** [comment]
does not work on 1.16.3, but with a different error when logging into a world. https://pastebin.com/uwyvY55p

**Comment by Romz24** [comment]
@Chocohead 

This actually works for me in **minecraft 1.16.3**, but only when using versions **OptiFabric-v1.7.0** and **OptiFine HD U G3** and all versions below which support 1.16.3

**Comment by Chocohead** [comment]
Does it work with a shader pack on too? It doesn't seem unreasonable that with Optifine alone it's fine but trying to apply shaders causes the conflict with Satin's shaders

**Comment by Romz24** [comment]
I don't use shaders, so I find it difficult to answer this question.

**Comment by Chocohead** [comment]
Having given it a try on both 1.16.3 and 1.16.4 this seems to be the combination which breaks things. I suppose I can make OptiFabric turn off any shader pack with Satin present rather than flat not working in any case.

**Comment by IMS212** [comment]
or optifabric could attempt to add it's own blur but that's probably out of scope
