### ISSUE TITLE
Optifabric conflicts with Just Enough Items

### ISSUE THREAD

**Issue by Chromatimania** [Chocohead/OptiFabric#933]
I play minecraft with a lot of mods which means figuring out recipes can be a bit of a challenge sometimes, so I decided to try and add Just Enough Items to the game. 

I tried every version of JEI, and all of them either crashed near instantly, or needed a new version of the fabric API, which also crashed once added. I didn't try different versions of OptiFabric (OF from now on) as there appeared to only be 1 version for 1.19.2. I'm using Optifine 1.19.2 HD U H9.

Both OF and JEI work with every other mod in the folder, but as soon as they're put together the game starts crashing.

I play Minecraft Java 1.19.2 on Windows 10 with Java version 11.0.8 if that helps any

The log I get during crashes (Can't find crash report) is attached

[latest.log] (https://github.com/Chocohead/OptiFabric/files/10299375/latest.log)

**Comment by itsMarkiS** [comment]
try using Roughly Enough Items

**Comment by Chromatimania** [comment]
> try using Roughly Enough Items

It worked
It looked like it just going to load forever the first time i started it up, but I disabled it (by putting .disable after the file extension,) started fabric back up, then enabled it again and restarted fabric and it works now
