### ISSUE TITLE
Minecraft keeps crashing 

### ISSUE THREAD

**Issue by somegirlmeme** [Chocohead/OptiFabric#943]
I tried replacing some mods and deleting some, but I think the problem is with optfine and or optifabric. I played this version without optifine and optifabric and it worked. Unfortunately, I can't switch to Sodium because Lum is incompatible with it and iris shaders.
Versions: fabric-api-0.67.0+1.18.2, OptiFine_1.18.2_HD_U_H7, optifabric-1.13.16
**This is my log without optifine and optifabric**
[latest.log](https://github.com/Chocohead/OptiFabric/files/10366258/latest.log)
**Below is my log with optifine and optifabric**
[latest 2.log](https://github.com/Chocohead/OptiFabric/files/10366269/latest.2.log)
and here's the exit code
![Annotation 2023-01-07 064127](https://user-images.githubusercontent.com/88017688/211151163-9ed9cab0-9ff6-4553-9662-f6d59a5cc737.png)

**Comment by topia** [comment]
> This is my log with optifine and optifabric
[latest 2.log](https://github.com/Chocohead/OptiFabric/files/10366269/latest.2.log)

I suspect your latest log was truncated because I can't find the message shown in the screenshot in the latest.log.

**Comment by somegirlmeme** [comment]
I'm sorry will this help? This is the crash report
[crash-2023-01-07_06.38.28-client.txt](https://github.com/Chocohead/OptiFabric/files/10366755/crash-2023-01-07_06.38.28-client.txt)

**Comment by topia** [comment]
This log shows that `immersive_weathering` and `optifine` might be incompatible.
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderFlowerCrown(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_1309;Lnet/minecraft/class_1304;ILnet/minecraft/class_572;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1799;Lnet/minecraft/class_1738;ZZ)V in immersive_weathering.mixins.json:ArmorLayerMixin from mod immersive_weathering failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap immersive_weathering-fabric-refmap.json
```

I think you should start with a fresh mod set; optifine and other mods are sometimes incompatible. You need to read the latest log to spot the root cause.

**Comment by somegirlmeme** [comment]
thank you that was an issue. minecraft can open up now but crashes with a different error. I'll try trying every mod with optifine and optifabric to troubleshoot it. thank you for your hindsight.

**Comment by somegirlmeme** [comment]
After the troubleshooting, I finally fixed it and the problem was the bumblezone, immersive weather, jei, blur, CHAS, and Enhance Celestials.
