### ISSUE TITLE
Crash when starting 1.18.1

### ISSUE THREAD

**Issue by Benike77** [Chocohead/OptiFabric#945]
Whenever starting OptiFabric with 1 other mod,it simply crashes.
I appreciate any help.
![mods 08_01_2023 16_09_49](https://user-images.githubusercontent.com/93082319/211207063-316445be-6584-4ea4-9abb-e9a849c8388f.png)

**Comment by topia** [comment]
Which one did you mention? In your screenshot, I can see two mods exclude optifabric/optifine.
By the way, if you mentioned sodium, sodium and optifine/optifabric are incompatible by design and can't use together; no workaround for it.

**Comment by Benike77** [comment]
> Which one did you mention? In your screenshot, I can see two mods exclude optifabric/optifine. By the way, if you mentioned sodium, sodium and optifine/optifabric are incompatible by design and can't use together; no workaround for it.

I meant sodium,thanks for the info.
