### ISSUE TITLE
Incompatibility with architectury mod "Roughly Enough Items" dependency OR "Just Enough Items" with OptiFabric 1.19.3 beta

### ISSUE THREAD

**Issue by juliocoliveira** [Chocohead/OptiFabric#978]
OptiFabric 1.19.3 version is not compatible with two mods, Here is the comments I sent on "1.19.3 Support" issue, I thought it was the best thing to create a separate issue.

I don't understand much but the problem seems to be incompatibility with architectury.

Well the log is the same in file or text, But if you care about it that much here it is: https://github.com/Chocohead/OptiFabric/files/10832471/latest.log

I tested that theory, and it was right, OptiFabric 1.19.3 beta is not compatible with architectury mod, And that is required for

"Roughly Enough Items". Without "Roughly Enough Items" and it's dependencies like "architectury", The game runs fine.
OptiFabric 1.19.3 is not compatible with "Roughly Enough Items" or
"Just Enough Items" here is the log for another crash related to "Just Enough Items" and OptiFabric, Tested without Optifabric and the game loads fine, tested with optifabric and
without "Just Enough Items" and the game loads fine, The issue is "Just Enough Items" with OptiFabric.
Just enough items log: https://mclo.gs/jBSOHDk

**Comment by Jenthevz** [comment]
there is an optifabric  1.19.3? where can you give link

**Comment by juliocoliveira** [comment]
> there is an optifabric 1.19.3? where can you give link

https://github.com/Chocohead/OptiFabric/suites/11122716797/artifacts/566927779

Use only one "optifabric-1.13.21.jar"

**Comment by Jenthevz** [comment]
thank you!

**Comment by Rofumer** [comment]
> > there is an optifabric 1.19.3? where can you give link
> 
> https://github.com/Chocohead/OptiFabric/suites/11122716797/artifacts/566927779
> 
> Use only one "optifabric-1.13.21.jar"

Could you say, where are the gradle sources for this artifact. Thank you )

**Comment by juliocoliveira** [comment]
> > > there is an optifabric 1.19.3? where can you give link
> > 
> > 
> > https://github.com/Chocohead/OptiFabric/suites/11122716797/artifacts/566927779
> > Use only one "optifabric-1.13.21.jar"
> 
> Could you say, where are the gradle sources for this artifact. Thank you )

No I could not, And that is off-topic. Guys this issue is about the incompatibility of mods, not to get stuff!

**Comment by Gregor7008** [comment]
Can confirm, have the same problem at the moment. As soon as I remove architectury, the game runs fine.
Logs: https://pastebin.com/PaYZ2JUT

**Comment by Bobbies2** [comment]
why does Optifabric always have issues with architecture?

**Comment by Mielie23** [comment]
The issue in my case was that Gnemboms Carpet mod was causing the crash please add support for carpet mod

**Comment by Chocohead** [comment]
> why does Optifabric always have issues with architecture?

Architectury (for Fabric) will often add mixins to replicate Forge patches. OptiFine also includes Forge's patches as a way of supporting running with Forge. Sometimes this causes a conflict where OptiFine's inclusion of a patch confuses/moves/breaks Architectury's mixin to the same place.

It would be nice if OptiFine didn't include all the Forge patches it doesn't use, but sp614x (reasonably) doesn't want the headaches that would bring trying to make OptiFine in the first place.
