### ISSUE TITLE
Please update to 1.19.3!!!

### ISSUE THREAD

**Issue by SkyKingPX** [Chocohead/OptiFabric#993]
I need it for other plugins. Otherwise it won`t work!

**Comment by topia** [comment]
You should refer to another issue for the beta version. The developer should release it when optifine is released.

**Comment by SkyKingPX** [comment]
You mean when there is a release and no preview?

**Comment by SkyKingPX** [comment]
@topia What do you mean with „beta version“? Is there a version for 1.19.3?

**Comment by topia** [comment]
> You mean when there is a release and no preview?

Yes.


> @topia What do you mean with „beta version“? Is there a version for 1.19.3?

Yes, you can download not-released builds from the actions' artifacts. Try searching "1.19.3" issues in this repository.

**Comment by SkyKingPX** [comment]
@topia And where are these „not-released builds“?

**Comment by SkyKingPX** [comment]
Thanks, I got it already

**Comment by yeqes** [comment]
where are the non released builds

**Comment by SkyKingPX** [comment]
@yeqes Here the first answer: https://github.com/Chocohead/OptiFabric/issues/971
