### ISSUE TITLE
1.19.3 optifabric missing "mm 2.0"

### ISSUE THREAD

**Issue by GamingGuyRob** [Chocohead/OptiFabric#996]
I have no idea what this mod is or where to find it. I've searched and can't find any mention of it.

I am using 1.13.21-dev, 1.13.21-sources-dev and 1.19.3_HD_U_I2_pre5.

I have also tried using all the other variants of Optifabric. 1.13.21 just crashes on launch. I have tried without the sources and got the same result.

**Comment by topia** [comment]
Do not use `-dev.jar`. if you use `1.13.21.jar`, that message should be disappeared.

**Comment by GamingGuyRob** [comment]
> 

When I use that, the game crashes upon start-up

**Comment by GamingGuyRob** [comment]
> Do not use `-dev.jar`. if you use `1.13.21.jar`, that message should be disappeared.
When I use that, the game crashes on startup - even with no other mods

**Comment by GamingGuyRob** [comment]
> Do not use `-dev.jar`. if you use `1.13.21.jar`, that message should be disappeared.

Ok. I tried that and the game did load with only those mods, but it looks like it's not compatible with the Fabric API (as previously reported, I am seeing). I will just have to wait until those issues are resolved as I need the API for the other mods I am using. 

Thank you for your assistance

**Comment by XXMA16** [comment]
What mods are you using? Please provide the versions for each one of them. Also do **not** use any version of Optifabric that ends with `dev` or `sources`

**Comment by GamingGuyRob** [comment]
![image](https://user-images.githubusercontent.com/49712816/226081751-07bdfd96-28c1-464c-951c-9d81a306b8d1.png)
